/**The class is automatically generated by BatMain.bat , please do not modify */
export const enum NetCMD {
	/**
	 * @param output {@link IUser}
	 */
	SyncInfo = "NetCMD_SyncInfo",

	/**
	 * @param output {@link IRegisterOutput}
	 * @param input {@link IRegisterInput}
	 */
	Register = "NetCMD_Register",

	/**
	 * @param output {@link IRegisterOutput}
	 * @param input {@link IRegisterInput}
	 */
	RegisterError = "NetCMD_Register_Error",

	/**
	 * @param output {@link ILoginOutput}
	 * @param input {@link ILoginInput}
	 */
	Login = "NetCMD_Login",

	/**
	 * @param output {@link ILoginOutput}
	 * @param input {@link ILoginInput}
	 */
	LoginError = "NetCMD_Login_Error",

	/**
	 * @param output {@link ISignInOutput}
	 * @param input {@link ISignInInput}
	 */
	SignIn = "NetCMD_SignIn",

	/**
	 * @param output {@link ISignInOutput}
	 * @param input {@link ISignInInput}
	 */
	SignInError = "NetCMD_SignIn_Error",

	/**
	 * @param output {@link IClearAccountOutput}
	 * @param input {@link IClearAccountInput}
	 */
	ClearAccount = "NetCMD_ClearAccount",

	/**
	 * @param output {@link IClearAccountOutput}
	 * @param input {@link IClearAccountInput}
	 */
	ClearAccountError = "NetCMD_ClearAccount_Error",

	/**
	 * @param output {@link IUseItemOutput}
	 * @param input {@link IUseItemInput}
	 */
	UseItem = "NetCMD_UseItem",

	/**
	 * @param output {@link IUseItemOutput}
	 * @param input {@link IUseItemInput}
	 */
	UseItemError = "NetCMD_UseItem_Error",

	/**
	 * @param output {@link ISellItemOutput}
	 * @param input {@link ISellItemInput}
	 */
	SellItem = "NetCMD_SellItem",

	/**
	 * @param output {@link ISellItemOutput}
	 * @param input {@link ISellItemInput}
	 */
	SellItemError = "NetCMD_SellItem_Error",

	/**
	 * @param output {@link IChangeCollectOutput}
	 * @param input {@link IChangeCollectInput}
	 */
	ChangeCollect = "NetCMD_ChangeCollect",

	/**
	 * @param output {@link IChangeCollectOutput}
	 * @param input {@link IChangeCollectInput}
	 */
	ChangeCollectError = "NetCMD_ChangeCollect_Error",

	/**
	 * @param output {@link IDecomposeGemOutput}
	 * @param input {@link IDecomposeGemInput}
	 */
	DecomposeGem = "NetCMD_DecomposeGem",

	/**
	 * @param output {@link IDecomposeGemOutput}
	 * @param input {@link IDecomposeGemInput}
	 */
	DecomposeGemError = "NetCMD_DecomposeGem_Error",

	/**
	 * @param output {@link IDressEquipOutput}
	 * @param input {@link IDressEquipInput}
	 */
	DressEquip = "NetCMD_DressEquip",

	/**
	 * @param output {@link IDressEquipOutput}
	 * @param input {@link IDressEquipInput}
	 */
	DressEquipError = "NetCMD_DressEquip_Error",

	/**
	 * @param output {@link ITakeOffEquipOutput}
	 * @param input {@link ITakeOffEquipInput}
	 */
	TakeOffEquip = "NetCMD_TakeOffEquip",

	/**
	 * @param output {@link ITakeOffEquipOutput}
	 * @param input {@link ITakeOffEquipInput}
	 */
	TakeOffEquipError = "NetCMD_TakeOffEquip_Error",

	/**
	 * @param output {@link ISellEquipOutput}
	 * @param input {@link ISellEquipInput}
	 */
	SellEquip = "NetCMD_SellEquip",

	/**
	 * @param output {@link ISellEquipOutput}
	 * @param input {@link ISellEquipInput}
	 */
	SellEquipError = "NetCMD_SellEquip_Error",

	/**
	 * @param output {@link IDecomposeEquipOutput}
	 * @param input {@link IDecomposeEquipInput}
	 */
	DecomposeEquip = "NetCMD_DecomposeEquip",

	/**
	 * @param output {@link IDecomposeEquipOutput}
	 * @param input {@link IDecomposeEquipInput}
	 */
	DecomposeEquipError = "NetCMD_DecomposeEquip_Error",

	/**
	 * @param output {@link IEnterBattleOutput}
	 * @param input {@link IEnterBattleInput}
	 */
	EnterBattle = "NetCMD_EnterBattle",

	/**
	 * @param output {@link IEnterBattleOutput}
	 * @param input {@link IEnterBattleInput}
	 */
	EnterBattleError = "NetCMD_EnterBattle_Error",

	/**
	 * @param output {@link IExitBattleOutput}
	 * @param input {@link IExitBattleInput}
	 */
	ExitBattle = "NetCMD_ExitBattle",

	/**
	 * @param output {@link IExitBattleOutput}
	 * @param input {@link IExitBattleInput}
	 */
	ExitBattleError = "NetCMD_ExitBattle_Error",

	/**
	 * @param output {@link IStartGatherOutput}
	 * @param input {@link IStartGatherInput}
	 */
	StartGather = "NetCMD_StartGather",

	/**
	 * @param output {@link IStartGatherOutput}
	 * @param input {@link IStartGatherInput}
	 */
	StartGatherError = "NetCMD_StartGather_Error",

	/**
	 * @param output {@link IBreakOffGatherOutput}
	 * @param input {@link IBreakOffGatherInput}
	 */
	BreakOffGather = "NetCMD_BreakOffGather",

	/**
	 * @param output {@link IBreakOffGatherOutput}
	 * @param input {@link IBreakOffGatherInput}
	 */
	BreakOffGatherError = "NetCMD_BreakOffGather_Error",

	/**
	 * @param output {@link IAddFriendOutput}
	 * @param input {@link IAddFriendInput}
	 */
	AddFriend = "NetCMD_AddFriend",

	/**
	 * @param output {@link IAddFriendOutput}
	 * @param input {@link IAddFriendInput}
	 */
	AddFriendError = "NetCMD_AddFriend_Error",

	/**
	 * @param output {@link IFriendMsgOutput}
	 * @param input {@link IFriendMsgInput}
	 */
	FriendMsg = "NetCMD_FriendMsg",

	/**
	 * @param output {@link IFriendMsgOutput}
	 * @param input {@link IFriendMsgInput}
	 */
	FriendMsgError = "NetCMD_FriendMsg_Error",

	/**
	 * @param output {@link IBuyGoodsOutput}
	 * @param input {@link IBuyGoodsInput}
	 */
	BuyGoods = "NetCMD_BuyGoods",

	/**
	 * @param output {@link IBuyGoodsOutput}
	 * @param input {@link IBuyGoodsInput}
	 */
	BuyGoodsError = "NetCMD_BuyGoods_Error",
}