/**The class is automatically generated by BatMain.bat , please do not modify */
export const enum NetMessage {
	/** 参数类型：{@link IUserData} */
	SyncInfo = "NetMsg_SyncInfo",

	/** 参数类型：{@link RegisterOutput} & {@link  RegisterInput} */
	Register = "NetMsg_Register",

	/** 参数类型：{@link LoginOutput} & {@link  LoginInput} */
	Login = "NetMsg_Login",

	/** 参数类型：{@link ClearAccountOutput} & {@link  ClearAccountInput} */
	ClearAccount = "NetMsg_ClearAccount",

	/** 参数类型：{@link BattleOutput} & {@link  BattleInput} */
	StartBattle = "NetMsg_StartBattle",

	/** 参数类型：{@link AddFriendOutput} & {@link  AddFriendInput} */
	AddFriend = "NetMsg_AddFriend",

	/** 参数类型：{@link FriendMsgOutput} & {@link  FriendMsgInput} */
	FriendMsg = "NetMsg_FriendMsg",

	/** 参数类型：{@link HeartOutput} & {@link  HeartInput} */
	Heart = "NetMsg_Heart",

	/** 参数类型：{@link UseItemOutput} & {@link  UseItemInput} */
	UseItem = "NetMsg_UseItem",

	/** 参数类型：{@link SellItemOutput} & {@link  SellItemInput} */
	SellItem = "NetMsg_SellItem",

	/** 参数类型：{@link DressEquipOutput} & {@link  DressEquipInput} */
	DressEquip = "NetMsg_DressEquip",

	/** 参数类型：{@link TakeOffEquipOutput} & {@link  TakeOffEquipInput} */
	TakeOffEquip = "NetMsg_TakeOffEquip",

	/** 参数类型：{@link SellEquipOutput} & {@link  SellEquipInput} */
	SellEquip = "NetMsg_SellEquip",

	/** 参数类型：{@link ChangeCollectOutput} & {@link  ChangeCollectInput} */
	ChangeCollect = "NetMsg_ChangeCollect",

	/** 参数类型：{@link DecomposeEquipOutput} & {@link  DecomposeEquipInput} */
	DecomposeEquip = "NetMsg_DecomposeEquip",

	/** 参数类型：{@link BuyGoodsOutput} & {@link  BuyGoodsInput} */
	BuyGoods = "NetMsg_BuyGoods",
}