/**The class is automatically generated by BatMain.bat , please do not modify */
export const enum NetMessage {
	/**
	 * @param output? {@link IUserData}
	 */
	SyncInfo = "NetMsg_SyncInfo",

	/**
	 * @param output? {@link RegisterOutput}
	 * @param input? {@link  RegisterInput}
	 */
	Register = "NetMsg_Register",

	/**
	 * @param output? {@link LoginOutput}
	 * @param input? {@link  LoginInput}
	 */
	Login = "NetMsg_Login",

	/**
	 * @param output? {@link ClearAccountOutput}
	 * @param input? {@link  ClearAccountInput}
	 */
	ClearAccount = "NetMsg_ClearAccount",

	/**
	 * @param output? {@link BattleOutput}
	 * @param input? {@link  BattleInput}
	 */
	StartBattle = "NetMsg_StartBattle",

	/**
	 * @param output? {@link DressEquipOutput}
	 * @param input? {@link  DressEquipInput}
	 */
	DressEquip = "NetMsg_DressEquip",

	/**
	 * @param output? {@link TakeOffEquipOutput}
	 * @param input? {@link  TakeOffEquipInput}
	 */
	TakeOffEquip = "NetMsg_TakeOffEquip",

	/**
	 * @param output? {@link SellEquipOutput}
	 * @param input? {@link  SellEquipInput}
	 */
	SellEquip = "NetMsg_SellEquip",

	/**
	 * @param output? {@link DecomposeEquipOutput}
	 * @param input? {@link  DecomposeEquipInput}
	 */
	DecomposeEquip = "NetMsg_DecomposeEquip",

	/**
	 * @param output? {@link AddFriendOutput}
	 * @param input? {@link  AddFriendInput}
	 */
	AddFriend = "NetMsg_AddFriend",

	/**
	 * @param output? {@link FriendMsgOutput}
	 * @param input? {@link  FriendMsgInput}
	 */
	FriendMsg = "NetMsg_FriendMsg",

	/**
	 * @param output? {@link HeartOutput}
	 * @param input? {@link  HeartInput}
	 */
	Heart = "NetMsg_Heart",

	/**
	 * @param output? {@link UseItemOutput}
	 * @param input? {@link  UseItemInput}
	 */
	UseItem = "NetMsg_UseItem",

	/**
	 * @param output? {@link SellItemOutput}
	 * @param input? {@link  SellItemInput}
	 */
	SellItem = "NetMsg_SellItem",

	/**
	 * @param output? {@link ChangeCollectOutput}
	 * @param input? {@link  ChangeCollectInput}
	 */
	ChangeCollect = "NetMsg_ChangeCollect",

	/**
	 * @param output? {@link BuyGoodsOutput}
	 * @param input? {@link  BuyGoodsInput}
	 */
	BuyGoods = "NetMsg_BuyGoods",
}