/**The class is automatically generated by BatMain.bat , please do not modify */
export const enum NetMessage {
	/**
	 * @param output {@link IUserData}
	 */
	SyncInfo = "NetMsg_SyncInfo",

	/**
	 * @param output {@link RegisterOutput}
	 * @param input {@link RegisterInput}
	 */
	Register = "NetMsg_Register",

	/**
	 * @param output {@link RegisterOutput}
	 * @param input {@link RegisterInput}
	 */
	RegisterError = "NetMsg_Register_Error",

	/**
	 * @param output {@link LoginOutput}
	 * @param input {@link LoginInput}
	 */
	Login = "NetMsg_Login",

	/**
	 * @param output {@link LoginOutput}
	 * @param input {@link LoginInput}
	 */
	LoginError = "NetMsg_Login_Error",

	/**
	 * @param output {@link SignInOutput}
	 * @param input {@link SignInInput}
	 */
	SignIn = "NetMsg_SignIn",

	/**
	 * @param output {@link SignInOutput}
	 * @param input {@link SignInInput}
	 */
	SignInError = "NetMsg_SignIn_Error",

	/**
	 * @param output {@link ClearAccountOutput}
	 * @param input {@link ClearAccountInput}
	 */
	ClearAccount = "NetMsg_ClearAccount",

	/**
	 * @param output {@link ClearAccountOutput}
	 * @param input {@link ClearAccountInput}
	 */
	ClearAccountError = "NetMsg_ClearAccount_Error",

	/**
	 * @param output {@link UseItemOutput}
	 * @param input {@link UseItemInput}
	 */
	UseItem = "NetMsg_UseItem",

	/**
	 * @param output {@link UseItemOutput}
	 * @param input {@link UseItemInput}
	 */
	UseItemError = "NetMsg_UseItem_Error",

	/**
	 * @param output {@link SellItemOutput}
	 * @param input {@link SellItemInput}
	 */
	SellItem = "NetMsg_SellItem",

	/**
	 * @param output {@link SellItemOutput}
	 * @param input {@link SellItemInput}
	 */
	SellItemError = "NetMsg_SellItem_Error",

	/**
	 * @param output {@link ChangeCollectOutput}
	 * @param input {@link ChangeCollectInput}
	 */
	ChangeCollect = "NetMsg_ChangeCollect",

	/**
	 * @param output {@link ChangeCollectOutput}
	 * @param input {@link ChangeCollectInput}
	 */
	ChangeCollectError = "NetMsg_ChangeCollect_Error",

	/**
	 * @param output {@link DecomposeGemOutput}
	 * @param input {@link DecomposeGemInput}
	 */
	DecomposeGem = "NetMsg_DecomposeGem",

	/**
	 * @param output {@link DecomposeGemOutput}
	 * @param input {@link DecomposeGemInput}
	 */
	DecomposeGemError = "NetMsg_DecomposeGem_Error",

	/**
	 * @param output {@link DressEquipOutput}
	 * @param input {@link DressEquipInput}
	 */
	DressEquip = "NetMsg_DressEquip",

	/**
	 * @param output {@link DressEquipOutput}
	 * @param input {@link DressEquipInput}
	 */
	DressEquipError = "NetMsg_DressEquip_Error",

	/**
	 * @param output {@link TakeOffEquipOutput}
	 * @param input {@link TakeOffEquipInput}
	 */
	TakeOffEquip = "NetMsg_TakeOffEquip",

	/**
	 * @param output {@link TakeOffEquipOutput}
	 * @param input {@link TakeOffEquipInput}
	 */
	TakeOffEquipError = "NetMsg_TakeOffEquip_Error",

	/**
	 * @param output {@link SellEquipOutput}
	 * @param input {@link SellEquipInput}
	 */
	SellEquip = "NetMsg_SellEquip",

	/**
	 * @param output {@link SellEquipOutput}
	 * @param input {@link SellEquipInput}
	 */
	SellEquipError = "NetMsg_SellEquip_Error",

	/**
	 * @param output {@link DecomposeEquipOutput}
	 * @param input {@link DecomposeEquipInput}
	 */
	DecomposeEquip = "NetMsg_DecomposeEquip",

	/**
	 * @param output {@link DecomposeEquipOutput}
	 * @param input {@link DecomposeEquipInput}
	 */
	DecomposeEquipError = "NetMsg_DecomposeEquip_Error",

	/**
	 * @param output {@link EnterBattleOutput}
	 * @param input {@link EnterBattleInput}
	 */
	EnterBattle = "NetMsg_EnterBattle",

	/**
	 * @param output {@link EnterBattleOutput}
	 * @param input {@link EnterBattleInput}
	 */
	EnterBattleError = "NetMsg_EnterBattle_Error",

	/**
	 * @param output {@link RequestBattleOutput}
	 * @param input {@link RequestBattleInput}
	 */
	RequestBattle = "NetMsg_RequestBattle",

	/**
	 * @param output {@link RequestBattleOutput}
	 * @param input {@link RequestBattleInput}
	 */
	RequestBattleError = "NetMsg_RequestBattle_Error",

	/**
	 * @param output {@link ExistBattleOutput}
	 * @param input {@link ExistBattleInput}
	 */
	ExistBattle = "NetMsg_ExistBattle",

	/**
	 * @param output {@link ExistBattleOutput}
	 * @param input {@link ExistBattleInput}
	 */
	ExistBattleError = "NetMsg_ExistBattle_Error",

	/**
	 * @param output {@link AddFriendOutput}
	 * @param input {@link AddFriendInput}
	 */
	AddFriend = "NetMsg_AddFriend",

	/**
	 * @param output {@link AddFriendOutput}
	 * @param input {@link AddFriendInput}
	 */
	AddFriendError = "NetMsg_AddFriend_Error",

	/**
	 * @param output {@link FriendMsgOutput}
	 * @param input {@link FriendMsgInput}
	 */
	FriendMsg = "NetMsg_FriendMsg",

	/**
	 * @param output {@link FriendMsgOutput}
	 * @param input {@link FriendMsgInput}
	 */
	FriendMsgError = "NetMsg_FriendMsg_Error",

	/**
	 * @param output {@link BuyGoodsOutput}
	 * @param input {@link BuyGoodsInput}
	 */
	BuyGoods = "NetMsg_BuyGoods",

	/**
	 * @param output {@link BuyGoodsOutput}
	 * @param input {@link BuyGoodsInput}
	 */
	BuyGoodsError = "NetMsg_BuyGoods_Error",
}