/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import ComZhiZuo from "./ComZhiZuo";
import { ComZhiZuoView } from "../../view/PkgMain/view/coms/ComZhiZuoView";
import ComGoodsInfo from "./ComGoodsInfo";
import { ComGoodsInfoView } from "../../view/PkgMain/view/coms/ComGoodsInfoView";
import ComXinFa from "./ComXinFa";
import { ComXinFaView } from "../../view/PkgMain/view/coms/ComXinFaView";
import ItemXinFa from "./ItemXinFa";
import UISect from "./UISect";
import { UISectView } from "../../view/PkgMain/view/UISectView";
import UISphereTool from "./UISphereTool";
import { UISphereToolView } from "../../view/PkgMain/view/UISphereToolView";
import ComSetting from "./ComSetting";
import { ComSettingView } from "../../view/PkgMain/view/coms/ComSettingView";
import UIGoodsInfo from "./UIGoodsInfo";
import { UIGoodsInfoView } from "../../view/PkgMain/view/UIGoodsInfoView";
import RenderChatMsg from "./RenderChatMsg";
import { RenderChatMsgView } from "../../view/PkgMain/view/renders/RenderChatMsgView";
import BtnCheck from "./BtnCheck";
import { BtnCheckView } from "../../view/PkgMain/view/btns/BtnCheckView";
import UIChat from "./UIChat";
import { UIChatView } from "../../view/PkgMain/view/UIChatView";
import BtnMainKind from "./BtnMainKind";
import { BtnMainKindView } from "../../view/PkgMain/view/btns/BtnMainKindView";
import UIMain from "./UIMain";
import { UIMainView } from "../../view/PkgMain/view/UIMainView";
import RenderFriend from "./RenderFriend";
import { RenderFriendView } from "../../view/PkgMain/view/renders/RenderFriendView";
import ComSkill from "./ComSkill";
import { ComSkillView } from "../../view/PkgMain/view/coms/ComSkillView";
import ComTrain from "./ComTrain";
import { ComTrainView } from "../../view/PkgMain/view/coms/ComTrainView";
import UIPlayerInfo from "./UIPlayerInfo";
import { UIPlayerInfoView } from "../../view/PkgMain/view/UIPlayerInfoView";
import UIEquipmentInfo from "./UIEquipmentInfo";
import { UIEquipmentInfoView } from "../../view/PkgMain/view/UIEquipmentInfoView";
import ComGoods from "./ComGoods";
import { ComGoodsView } from "../../view/PkgMain/view/coms/ComGoodsView";
import ComShop from "./ComShop";
import { ComShopView } from "../../view/PkgMain/view/coms/ComShopView";
import ComChar from "./ComChar";
import { ComCharView } from "../../view/PkgMain/view/coms/ComCharView";
import ComAbode from "./ComAbode";
import { ComAbodeView } from "../../view/PkgMain/view/coms/ComAbodeView";
import RenderText from "./RenderText";
import { RenderTextView } from "../../view/PkgMain/view/renders/RenderTextView";
import CmbDongFu_item from "./CmbDongFu_item";
import CmbDongFu_popup from "./CmbDongFu_popup";
import CmbDongFu from "./CmbDongFu";
import UISetting from "./UISetting";
import { UISettingView } from "../../view/PkgMain/view/UISettingView";
import RenderGoods from "./RenderGoods";
import { RenderGoodsView } from "../../view/PkgMain/view/renders/RenderGoodsView";
import ComRenWu from "./ComRenWu";
import { ComRenWuView } from "../../view/PkgMain/view/coms/ComRenWuView";

export default class PkgMainBinder {
	public static bindAll(): void {
		fgui.UIObjectFactory.setExtension(ComZhiZuo.url, ComZhiZuoView);
		fgui.UIObjectFactory.setExtension(ComGoodsInfo.url, ComGoodsInfoView);
		fgui.UIObjectFactory.setExtension(ComXinFa.url, ComXinFaView);
		fgui.UIObjectFactory.setExtension(ItemXinFa.url, ItemXinFa);
		fgui.UIObjectFactory.setExtension(UISect.url, UISectView);
		fgui.UIObjectFactory.setExtension(UISphereTool.url, UISphereToolView);
		fgui.UIObjectFactory.setExtension(ComSetting.url, ComSettingView);
		fgui.UIObjectFactory.setExtension(UIGoodsInfo.url, UIGoodsInfoView);
		fgui.UIObjectFactory.setExtension(RenderChatMsg.url, RenderChatMsgView);
		fgui.UIObjectFactory.setExtension(BtnCheck.url, BtnCheckView);
		fgui.UIObjectFactory.setExtension(UIChat.url, UIChatView);
		fgui.UIObjectFactory.setExtension(BtnMainKind.url, BtnMainKindView);
		fgui.UIObjectFactory.setExtension(UIMain.url, UIMainView);
		fgui.UIObjectFactory.setExtension(RenderFriend.url, RenderFriendView);
		fgui.UIObjectFactory.setExtension(ComSkill.url, ComSkillView);
		fgui.UIObjectFactory.setExtension(ComTrain.url, ComTrainView);
		fgui.UIObjectFactory.setExtension(UIPlayerInfo.url, UIPlayerInfoView);
		fgui.UIObjectFactory.setExtension(UIEquipmentInfo.url, UIEquipmentInfoView);
		fgui.UIObjectFactory.setExtension(ComGoods.url, ComGoodsView);
		fgui.UIObjectFactory.setExtension(ComShop.url, ComShopView);
		fgui.UIObjectFactory.setExtension(ComChar.url, ComCharView);
		fgui.UIObjectFactory.setExtension(ComAbode.url, ComAbodeView);
		fgui.UIObjectFactory.setExtension(RenderText.url, RenderTextView);
		fgui.UIObjectFactory.setExtension(CmbDongFu_item.url, CmbDongFu_item);
		fgui.UIObjectFactory.setExtension(CmbDongFu_popup.url, CmbDongFu_popup);
		fgui.UIObjectFactory.setExtension(CmbDongFu.url, CmbDongFu);
		fgui.UIObjectFactory.setExtension(UISetting.url, UISettingView);
		fgui.UIObjectFactory.setExtension(RenderGoods.url, RenderGoodsView);
		fgui.UIObjectFactory.setExtension(ComRenWu.url, ComRenWuView);
	}
}