/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import BtnCheck from "./BtnCheck";
import CmbDongFu from "./CmbDongFu";
import BtnCornerTxt from "../PkgCommon/BtnCornerTxt";

export default class UISphereTool extends fgui.GComponent {

	public ctrlState:fgui.Controller;
	public c1:fgui.Controller;
	public graph_bg:fgui.GGraph;
	public btn_clearLog:BtnCornerTxt;
	public btn_recoverVigor:BtnCornerTxt;
	public btn_create:BtnCornerTxt;
	public btn_clear:BtnCornerTxt;
	public btn_percent:BtnCheck;
	public Ipt0:fgui.GTextInput;
	public Ipt1:fgui.GTextInput;
	public Ipt2:fgui.GTextInput;
	public Ipt3:fgui.GTextInput;
	public Ipt4:fgui.GTextInput;
	public Ipt5:fgui.GTextInput;
	public Ipt6:fgui.GTextInput;
	public Ipt7:fgui.GTextInput;
	public Ipt8:fgui.GTextInput;
	public Ipt9:fgui.GTextInput;
	public Ipt10:fgui.GTextInput;
	public Ipt11:fgui.GTextInput;
	public Ipt12:fgui.GTextInput;
	public Ipt13:fgui.GTextInput;
	public Ipt14:fgui.GTextInput;
	public Ipt15:fgui.GTextInput;
	public Ipt16:fgui.GTextInput;
	public Ipt17:fgui.GTextInput;
	public Ipt18:fgui.GTextInput;
	public Ipt19:fgui.GTextInput;
	public Ipt20:fgui.GTextInput;
	public Ipt21:fgui.GTextInput;
	public Ipt22:fgui.GTextInput;
	public Ipt23:fgui.GTextInput;
	public Ipt24:fgui.GTextInput;
	public Ipt25:fgui.GTextInput;
	public Ipt26:fgui.GTextInput;
	public Ipt27:fgui.GTextInput;
	public Ipt28:fgui.GTextInput;
	public btn_check1:BtnCheck;
	public btn_check2:BtnCheck;
	public btn_check3:BtnCheck;
	public btn_check4:BtnCheck;
	public btn_check5:BtnCheck;
	public btn_check6:BtnCheck;
	public btn_check7:BtnCheck;
	public btn_check8:BtnCheck;
	public btn_check9:BtnCheck;
	public btn_check10:BtnCheck;
	public btn_check11:BtnCheck;
	public btn_check12:BtnCheck;
	public btn_check13:BtnCheck;
	public btn_check14:BtnCheck;
	public btn_check15:BtnCheck;
	public btn_check16:BtnCheck;
	public btn_check17:BtnCheck;
	public btn_check18:BtnCheck;
	public btn_check19:BtnCheck;
	public btn_check20:BtnCheck;
	public btn_check21:BtnCheck;
	public btn_check22:BtnCheck;
	public btn_check23:BtnCheck;
	public btn_check24:BtnCheck;
	public btn_check25:BtnCheck;
	public btn_check26:BtnCheck;
	public btn_check27:BtnCheck;
	public btn_check28:BtnCheck;
	public btn_check0:BtnCheck;
	public input_31:fgui.GTextInput;
	public input_32:fgui.GTextInput;
	public btn_check31:BtnCheck;
	public btn_check32:BtnCheck;
	public btn_add:BtnCornerTxt;
	public btn_submit:BtnCornerTxt;
	public btn_remove:BtnCornerTxt;
	public btn_removeAll:BtnCornerTxt;
	public txt_content:fgui.GRichTextField;
	public cmb_item:CmbDongFu;
	public input_30:fgui.GTextInput;
	public input_29:fgui.GTextInput;
	public static URL:string = "ui://vith2b66e3vt1v";

	public static createInstance():UISphereTool {
		return <UISphereTool>(fgui.UIPackage.createObject("PkgMain", "UISphereTool"));
	}

	protected override onConstruct():void {
		this.ctrlState = this.getControllerAt(0);
		this.c1 = this.getControllerAt(1);
		this.graph_bg = <fgui.GGraph>(this.getChildAt(0));
		this.btn_clearLog = <BtnCornerTxt>(this.getChildAt(1));
		this.btn_recoverVigor = <BtnCornerTxt>(this.getChildAt(2));
		this.btn_create = <BtnCornerTxt>(this.getChildAt(8));
		this.btn_clear = <BtnCornerTxt>(this.getChildAt(9));
		this.btn_percent = <BtnCheck>(this.getChildAt(10));
		this.Ipt0 = <fgui.GTextInput>(this.getChildAt(69));
		this.Ipt1 = <fgui.GTextInput>(this.getChildAt(70));
		this.Ipt2 = <fgui.GTextInput>(this.getChildAt(71));
		this.Ipt3 = <fgui.GTextInput>(this.getChildAt(72));
		this.Ipt4 = <fgui.GTextInput>(this.getChildAt(73));
		this.Ipt5 = <fgui.GTextInput>(this.getChildAt(74));
		this.Ipt6 = <fgui.GTextInput>(this.getChildAt(75));
		this.Ipt7 = <fgui.GTextInput>(this.getChildAt(76));
		this.Ipt8 = <fgui.GTextInput>(this.getChildAt(77));
		this.Ipt9 = <fgui.GTextInput>(this.getChildAt(78));
		this.Ipt10 = <fgui.GTextInput>(this.getChildAt(79));
		this.Ipt11 = <fgui.GTextInput>(this.getChildAt(80));
		this.Ipt12 = <fgui.GTextInput>(this.getChildAt(81));
		this.Ipt13 = <fgui.GTextInput>(this.getChildAt(82));
		this.Ipt14 = <fgui.GTextInput>(this.getChildAt(83));
		this.Ipt15 = <fgui.GTextInput>(this.getChildAt(84));
		this.Ipt16 = <fgui.GTextInput>(this.getChildAt(85));
		this.Ipt17 = <fgui.GTextInput>(this.getChildAt(86));
		this.Ipt18 = <fgui.GTextInput>(this.getChildAt(87));
		this.Ipt19 = <fgui.GTextInput>(this.getChildAt(88));
		this.Ipt20 = <fgui.GTextInput>(this.getChildAt(89));
		this.Ipt21 = <fgui.GTextInput>(this.getChildAt(90));
		this.Ipt22 = <fgui.GTextInput>(this.getChildAt(91));
		this.Ipt23 = <fgui.GTextInput>(this.getChildAt(92));
		this.Ipt24 = <fgui.GTextInput>(this.getChildAt(93));
		this.Ipt25 = <fgui.GTextInput>(this.getChildAt(94));
		this.Ipt26 = <fgui.GTextInput>(this.getChildAt(95));
		this.Ipt27 = <fgui.GTextInput>(this.getChildAt(96));
		this.Ipt28 = <fgui.GTextInput>(this.getChildAt(97));
		this.btn_check1 = <BtnCheck>(this.getChildAt(98));
		this.btn_check2 = <BtnCheck>(this.getChildAt(99));
		this.btn_check3 = <BtnCheck>(this.getChildAt(100));
		this.btn_check4 = <BtnCheck>(this.getChildAt(101));
		this.btn_check5 = <BtnCheck>(this.getChildAt(102));
		this.btn_check6 = <BtnCheck>(this.getChildAt(103));
		this.btn_check7 = <BtnCheck>(this.getChildAt(104));
		this.btn_check8 = <BtnCheck>(this.getChildAt(105));
		this.btn_check9 = <BtnCheck>(this.getChildAt(106));
		this.btn_check10 = <BtnCheck>(this.getChildAt(107));
		this.btn_check11 = <BtnCheck>(this.getChildAt(108));
		this.btn_check12 = <BtnCheck>(this.getChildAt(109));
		this.btn_check13 = <BtnCheck>(this.getChildAt(110));
		this.btn_check14 = <BtnCheck>(this.getChildAt(111));
		this.btn_check15 = <BtnCheck>(this.getChildAt(112));
		this.btn_check16 = <BtnCheck>(this.getChildAt(113));
		this.btn_check17 = <BtnCheck>(this.getChildAt(114));
		this.btn_check18 = <BtnCheck>(this.getChildAt(115));
		this.btn_check19 = <BtnCheck>(this.getChildAt(116));
		this.btn_check20 = <BtnCheck>(this.getChildAt(117));
		this.btn_check21 = <BtnCheck>(this.getChildAt(118));
		this.btn_check22 = <BtnCheck>(this.getChildAt(119));
		this.btn_check23 = <BtnCheck>(this.getChildAt(120));
		this.btn_check24 = <BtnCheck>(this.getChildAt(121));
		this.btn_check25 = <BtnCheck>(this.getChildAt(122));
		this.btn_check26 = <BtnCheck>(this.getChildAt(123));
		this.btn_check27 = <BtnCheck>(this.getChildAt(124));
		this.btn_check28 = <BtnCheck>(this.getChildAt(125));
		this.btn_check0 = <BtnCheck>(this.getChildAt(126));
		this.input_31 = <fgui.GTextInput>(this.getChildAt(132));
		this.input_32 = <fgui.GTextInput>(this.getChildAt(133));
		this.btn_check31 = <BtnCheck>(this.getChildAt(134));
		this.btn_check32 = <BtnCheck>(this.getChildAt(135));
		this.btn_add = <BtnCornerTxt>(this.getChildAt(138));
		this.btn_submit = <BtnCornerTxt>(this.getChildAt(139));
		this.btn_remove = <BtnCornerTxt>(this.getChildAt(140));
		this.btn_removeAll = <BtnCornerTxt>(this.getChildAt(141));
		this.txt_content = <fgui.GRichTextField>(this.getChildAt(144));
		this.cmb_item = <CmbDongFu>(this.getChildAt(146));
		this.input_30 = <fgui.GTextInput>(this.getChildAt(147));
		this.input_29 = <fgui.GTextInput>(this.getChildAt(149));
	}
}