/**The script is automatically generated by BatMain.bat , please do not modify */
export const enum ViewID {
	/**Coms */
	ComNumInputView = "ComNumInputView",
	ComTipInfoView = "ComTipInfoView",
	ComDongFuView = "ComDongFuView",
	ComItemInfoView = "ComItemInfoView",
	ComJueSeView = "ComJueSeView",
	ComLiLianView = "ComLiLianView",
	ComRenWuView = "ComRenWuView",
	ComShangChengView = "ComShangChengView",
	ComSkillView = "ComSkillView",
	ComWuPinView = "ComWuPinView",
	ComXinFaView = "ComXinFaView",
	ComZhiZuoView = "ComZhiZuoView",

	/**Views */
	BattleView = "BattleView",
	ChooseBattleView = "ChooseBattleView",
	TipConfirmView = "TipConfirmView",
	LoginMainView = "LoginMainView",
	EquipmentInfoView = "EquipmentInfoView",
	MainView = "MainView",
	PlayerInfoView = "PlayerInfoView",
	SectView = "SectView",
	SettingView = "SettingView",
	SphereToolView = "SphereToolView",
}