/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface INetService extends IAccountCtrl, IBagCtrl, IBattleCtrl, IFriendCtrl, IShopCtrl {
	register(data: IRegisterInput): Promise<IRegisterOutput>;
	login(data: ILoginInput): Promise<ILoginOutput>;
	signIn(data: ISignInInput): Promise<ISignInOutput>;
	clearAccount(data: IClearAccountInput): Promise<IClearAccountOutput>;
	useItem(data: IUseItemInput): Promise<IUseItemOutput>;
	sellItem(data: ISellItemInput): Promise<ISellItemOutput>;
	changeCollect(data: IChangeCollectInput): Promise<IChangeCollectOutput>;
	decomposeGem(data: IDecomposeGemInput): Promise<IDecomposeGemOutput>;
	dressEquip(data: IDressEquipInput): Promise<IDressEquipOutput>;
	takeOffEquip(data: ITakeOffEquipInput): Promise<ITakeOffEquipOutput>;
	sellEquip(data: ISellEquipInput): Promise<ISellEquipOutput>;
	decomposeEquip(data: IDecomposeEquipInput): Promise<IDecomposeEquipOutput>;
	enterBattle(data: IEnterBattleInput): Promise<IEnterBattleOutput>;
	exitBattle(data: IExitBattleInput): Promise<IExitBattleOutput>;
	startGather(data: IStartGatherInput): Promise<IStartGatherOutput>;
	breakOffGather(data: IBreakOffGatherInput): Promise<IBreakOffGatherOutput>;
	addFriend(data: IAddFriendInput): Promise<IAddFriendOutput>;
	friendMsg(data: IFriendMsgInput): Promise<IFriendMsgOutput>;
	buyGoods(data: IBuyGoodsInput): Promise<IBuyGoodsOutput>;
}