/**The class is automatically generated by BatMain.bat , please do not modify */
export const enum NetResponse {
	/** 参数类型：{@link IUserData} */
	Response_SyncInfo = "Response_SyncInfo",

	/** 参数类型：{@link HeartOutput} */
	Response_Heart = "Response_Heart",

	/** 参数类型：{@link LoginOutput} */
	Response_Login = "Response_Login",

	/** 参数类型：{@link RegisterOutput} */
	Response_Register = "Response_Register",
}