/**The class is automatically generated by BatMain.bat , please do not modify */
export const enum NetResponse {
	/** 参数类型：{@link IUserData} */
	Response_SyncInfo = "Response_SyncInfo",

	/** 参数类型：{@link RegisterOutput} */
	Response_Register = "Response_Register",

	/** 参数类型：{@link LoginOutput} */
	Response_Login = "Response_Login",

	/** 参数类型：{@link ClearAccountOutput} */
	Response_ClearAccount = "Response_ClearAccount",

	/** 参数类型：{@link BattleOutput} */
	Response_StartBattle = "Response_StartBattle",

	/** 参数类型：{@link FriendMsgOutput} */
	Response_FriendMsg = "Response_FriendMsg",

	/** 参数类型：{@link HeartOutput} */
	Response_Heart = "Response_Heart",

	/** 参数类型：{@link UseItemOutput} */
	Response_UseItem = "Response_UseItem",

	/** 参数类型：{@link SellItemOutput} */
	Response_SellItem = "Response_SellItem",

	/** 参数类型：{@link DressEquipOutput} */
	Response_DressEquip = "Response_DressEquip",

	/** 参数类型：{@link TakeOffEquipOutput} */
	Response_TakeOffEquip = "Response_TakeOffEquip",

	/** 参数类型：{@link SellEquipOutput} */
	Response_SellEquip = "Response_SellEquip",

	/** 参数类型：{@link ChangeCollectOutput} */
	Response_ChangeCollect = "Response_ChangeCollect",

	/** 参数类型：{@link DecomposeEquipOutput} */
	Response_DecomposeEquip = "Response_DecomposeEquip",

	/** 参数类型：{@link BuyGoodsOutput} */
	Response_BuyGoods = "Response_BuyGoods",
}