/**The class is automatically generated by BatMain.bat , please do not modify */

import { ProxyAdapter } from "../libs/utils/ProxyAdapter";
import { ServiceObj } from "./ServiceObj";
import { websocket } from "./WebSocket";

class BaseService<T> {
    protected _proxy: T;
    protected constructor() {
        this._proxy = ProxyAdapter(ServiceObj.Objs, {
            get(_target, property) {
                return (args: UserInput) => {
                    args.cmd = property;
                    websocket.sendMsg(args);
                };
            }
        });
    }
}

function ServiceInst<T>() {
    return class ServiceInst extends BaseService<T>{
        protected static _inst: ServiceInst;
        static get Inst() { return (this._inst || (this._inst = new this()))._proxy; }
    }
}

export const AccountService = ServiceInst<IAccountCtrl>();
export const BattleService = ServiceInst<IBattleCtrl>();
export const EquipmentService = ServiceInst<IEquipmentCtrl>();
export const FriendService = ServiceInst<IFriendCtrl>();
export const HeartService = ServiceInst<IHeartCtrl>();
export const ItemHandleService = ServiceInst<IItemHandleCtrl>();
export const ShopService = ServiceInst<IShopCtrl>();