/**The class is automatically generated by BatMain.bat , please do not modify */

import { ServiceObj } from "./ServiceObj";
import { websocket } from "./WebSocket";

class BaseService<T> {
    protected _proxy: T;
    protected constructor() {
        Object.keys(ServiceObj.Objs).forEach(key => {
            Object.defineProperty(this, key, {
                configurable: false,
                enumerable: false,
                value: function (data: UserInput) {
                    data.cmd = key;
                    websocket.sendMsg(data);
                }
            })
        });
    }
}

function ServiceInst<T>() {
    return class ServiceInst extends BaseService<T>{
        protected static _inst: ServiceInst;
        static get Inst() { return (this._inst || (this._inst = new this())) as unknown as T; }
    }
}

export const AccountService = ServiceInst<IAccountCtrl>();
export const BagService = ServiceInst<IBagCtrl>();
export const BattleService = ServiceInst<IBattleCtrl>();
export const FriendService = ServiceInst<IFriendCtrl>();
export const ShopService = ServiceInst<IShopCtrl>();