/** This script is generated automatically, Please do not any modify! */
declare interface CfgItem {
	readonly [key: string]: CfgItemData;
	/** 金币 */
	readonly 1001: CfgItemData;
	/** 元宝 */
	readonly 1002: CfgItemData;
	/** 经验 */
	readonly 1003: CfgItemData;
	/** 魔核 */
	readonly 1004: CfgItemData;
	/** 魔币 */
	readonly 1005: CfgItemData;
	/** 灵石 */
	readonly 1006: CfgItemData;
	/** 魂魄 */
	readonly 1007: CfgItemData;
	/** 宝石积分 */
	readonly 1008: CfgItemData;
	/** 精力 */
	readonly 1009: CfgItemData;
	/** 1百万金币 */
	readonly 2000: CfgItemData;
	/** 1亿金币 */
	readonly 2001: CfgItemData;
	/** 50元宝 */
	readonly 2002: CfgItemData;
	/** 100元宝 */
	readonly 2003: CfgItemData;
	/** 500元宝 */
	readonly 2004: CfgItemData;
	/** 1000元宝 */
	readonly 2005: CfgItemData;
	/** 10000元宝 */
	readonly 2006: CfgItemData;
	/** 副本重置卡 */
	readonly 2007: CfgItemData;
	/** 秘境重置卡 */
	readonly 2008: CfgItemData;
	/** BOSS重置卡 */
	readonly 2009: CfgItemData;
	/** 门派邀请函 */
	readonly 2010: CfgItemData;
	/** 首充礼包 */
	readonly 2011: CfgItemData;
	/** 首充礼包2 */
	readonly 2012: CfgItemData;
	/** 微型经验胶囊 */
	readonly 2013: CfgItemData;
	/** 小型经验胶囊 */
	readonly 2014: CfgItemData;
	/** 中型经验胶囊 */
	readonly 2015: CfgItemData;
	/** 大型经验胶囊 */
	readonly 2016: CfgItemData;
	/** 巨型经验胶囊 */
	readonly 2017: CfgItemData;
	/** 碎石头 */
	readonly 3000: CfgItemData;
	/** 重铸石 */
	readonly 3001: CfgItemData;
	/** 绿松石 */
	readonly 3002: CfgItemData;
	/** 强化石 */
	readonly 3003: CfgItemData;
	/** 小魔石 */
	readonly 3004: CfgItemData;
	/** 玄星石 */
	readonly 3005: CfgItemData;
	/** 空冥石 */
	readonly 3006: CfgItemData;
	/** 龙血石 */
	readonly 3007: CfgItemData;
	/** 防爆符 */
	readonly 3008: CfgItemData;
	/** 卷轴·强化10 */
	readonly 3009: CfgItemData;
	/** 极冰石胆 */
	readonly 3010: CfgItemData;
	/** 神器碎片 */
	readonly 3011: CfgItemData;
	/** 古兰玉 */
	readonly 3012: CfgItemData;
	/** 青龙宝珠 */
	readonly 3013: CfgItemData;
	/** 朱雀宝珠 */
	readonly 3014: CfgItemData;
	/** 白虎宝珠 */
	readonly 3015: CfgItemData;
	/** 玄武宝珠 */
	readonly 3016: CfgItemData;
	/** 龙鳞 */
	readonly 3017: CfgItemData;
	/** 天罚残页 */
	readonly 3018: CfgItemData;
	/** 面包 */
	readonly 4000: CfgItemData;
	/** 汉堡 */
	readonly 4001: CfgItemData;
	/** 炒面 */
	readonly 4002: CfgItemData;
	/** 煎饼 */
	readonly 4003: CfgItemData;
	/** 烧鸡 */
	readonly 4004: CfgItemData;
	/** 牛排 */
	readonly 4005: CfgItemData;
	/** 蛋炒饭 */
	readonly 4006: CfgItemData;
	/** 咖喱饭 */
	readonly 4007: CfgItemData;
	/** 青椒肉丝 */
	readonly 4008: CfgItemData;
	/** 鱼香肉丝 */
	readonly 4009: CfgItemData;
	/** 技能·基本剑术 */
	readonly 5000: CfgItemData;
	/** 技能·元素之力 */
	readonly 5001: CfgItemData;
	/** 技能·即死魔法 */
	readonly 5002: CfgItemData;
	/** 技能·不败佛指 */
	readonly 5003: CfgItemData;
	/** 技能·催心魔咒 */
	readonly 5004: CfgItemData;
	/** 技能·飞雪龙闪 */
	readonly 5005: CfgItemData;
	/** 技能·圣火圣隐 */
	readonly 5006: CfgItemData;
	/** 技能·醉仙神剑 */
	readonly 5007: CfgItemData;
	/** 技能·断浪龙印 */
	readonly 5008: CfgItemData;
	/** 技能·金光乍现 */
	readonly 5009: CfgItemData;
	/** 技能·春木之歌 */
	readonly 5010: CfgItemData;
	/** 技能·鬼雾水刃 */
	readonly 5011: CfgItemData;
	/** 技能·火蛇之舞 */
	readonly 5012: CfgItemData;
	/** 技能·土流大河 */
	readonly 5013: CfgItemData;
	/** 技能·上苍之怒 */
	readonly 5014: CfgItemData;
	/** 技能·摩诃无量 */
	readonly 5015: CfgItemData;
	/** 技能·化功大法 */
	readonly 5016: CfgItemData;
	/** 技能·北冥神功 */
	readonly 5017: CfgItemData;
	/** 技能·炎龙无双 */
	readonly 5018: CfgItemData;
	/** 技能·斗转星移 */
	readonly 5019: CfgItemData;
	/** 技能·棒打狗头 */
	readonly 5020: CfgItemData;
	/** 技能·乾坤一掷 */
	readonly 5021: CfgItemData;
	/** 技能·驾轻就熟 */
	readonly 5022: CfgItemData;
	/** 技能·复活青炎 */
	readonly 5023: CfgItemData;
	/** 技能·越战越勇 */
	readonly 5024: CfgItemData;
	/** 技能·天罚 */
	readonly 5025: CfgItemData;
	/** 技能·不死之身 */
	readonly 5026: CfgItemData;
	/** 心法·天机卷 */
	readonly 6000: CfgItemData;
	/** 心法·玄心卷 */
	readonly 6001: CfgItemData;
	/** 心法·秋水卷 */
	readonly 6002: CfgItemData;
	/** 心法·逍遥卷 */
	readonly 6003: CfgItemData;
	/** 心法·离殇卷 */
	readonly 6004: CfgItemData;
	/** 心法·大雅卷 */
	readonly 6005: CfgItemData;
	/** 心法·七星卷 */
	readonly 6006: CfgItemData;
	/** 心法·阴阳卷 */
	readonly 6007: CfgItemData;
	/** 心法·战神图录 */
	readonly 6008: CfgItemData;
	/** 一级攻击宝石 */
	readonly 7000: CfgItemData;
	/** 二级攻击宝石 */
	readonly 7001: CfgItemData;
	/** 三级攻击宝石 */
	readonly 7002: CfgItemData;
	/** 四级攻击宝石 */
	readonly 7003: CfgItemData;
	/** 五级攻击宝石 */
	readonly 7004: CfgItemData;
	/** 六级攻击宝石 */
	readonly 7005: CfgItemData;
	/** 七级攻击宝石 */
	readonly 7006: CfgItemData;
	/** 八级攻击宝石 */
	readonly 7007: CfgItemData;
	/** 九级攻击宝石 */
	readonly 7008: CfgItemData;
	/** 十级攻击宝石 */
	readonly 7009: CfgItemData;
	/** 一级防御宝石 */
	readonly 7010: CfgItemData;
	/** 二级防御宝石 */
	readonly 7011: CfgItemData;
	/** 三级防御宝石 */
	readonly 7012: CfgItemData;
	/** 四级防御宝石 */
	readonly 7013: CfgItemData;
	/** 五级防御宝石 */
	readonly 7014: CfgItemData;
	/** 六级防御宝石 */
	readonly 7015: CfgItemData;
	/** 七级防御宝石 */
	readonly 7016: CfgItemData;
	/** 八级防御宝石 */
	readonly 7017: CfgItemData;
	/** 九级防御宝石 */
	readonly 7018: CfgItemData;
	/** 十级防御宝石 */
	readonly 7019: CfgItemData;
	/** 一级生命宝石 */
	readonly 7020: CfgItemData;
	/** 二级生命宝石 */
	readonly 7021: CfgItemData;
	/** 三级生命宝石 */
	readonly 7022: CfgItemData;
	/** 四级生命宝石 */
	readonly 7023: CfgItemData;
	/** 五级生命宝石 */
	readonly 7024: CfgItemData;
	/** 六级生命宝石 */
	readonly 7025: CfgItemData;
	/** 七级生命宝石 */
	readonly 7026: CfgItemData;
	/** 八级生命宝石 */
	readonly 7027: CfgItemData;
	/** 九级生命宝石 */
	readonly 7028: CfgItemData;
	/** 十级生命宝石 */
	readonly 7029: CfgItemData;
	/** 一级力量宝石 */
	readonly 7030: CfgItemData;
	/** 二级力量宝石 */
	readonly 7031: CfgItemData;
	/** 三级力量宝石 */
	readonly 7032: CfgItemData;
	/** 四级力量宝石 */
	readonly 7033: CfgItemData;
	/** 五级力量宝石 */
	readonly 7034: CfgItemData;
	/** 六级力量宝石 */
	readonly 7035: CfgItemData;
	/** 七级力量宝石 */
	readonly 7036: CfgItemData;
	/** 八级力量宝石 */
	readonly 7037: CfgItemData;
	/** 九级力量宝石 */
	readonly 7038: CfgItemData;
	/** 十级力量宝石 */
	readonly 7039: CfgItemData;
	/** 一级体力宝石 */
	readonly 7040: CfgItemData;
	/** 二级体力宝石 */
	readonly 7041: CfgItemData;
	/** 三级体力宝石 */
	readonly 7042: CfgItemData;
	/** 四级体力宝石 */
	readonly 7043: CfgItemData;
	/** 五级体力宝石 */
	readonly 7044: CfgItemData;
	/** 六级体力宝石 */
	readonly 7045: CfgItemData;
	/** 七级体力宝石 */
	readonly 7046: CfgItemData;
	/** 八级体力宝石 */
	readonly 7047: CfgItemData;
	/** 九级体力宝石 */
	readonly 7048: CfgItemData;
	/** 十级体力宝石 */
	readonly 7049: CfgItemData;
	/** 一级金攻宝石 */
	readonly 7050: CfgItemData;
	/** 二级金攻宝石 */
	readonly 7051: CfgItemData;
	/** 三级金攻宝石 */
	readonly 7052: CfgItemData;
	/** 四级金攻宝石 */
	readonly 7053: CfgItemData;
	/** 五级金攻宝石 */
	readonly 7054: CfgItemData;
	/** 六级金攻宝石 */
	readonly 7055: CfgItemData;
	/** 七级金攻宝石 */
	readonly 7056: CfgItemData;
	/** 八级金攻宝石 */
	readonly 7057: CfgItemData;
	/** 九级金攻宝石 */
	readonly 7058: CfgItemData;
	/** 十级金攻宝石 */
	readonly 7059: CfgItemData;
	/** 一级木攻宝石 */
	readonly 7060: CfgItemData;
	/** 二级木攻宝石 */
	readonly 7061: CfgItemData;
	/** 三级木攻宝石 */
	readonly 7062: CfgItemData;
	/** 四级木攻宝石 */
	readonly 7063: CfgItemData;
	/** 五级木攻宝石 */
	readonly 7064: CfgItemData;
	/** 六级木攻宝石 */
	readonly 7065: CfgItemData;
	/** 七级木攻宝石 */
	readonly 7066: CfgItemData;
	/** 八级木攻宝石 */
	readonly 7067: CfgItemData;
	/** 九级木攻宝石 */
	readonly 7068: CfgItemData;
	/** 十级木攻宝石 */
	readonly 7069: CfgItemData;
	/** 一级水攻宝石 */
	readonly 7070: CfgItemData;
	/** 二级水攻宝石 */
	readonly 7071: CfgItemData;
	/** 三级水攻宝石 */
	readonly 7072: CfgItemData;
	/** 四级水攻宝石 */
	readonly 7073: CfgItemData;
	/** 五级水攻宝石 */
	readonly 7074: CfgItemData;
	/** 六级水攻宝石 */
	readonly 7075: CfgItemData;
	/** 七级水攻宝石 */
	readonly 7076: CfgItemData;
	/** 八级水攻宝石 */
	readonly 7077: CfgItemData;
	/** 九级水攻宝石 */
	readonly 7078: CfgItemData;
	/** 十级水攻宝石 */
	readonly 7079: CfgItemData;
	/** 一级火攻宝石 */
	readonly 7080: CfgItemData;
	/** 二级火攻宝石 */
	readonly 7081: CfgItemData;
	/** 三级火攻宝石 */
	readonly 7082: CfgItemData;
	/** 四级火攻宝石 */
	readonly 7083: CfgItemData;
	/** 五级火攻宝石 */
	readonly 7084: CfgItemData;
	/** 六级火攻宝石 */
	readonly 7085: CfgItemData;
	/** 七级火攻宝石 */
	readonly 7086: CfgItemData;
	/** 八级火攻宝石 */
	readonly 7087: CfgItemData;
	/** 九级火攻宝石 */
	readonly 7088: CfgItemData;
	/** 十级火攻宝石 */
	readonly 7089: CfgItemData;
	/** 一级土攻宝石 */
	readonly 7090: CfgItemData;
	/** 二级土攻宝石 */
	readonly 7091: CfgItemData;
	/** 三级土攻宝石 */
	readonly 7092: CfgItemData;
	/** 四级土攻宝石 */
	readonly 7093: CfgItemData;
	/** 五级土攻宝石 */
	readonly 7094: CfgItemData;
	/** 六级土攻宝石 */
	readonly 7095: CfgItemData;
	/** 七级土攻宝石 */
	readonly 7096: CfgItemData;
	/** 八级土攻宝石 */
	readonly 7097: CfgItemData;
	/** 九级土攻宝石 */
	readonly 7098: CfgItemData;
	/** 十级土攻宝石 */
	readonly 7099: CfgItemData;
	/** 一级命中宝石 */
	readonly 7100: CfgItemData;
	/** 二级命中宝石 */
	readonly 7101: CfgItemData;
	/** 三级命中宝石 */
	readonly 7102: CfgItemData;
	/** 四级命中宝石 */
	readonly 7103: CfgItemData;
	/** 五级命中宝石 */
	readonly 7104: CfgItemData;
	/** 六级命中宝石 */
	readonly 7105: CfgItemData;
	/** 七级命中宝石 */
	readonly 7106: CfgItemData;
	/** 八级命中宝石 */
	readonly 7107: CfgItemData;
	/** 九级命中宝石 */
	readonly 7108: CfgItemData;
	/** 十级命中宝石 */
	readonly 7109: CfgItemData;
	/** 一级闪避宝石 */
	readonly 7110: CfgItemData;
	/** 二级闪避宝石 */
	readonly 7111: CfgItemData;
	/** 三级闪避宝石 */
	readonly 7112: CfgItemData;
	/** 四级闪避宝石 */
	readonly 7113: CfgItemData;
	/** 五级闪避宝石 */
	readonly 7114: CfgItemData;
	/** 六级闪避宝石 */
	readonly 7115: CfgItemData;
	/** 七级闪避宝石 */
	readonly 7116: CfgItemData;
	/** 八级闪避宝石 */
	readonly 7117: CfgItemData;
	/** 九级闪避宝石 */
	readonly 7118: CfgItemData;
	/** 十级闪避宝石 */
	readonly 7119: CfgItemData;
	/** 一级暴击宝石 */
	readonly 7120: CfgItemData;
	/** 二级暴击宝石 */
	readonly 7121: CfgItemData;
	/** 三级暴击宝石 */
	readonly 7122: CfgItemData;
	/** 四级暴击宝石 */
	readonly 7123: CfgItemData;
	/** 五级暴击宝石 */
	readonly 7124: CfgItemData;
	/** 六级暴击宝石 */
	readonly 7125: CfgItemData;
	/** 七级暴击宝石 */
	readonly 7126: CfgItemData;
	/** 八级暴击宝石 */
	readonly 7127: CfgItemData;
	/** 九级暴击宝石 */
	readonly 7128: CfgItemData;
	/** 十级暴击宝石 */
	readonly 7129: CfgItemData;
	/** 一级身法宝石 */
	readonly 7130: CfgItemData;
	/** 二级身法宝石 */
	readonly 7131: CfgItemData;
	/** 三级身法宝石 */
	readonly 7132: CfgItemData;
	/** 四级身法宝石 */
	readonly 7133: CfgItemData;
	/** 五级身法宝石 */
	readonly 7134: CfgItemData;
	/** 六级身法宝石 */
	readonly 7135: CfgItemData;
	/** 七级身法宝石 */
	readonly 7136: CfgItemData;
	/** 八级身法宝石 */
	readonly 7137: CfgItemData;
	/** 九级身法宝石 */
	readonly 7138: CfgItemData;
	/** 十级身法宝石 */
	readonly 7139: CfgItemData;
	/** 一级耐力宝石 */
	readonly 7140: CfgItemData;
	/** 二级耐力宝石 */
	readonly 7141: CfgItemData;
	/** 三级耐力宝石 */
	readonly 7142: CfgItemData;
	/** 四级耐力宝石 */
	readonly 7143: CfgItemData;
	/** 五级耐力宝石 */
	readonly 7144: CfgItemData;
	/** 六级耐力宝石 */
	readonly 7145: CfgItemData;
	/** 七级耐力宝石 */
	readonly 7146: CfgItemData;
	/** 八级耐力宝石 */
	readonly 7147: CfgItemData;
	/** 九级耐力宝石 */
	readonly 7148: CfgItemData;
	/** 十级耐力宝石 */
	readonly 7149: CfgItemData;
	/** 一级金防宝石 */
	readonly 7150: CfgItemData;
	/** 二级金防宝石 */
	readonly 7151: CfgItemData;
	/** 三级金防宝石 */
	readonly 7152: CfgItemData;
	/** 四级金防宝石 */
	readonly 7153: CfgItemData;
	/** 五级金防宝石 */
	readonly 7154: CfgItemData;
	/** 六级金防宝石 */
	readonly 7155: CfgItemData;
	/** 七级金防宝石 */
	readonly 7156: CfgItemData;
	/** 八级金防宝石 */
	readonly 7157: CfgItemData;
	/** 九级金防宝石 */
	readonly 7158: CfgItemData;
	/** 十级金防宝石 */
	readonly 7159: CfgItemData;
	/** 一级木防宝石 */
	readonly 7160: CfgItemData;
	/** 二级木防宝石 */
	readonly 7161: CfgItemData;
	/** 三级木防宝石 */
	readonly 7162: CfgItemData;
	/** 四级木防宝石 */
	readonly 7163: CfgItemData;
	/** 五级木防宝石 */
	readonly 7164: CfgItemData;
	/** 六级木防宝石 */
	readonly 7165: CfgItemData;
	/** 七级木防宝石 */
	readonly 7166: CfgItemData;
	/** 八级木防宝石 */
	readonly 7167: CfgItemData;
	/** 九级木防宝石 */
	readonly 7168: CfgItemData;
	/** 十级木防宝石 */
	readonly 7169: CfgItemData;
	/** 一级水防宝石 */
	readonly 7170: CfgItemData;
	/** 二级水防宝石 */
	readonly 7171: CfgItemData;
	/** 三级水防宝石 */
	readonly 7172: CfgItemData;
	/** 四级水防宝石 */
	readonly 7173: CfgItemData;
	/** 五级水防宝石 */
	readonly 7174: CfgItemData;
	/** 六级水防宝石 */
	readonly 7175: CfgItemData;
	/** 七级水防宝石 */
	readonly 7176: CfgItemData;
	/** 八级水防宝石 */
	readonly 7177: CfgItemData;
	/** 九级水防宝石 */
	readonly 7178: CfgItemData;
	/** 十级水防宝石 */
	readonly 7179: CfgItemData;
	/** 一级火防宝石 */
	readonly 7180: CfgItemData;
	/** 二级火防宝石 */
	readonly 7181: CfgItemData;
	/** 三级火防宝石 */
	readonly 7182: CfgItemData;
	/** 四级火防宝石 */
	readonly 7183: CfgItemData;
	/** 五级火防宝石 */
	readonly 7184: CfgItemData;
	/** 六级火防宝石 */
	readonly 7185: CfgItemData;
	/** 七级火防宝石 */
	readonly 7186: CfgItemData;
	/** 八级火防宝石 */
	readonly 7187: CfgItemData;
	/** 九级火防宝石 */
	readonly 7188: CfgItemData;
	/** 十级火防宝石 */
	readonly 7189: CfgItemData;
	/** 一级土防宝石 */
	readonly 7190: CfgItemData;
	/** 二级土防宝石 */
	readonly 7191: CfgItemData;
	/** 三级土防宝石 */
	readonly 7192: CfgItemData;
	/** 四级土防宝石 */
	readonly 7193: CfgItemData;
	/** 五级土防宝石 */
	readonly 7194: CfgItemData;
	/** 六级土防宝石 */
	readonly 7195: CfgItemData;
	/** 七级土防宝石 */
	readonly 7196: CfgItemData;
	/** 八级土防宝石 */
	readonly 7197: CfgItemData;
	/** 九级土防宝石 */
	readonly 7198: CfgItemData;
	/** 十级土防宝石 */
	readonly 7199: CfgItemData;
	/** 新手武器 */
	readonly 40000: CfgItemData;
	/** 新手头盔 */
	readonly 40001: CfgItemData;
	/** 新手项链 */
	readonly 40002: CfgItemData;
	/** 新手衣服 */
	readonly 40003: CfgItemData;
	/** 新手戒指 */
	readonly 40004: CfgItemData;
	/** 新手裤子 */
	readonly 40005: CfgItemData;
	/** 新手护符 */
	readonly 40006: CfgItemData;
	/** 新手鞋子 */
	readonly 40007: CfgItemData;
	/** 苍竹长剑 */
	readonly 40008: CfgItemData;
	/** 苍竹项链 */
	readonly 40009: CfgItemData;
	/** 苍竹戒指 */
	readonly 40010: CfgItemData;
	/** 苍竹护符 */
	readonly 40011: CfgItemData;
	/** 苍竹帽 */
	readonly 40012: CfgItemData;
	/** 苍竹衣 */
	readonly 40013: CfgItemData;
	/** 苍竹裤 */
	readonly 40014: CfgItemData;
	/** 苍竹鞋 */
	readonly 40015: CfgItemData;
	/** 平凡长剑 */
	readonly 40016: CfgItemData;
	/** 平凡项链 */
	readonly 40017: CfgItemData;
	/** 平凡戒指 */
	readonly 40018: CfgItemData;
	/** 平凡护符 */
	readonly 40019: CfgItemData;
	/** 平凡帽 */
	readonly 40020: CfgItemData;
	/** 平凡衣 */
	readonly 40021: CfgItemData;
	/** 平凡裤 */
	readonly 40022: CfgItemData;
	/** 平凡鞋 */
	readonly 40023: CfgItemData;
	/** 清风长剑 */
	readonly 40024: CfgItemData;
	/** 清风项链 */
	readonly 40025: CfgItemData;
	/** 清风戒指 */
	readonly 40026: CfgItemData;
	/** 清风护符 */
	readonly 40027: CfgItemData;
	/** 清风帽 */
	readonly 40028: CfgItemData;
	/** 清风衣 */
	readonly 40029: CfgItemData;
	/** 清风裤 */
	readonly 40030: CfgItemData;
	/** 清风鞋 */
	readonly 40031: CfgItemData;
	/** 星海长剑 */
	readonly 40032: CfgItemData;
	/** 星海项链 */
	readonly 40033: CfgItemData;
	/** 星海戒指 */
	readonly 40034: CfgItemData;
	/** 星海护符 */
	readonly 40035: CfgItemData;
	/** 星海帽 */
	readonly 40036: CfgItemData;
	/** 星海衣 */
	readonly 40037: CfgItemData;
	/** 星海裤 */
	readonly 40038: CfgItemData;
	/** 星海鞋 */
	readonly 40039: CfgItemData;
	/** 寂灭长剑 */
	readonly 40040: CfgItemData;
	/** 寂灭项链 */
	readonly 40041: CfgItemData;
	/** 寂灭戒指 */
	readonly 40042: CfgItemData;
	/** 寂灭护符 */
	readonly 40043: CfgItemData;
	/** 寂灭帽 */
	readonly 40044: CfgItemData;
	/** 寂灭衣 */
	readonly 40045: CfgItemData;
	/** 寂灭裤 */
	readonly 40046: CfgItemData;
	/** 寂灭鞋 */
	readonly 40047: CfgItemData;
	/** 烈焰长剑 */
	readonly 40048: CfgItemData;
	/** 烈焰项链 */
	readonly 40049: CfgItemData;
	/** 烈焰戒指 */
	readonly 40050: CfgItemData;
	/** 烈焰护符 */
	readonly 40051: CfgItemData;
	/** 烈焰帽 */
	readonly 40052: CfgItemData;
	/** 烈焰衣 */
	readonly 40053: CfgItemData;
	/** 烈焰裤 */
	readonly 40054: CfgItemData;
	/** 烈焰鞋 */
	readonly 40055: CfgItemData;
	/** 紫月长剑 */
	readonly 40056: CfgItemData;
	/** 紫月项链 */
	readonly 40057: CfgItemData;
	/** 紫月戒指 */
	readonly 40058: CfgItemData;
	/** 紫月护符 */
	readonly 40059: CfgItemData;
	/** 紫月帽 */
	readonly 40060: CfgItemData;
	/** 紫月衣 */
	readonly 40061: CfgItemData;
	/** 紫月裤 */
	readonly 40062: CfgItemData;
	/** 紫月鞋 */
	readonly 40063: CfgItemData;
	/** 踏雪长剑 */
	readonly 40064: CfgItemData;
	/** 踏雪项链 */
	readonly 40065: CfgItemData;
	/** 踏雪戒指 */
	readonly 40066: CfgItemData;
	/** 踏雪护符 */
	readonly 40067: CfgItemData;
	/** 踏雪帽 */
	readonly 40068: CfgItemData;
	/** 踏雪衣 */
	readonly 40069: CfgItemData;
	/** 踏雪裤 */
	readonly 40070: CfgItemData;
	/** 踏雪鞋 */
	readonly 40071: CfgItemData;
	/** 秋水长剑 */
	readonly 40072: CfgItemData;
	/** 秋水项链 */
	readonly 40073: CfgItemData;
	/** 秋水戒指 */
	readonly 40074: CfgItemData;
	/** 秋水护符 */
	readonly 40075: CfgItemData;
	/** 秋水帽 */
	readonly 40076: CfgItemData;
	/** 秋水衣 */
	readonly 40077: CfgItemData;
	/** 秋水裤 */
	readonly 40078: CfgItemData;
	/** 秋水鞋 */
	readonly 40079: CfgItemData;
	/** 破凡长剑 */
	readonly 40080: CfgItemData;
	/** 破凡项链 */
	readonly 40081: CfgItemData;
	/** 破凡戒指 */
	readonly 40082: CfgItemData;
	/** 破凡护符 */
	readonly 40083: CfgItemData;
	/** 破凡帽 */
	readonly 40084: CfgItemData;
	/** 破凡衣 */
	readonly 40085: CfgItemData;
	/** 破凡裤 */
	readonly 40086: CfgItemData;
	/** 破凡鞋 */
	readonly 40087: CfgItemData;
	/** 神木长剑 */
	readonly 40088: CfgItemData;
	/** 神木项链 */
	readonly 40089: CfgItemData;
	/** 神木戒指 */
	readonly 40090: CfgItemData;
	/** 神木护符 */
	readonly 40091: CfgItemData;
	/** 神木帽 */
	readonly 40092: CfgItemData;
	/** 神木衣 */
	readonly 40093: CfgItemData;
	/** 神木裤 */
	readonly 40094: CfgItemData;
	/** 神木鞋 */
	readonly 40095: CfgItemData;
	/** 九州神龙 */
	readonly 49996: CfgItemData;
	/** 骷髅战甲 */
	readonly 49997: CfgItemData;
	/** 观音泪 */
	readonly 49998: CfgItemData;
	/** 仙器 */
	readonly 49999: CfgItemData;
}

declare interface CfgItemData {
	readonly [key: string]: any;
	/** id */
	readonly id: number;
	/** 名字 */
	readonly name: string;
	/** 品质 */
	readonly quality: number;
	/** 数据类型 */
	readonly dataType: number;
	/** 背包类型 */
	readonly bagType: number;
	/** 物品类型 */
	readonly itemType: number;
	/** 描述 */
	readonly desc: string;
	/** 是否可出售 */
	readonly salable: number;
	/** 售卖获得物品 */
	readonly sellRewards: CfgItemData1[];
	/** 可使用境界 */
	readonly useRequire: CfgItemData2;
}

declare interface CfgItemData1 {
	readonly [key: string]: any;
	readonly id: number;
	readonly count: number;
}

declare interface CfgItemData2 {
	readonly [key: string]: any;
	readonly jingJie: number;
	readonly cengJi: number;
}

