/** This script is generated automatically, Please do not any modify! */declare interface CfgJingJie {
	readonly [key: string]: CfgJingJieData;
	/** 炼体 */
	readonly 1: CfgJingJieData;
	/** 练气 */
	readonly 2: CfgJingJieData;
	/** 筑基 */
	readonly 3: CfgJingJieData;
	/** 金丹 */
	readonly 4: CfgJingJieData;
	/** 元婴 */
	readonly 5: CfgJingJieData;
	/** 出窍 */
	readonly 6: CfgJingJieData;
	/** 化神 */
	readonly 7: CfgJingJieData;
	/** 合体 */
	readonly 8: CfgJingJieData;
	/** 炼虚 */
	readonly 9: CfgJingJieData;
	/** 渡劫 */
	readonly 10: CfgJingJieData;
	/** 大乘 */
	readonly 11: CfgJingJieData;
	/** 人仙 */
	readonly 12: CfgJingJieData;
	/** 地仙 */
	readonly 13: CfgJingJieData;
	/** 天仙 */
	readonly 14: CfgJingJieData;
	/** 真仙 */
	readonly 15: CfgJingJieData;
	/** 金仙 */
	readonly 16: CfgJingJieData;
	/** 玄仙 */
	readonly 17: CfgJingJieData;
	/** 太乙散仙 */
	readonly 18: CfgJingJieData;
	/** 太乙金仙 */
	readonly 19: CfgJingJieData;
	/** 太乙玄仙 */
	readonly 20: CfgJingJieData;
	/** 大罗金仙 */
	readonly 21: CfgJingJieData;
	/** 大罗至仙 */
	readonly 22: CfgJingJieData;
	/** 大罗始仙 */
	readonly 23: CfgJingJieData;
	/** 仙王 */
	readonly 24: CfgJingJieData;
	/** 仙君 */
	readonly 25: CfgJingJieData;
	/** 仙帝 */
	readonly 26: CfgJingJieData;
	/** 仙尊 */
	readonly 27: CfgJingJieData;
	/** 伪神 */
	readonly 28: CfgJingJieData;
	/** 神人 */
	readonly 29: CfgJingJieData;
	/** 神明 */
	readonly 30: CfgJingJieData;
	/** 大神 */
	readonly 31: CfgJingJieData;
	/** 真神 */
	readonly 32: CfgJingJieData;
	/** 天神 */
	readonly 33: CfgJingJieData;
	/** 神君 */
	readonly 34: CfgJingJieData;
	/** 神王 */
	readonly 35: CfgJingJieData;
	/** 神帝 */
	readonly 36: CfgJingJieData;
	/** 神尊 */
	readonly 37: CfgJingJieData;
	/** 准圣 */
	readonly 38: CfgJingJieData;
	/** 亚圣 */
	readonly 39: CfgJingJieData;
	/** 入圣 */
	readonly 40: CfgJingJieData;
	/** 显圣 */
	readonly 41: CfgJingJieData;
	/** 圣人 */
	readonly 42: CfgJingJieData;
	/** 圣王 */
	readonly 43: CfgJingJieData;
	/** 圣尊 */
	readonly 44: CfgJingJieData;
	/** 天道圣人 */
	readonly 45: CfgJingJieData;
	/** 天道至圣 */
	readonly 46: CfgJingJieData;
	/** 混元圣人 */
	readonly 47: CfgJingJieData;
	/** 混元至圣 */
	readonly 48: CfgJingJieData;
	/** 混沌圣人 */
	readonly 49: CfgJingJieData;
	/** 混沌至圣 */
	readonly 50: CfgJingJieData;
	/** 大道至尊 */
	readonly 51: CfgJingJieData;
	/** 大道帝尊 */
	readonly 52: CfgJingJieData;
	/** 无极混元超圣 */
	readonly 53: CfgJingJieData;
	/** 无极至高大帝 */
	readonly 54: CfgJingJieData;
	/** 无极大主宰 */
	readonly 55: CfgJingJieData;
	/** 鸿蒙融道 */
	readonly 56: CfgJingJieData;
	/** 鸿蒙大自在 */
	readonly 57: CfgJingJieData;
	/** 鸿蒙太元始祖 */
	readonly 58: CfgJingJieData;
	/** 造化太虚尊 */
	readonly 59: CfgJingJieData;
	/** 大衍神祗 */
	readonly 60: CfgJingJieData;
	/** 至上始源主 */
	readonly 61: CfgJingJieData;
	/** 不朽法先天 */
	readonly 62: CfgJingJieData;
	/** 不朽神念大帝 */
	readonly 63: CfgJingJieData;
	/** 永恒神命 */
	readonly 64: CfgJingJieData;
	/** 超脱神源 */
	readonly 65: CfgJingJieData;
	/** 无上神源 */
	readonly 66: CfgJingJieData;
	/** 万生创造 */
	readonly 67: CfgJingJieData;
}

declare interface CfgJingJieData {
	readonly [key: string]: any;
	/**  */
	readonly id: number;
	/** 名称 */
	readonly name: string;
}

