/**The script is automatically generated by BatMain.bat , please do not modify */

type CfgData<T> = { [P in keyof T]: T[P] }[keyof T];
interface CfgExtension<T> {
	forEach(callbackfn: (value: T, index: number, array: T[]) => void, thisArg?: any): void;
	filter(predicate: (value: T, index: number, array: T[]) => boolean, thisArg?: any): T[];
	find(predicate: (value: T, index: number, array: T[]) => boolean, thisArg?: any): T;
	every(predicate: (value: T, index: number, array: T[]) => boolean, thisArg?: any): boolean;
	findIndex(predicate: (value: T, index: number, obj: T[]) => boolean, thisArg?: any): number;
	includes(searchElement: T, fromIndex?: number): boolean;
	indexOf(searchElement: T, fromIndex?: number): number;
	lastIndexOf(searchElement: T, fromIndex?: number): number;
	map<U>(callbackfn: (value: T, index: number, array: T[]) => U, thisArg?: any): U[];
	reduce<U>(callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: T[]) => U, initialValue: U): U;
	slice(start?: number, end?: number): T[];
	some(predicate: (value: T, index: number, array: T[]) => boolean, thisArg?: any): boolean;
}

declare interface ICfgManager {
	/** 关卡 */
	readonly Level: CfgLevel & CfgExtension<CfgData<CfgLevel>>;
	/** 副本 */
	readonly Copy: CfgCopy & CfgExtension<CfgData<CfgCopy>>;
	/** 秘境 */
	readonly Secret: CfgSecret & CfgExtension<CfgData<CfgSecret>>;
	/** Boss */
	readonly Boss: CfgBoss & CfgExtension<CfgData<CfgBoss>>;
	/** 采集 */
	readonly Gather: CfgGather & CfgExtension<CfgData<CfgGather>>;
	/** 怪物 */
	readonly Enemy: CfgEnemy & CfgExtension<CfgData<CfgEnemy>>;
	/** 装备 */
	readonly Equipment: CfgEquipment & CfgExtension<CfgData<CfgEquipment>>;
	/** 装备加成 */
	readonly EquipmentAddition: CfgEquipmentAddition & CfgExtension<CfgData<CfgEquipmentAddition>>;
	/** 宝石 */
	readonly Gem: CfgGem & CfgExtension<CfgData<CfgGem>>;
	/** 道具 */
	readonly Props: CfgProps & CfgExtension<CfgData<CfgProps>>;
	/** 材料 */
	readonly Material: CfgMaterial & CfgExtension<CfgData<CfgMaterial>>;
	/** 食物 */
	readonly Food: CfgFood & CfgExtension<CfgData<CfgFood>>;
	/** 技能书 */
	readonly SkillBook: CfgSkillBook & CfgExtension<CfgData<CfgSkillBook>>;
	/** 心法书 */
	readonly XinFaBook: CfgXinFaBook & CfgExtension<CfgData<CfgXinFaBook>>;
	/** 固定文本 */
	readonly Lang: CfgLang & CfgExtension<CfgData<CfgLang>>;
	/** 物品 */
	readonly Item: CfgItem & CfgExtension<CfgData<CfgItem>>;
	/** 境界 */
	readonly JingJie: CfgJingJie & CfgExtension<CfgData<CfgJingJie>>;
	/** 常量 */
	readonly Const: CfgConst & CfgExtension<CfgData<CfgConst>>;
	/** 称号 */
	readonly Title: CfgTitle & CfgExtension<CfgData<CfgTitle>>;
	/** 门派 */
	readonly Sect: CfgSect & CfgExtension<CfgData<CfgSect>>;
	/** 商店 */
	readonly Shop: CfgShop & CfgExtension<CfgData<CfgShop>>;
	/** 颜色 */
	readonly Color: CfgColor & CfgExtension<CfgData<CfgColor>>;
	/** 错误码 */
	readonly Error: CfgError & CfgExtension<CfgData<CfgError>>;

}