/**This is automatically generated by BatMain.bat , please do not modify */
export const enum ResPath{
	// res/font/
	Font_HYDianHeiW = "res/font/HYDianHeiW.ttf",
	Font_HYDiShengYingXiongTiW = "res/font/HYDiShengYingXiongTiW.ttf",
	Font_HYTangMeiRen95W = "res/font/HYTangMeiRen95W.ttf",
	Font_HYZhengYuan65W = "res/font/HYZhengYuan65W.ttf",

	// res/table/
	Table_Config = "res/table/Config.json",

	// res/ui/
	Ui_PkgBattle = "res/ui/PkgBattle",
	Ui_PkgCommon = "res/ui/PkgCommon",
	Ui_PkgLogin = "res/ui/PkgLogin",
	Ui_PkgMain = "res/ui/PkgMain",
}