/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigJingJieData {
	readonly ID: number;
	/**名称 */
	readonly Name: string;
}

declare interface ConfigJingJie extends ReadOnlyObject<ConfigJingJieData> {
	/**炼体 */
	readonly 1: ConfigJingJieData;
	/**练气 */
	readonly 2: ConfigJingJieData;
	/**筑基 */
	readonly 3: ConfigJingJieData;
	/**金丹 */
	readonly 4: ConfigJingJieData;
	/**元婴 */
	readonly 5: ConfigJingJieData;
	/**出窍 */
	readonly 6: ConfigJingJieData;
	/**化神 */
	readonly 7: ConfigJingJieData;
	/**合体 */
	readonly 8: ConfigJingJieData;
	/**炼虚 */
	readonly 9: ConfigJingJieData;
	/**渡劫 */
	readonly 10: ConfigJingJieData;
	/**大乘 */
	readonly 11: ConfigJingJieData;
	/**人仙 */
	readonly 12: ConfigJingJieData;
	/**地仙 */
	readonly 13: ConfigJingJieData;
	/**天仙 */
	readonly 14: ConfigJingJieData;
	/**真仙 */
	readonly 15: ConfigJingJieData;
	/**金仙 */
	readonly 16: ConfigJingJieData;
	/**玄仙 */
	readonly 17: ConfigJingJieData;
	/**太乙散仙 */
	readonly 18: ConfigJingJieData;
	/**太乙金仙 */
	readonly 19: ConfigJingJieData;
	/**太乙玄仙 */
	readonly 20: ConfigJingJieData;
	/**大罗金仙 */
	readonly 21: ConfigJingJieData;
	/**大罗至仙 */
	readonly 22: ConfigJingJieData;
	/**大罗始仙 */
	readonly 23: ConfigJingJieData;
	/**仙王 */
	readonly 24: ConfigJingJieData;
	/**仙君 */
	readonly 25: ConfigJingJieData;
	/**仙帝 */
	readonly 26: ConfigJingJieData;
	/**仙尊 */
	readonly 27: ConfigJingJieData;
	/**伪神 */
	readonly 28: ConfigJingJieData;
	/**神人 */
	readonly 29: ConfigJingJieData;
	/**神明 */
	readonly 30: ConfigJingJieData;
	/**大神 */
	readonly 31: ConfigJingJieData;
	/**真神 */
	readonly 32: ConfigJingJieData;
	/**天神 */
	readonly 33: ConfigJingJieData;
	/**神君 */
	readonly 34: ConfigJingJieData;
	/**神王 */
	readonly 35: ConfigJingJieData;
	/**神帝 */
	readonly 36: ConfigJingJieData;
	/**神尊 */
	readonly 37: ConfigJingJieData;
	/**准圣 */
	readonly 38: ConfigJingJieData;
	/**亚圣 */
	readonly 39: ConfigJingJieData;
	/**入圣 */
	readonly 40: ConfigJingJieData;
	/**显圣 */
	readonly 41: ConfigJingJieData;
	/**圣人 */
	readonly 42: ConfigJingJieData;
	/**圣王 */
	readonly 43: ConfigJingJieData;
	/**圣尊 */
	readonly 44: ConfigJingJieData;
	/**天道圣人 */
	readonly 45: ConfigJingJieData;
	/**天道至圣 */
	readonly 46: ConfigJingJieData;
	/**混元圣人 */
	readonly 47: ConfigJingJieData;
	/**混元至圣 */
	readonly 48: ConfigJingJieData;
	/**混沌圣人 */
	readonly 49: ConfigJingJieData;
	/**混沌至圣 */
	readonly 50: ConfigJingJieData;
	/**大道至尊 */
	readonly 51: ConfigJingJieData;
	/**大道帝尊 */
	readonly 52: ConfigJingJieData;
	/**无极混元超圣 */
	readonly 53: ConfigJingJieData;
	/**无极至高大帝 */
	readonly 54: ConfigJingJieData;
	/**无极大主宰 */
	readonly 55: ConfigJingJieData;
	/**鸿蒙融道 */
	readonly 56: ConfigJingJieData;
	/**鸿蒙大自在 */
	readonly 57: ConfigJingJieData;
	/**鸿蒙太元始祖 */
	readonly 58: ConfigJingJieData;
	/**造化太虚尊 */
	readonly 59: ConfigJingJieData;
	/**大衍神祗 */
	readonly 60: ConfigJingJieData;
	/**至上始源主 */
	readonly 61: ConfigJingJieData;
	/**不朽法先天 */
	readonly 62: ConfigJingJieData;
	/**不朽神念大帝 */
	readonly 63: ConfigJingJieData;
	/**永恒神命 */
	readonly 64: ConfigJingJieData;
	/**超脱神源 */
	readonly 65: ConfigJingJieData;
	/**无上神源 */
	readonly 66: ConfigJingJieData;
	/**万生创造 */
	readonly 67: ConfigJingJieData;
}