/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigSectData {
	readonly ID: number;
	/**名字 */
	readonly Name: string;
	/**属性 */
	readonly Attribute: number[];
	/**攻击成长 */
	readonly AtkFactor: number;
	/**防御成长 */
	readonly DefFactor: number;
	/**生命成长 */
	readonly HpFactor: number;
	/**命中成长 */
	readonly HitFactor: number;
	/**闪避成长 */
	readonly DodFactor: number;
	/**暴击成长 */
	readonly CriFactor: number;
	/**暴抗成长 */
	readonly CrFactor: number;
}

declare interface ConfigSect extends ReadOnlyObject<ConfigSectData> {
	/**少林 */
	readonly 101: ConfigSectData;
	/**星宿 */
	readonly 102: ConfigSectData;
	/**天山 */
	readonly 103: ConfigSectData;
	/**明教 */
	readonly 104: ConfigSectData;
	/**慕容 */
	readonly 105: ConfigSectData;
	/**丐帮 */
	readonly 106: ConfigSectData;
}