/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigConstData {
	readonly ID: number;
	/**值 */
	readonly Value: string;
	/**描述 */
	readonly Description: string;
}

declare interface ConfigConst extends ReadOnlyObject<ConfigConstData> {
	/** */
	readonly 1001: ConfigConstData;
	/**tip消失时间 */
	readonly 1002: ConfigConstData;
	/**tip每行显示时间 */
	readonly 1003: ConfigConstData;
	/**tip移动速度 */
	readonly 1004: ConfigConstData;
	/**每一境界所能到达的最大层数 */
	readonly 1005: ConfigConstData;
	/**倍速 */
	readonly 1006: ConfigConstData;
	/**分解装备 */
	readonly 1007: ConfigConstData;
	/**分解宝石 */
	readonly 1008: ConfigConstData;
	/**最大宝石等级 */
	readonly 1009: ConfigConstData;
	/**武器最大星级 */
	readonly 1010: ConfigConstData;
}