/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigMaterialData {
	/**id */
	readonly ID: number;
}

declare interface ConfigMaterial extends ReadOnlyObject<ConfigMaterialData> {
	readonly 3000: ConfigMaterialData;
	readonly 3001: ConfigMaterialData;
	readonly 3002: ConfigMaterialData;
	readonly 3003: ConfigMaterialData;
	readonly 3004: ConfigMaterialData;
	readonly 3005: ConfigMaterialData;
	readonly 3006: ConfigMaterialData;
	readonly 3007: ConfigMaterialData;
	readonly 3008: ConfigMaterialData;
	readonly 3009: ConfigMaterialData;
	readonly 3010: ConfigMaterialData;
	readonly 3011: ConfigMaterialData;
	readonly 3012: ConfigMaterialData;
	readonly 3013: ConfigMaterialData;
	readonly 3014: ConfigMaterialData;
	readonly 3015: ConfigMaterialData;
	readonly 3016: ConfigMaterialData;
	readonly 3017: ConfigMaterialData;
	readonly 3018: ConfigMaterialData;
}