/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigEnemyData {
	readonly ID: number;
	/**名字 */
	readonly Name: string;
	/**怪物等级 */
	readonly EnemyLevel: number;
	/**怪物攻击名字 */
	readonly AttackName: string;
	/**攻击力 */
	readonly ATK: number;
	/**防御 */
	readonly Defense: number;
	/**生命值 */
	readonly HP: number;
	/**金攻 */
	readonly JinATK: number;
	/**木攻 */
	readonly MuATK: number;
	/**水攻 */
	readonly ShuiATK: number;
	/**火攻 */
	readonly HuoATK: number;
	/**土攻 */
	readonly TuATK: number;
	/**金防 */
	readonly JinDef: number;
	/**木防 */
	readonly MuDef: number;
	/**水防 */
	readonly ShuiDef: number;
	/**火防 */
	readonly HuoDef: number;
	/**土防 */
	readonly TuDef: number;
	/**角色命中率 */
	readonly HitRate: number;
	/**角色暴击率 */
	readonly CriRate: number;
	/**角色闪避率 */
	readonly DodRate: number;
}

declare interface ConfigEnemy extends ReadOnlyObject<ConfigEnemyData> {
	/**野牛 */
	readonly 10001: ConfigEnemyData;
	/**血月魔狼 */
	readonly 10002: ConfigEnemyData;
	/**游牧民 */
	readonly 10003: ConfigEnemyData;
	/**野猪 */
	readonly 10004: ConfigEnemyData;
	/**镰鼬龙王 */
	readonly 10005: ConfigEnemyData;
	/**青铜傀儡 */
	readonly 10006: ConfigEnemyData;
	/**刀角虎 */
	readonly 10007: ConfigEnemyData;
	/**翼蛇龙 */
	readonly 10008: ConfigEnemyData;
	/**合体金人兵 */
	readonly 10009: ConfigEnemyData;
	/**骷髅勇士 */
	readonly 10010: ConfigEnemyData;
	/**戟兵 */
	readonly 10011: ConfigEnemyData;
	/**山魈 */
	readonly 10012: ConfigEnemyData;
	/**精神元素 */
	readonly 10013: ConfigEnemyData;
	/**狂暴魔熊 */
	readonly 10014: ConfigEnemyData;
	/**龙蝇 */
	readonly 10015: ConfigEnemyData;
	/**土砂龙 */
	readonly 10016: ConfigEnemyData;
	/**洞穴人 */
	readonly 10017: ConfigEnemyData;
	/**贼龙 */
	readonly 10018: ConfigEnemyData;
	/**眠狗龙王 */
	readonly 10019: ConfigEnemyData;
	/**雷鸟 */
	readonly 10020: ConfigEnemyData;
	/**讯龙 */
	readonly 10021: ConfigEnemyData;
	/**毒妖鸟 */
	readonly 10022: ConfigEnemyData;
	/**火光兽 */
	readonly 10023: ConfigEnemyData;
	/**火精灵 */
	readonly 10024: ConfigEnemyData;
	/**邪神王 */
	readonly 10025: ConfigEnemyData;
	/**雪鹿 */
	readonly 10026: ConfigEnemyData;
	/**食人花 */
	readonly 10027: ConfigEnemyData;
	/**铁背苍熊 */
	readonly 10028: ConfigEnemyData;
	/**机关陀螺 */
	readonly 10029: ConfigEnemyData;
	/**飞甲虫 */
	readonly 10030: ConfigEnemyData;
	/**巨人 */
	readonly 10031: ConfigEnemyData;
	/**独眼魔 */
	readonly 10032: ConfigEnemyData;
	/**吸血鬼 */
	readonly 10033: ConfigEnemyData;
	/**铠骨魔 */
	readonly 10034: ConfigEnemyData;
	/**风刃豹 */
	readonly 10035: ConfigEnemyData;
	/**秦军什长 */
	readonly 10036: ConfigEnemyData;
	/**食人魔王 */
	readonly 10037: ConfigEnemyData;
	/**三头魔兽 */
	readonly 10038: ConfigEnemyData;
	/**蛇妖 */
	readonly 10039: ConfigEnemyData;
	/**独角兽 */
	readonly 10040: ConfigEnemyData;
	/**半人马 */
	readonly 10041: ConfigEnemyData;
	/**无头机关鸟 */
	readonly 10042: ConfigEnemyData;
	/**机关妖兵 */
	readonly 10043: ConfigEnemyData;
	/**无头鬼 */
	readonly 10044: ConfigEnemyData;
	/**大雕 */
	readonly 10045: ConfigEnemyData;
	/**毒狗龙王 */
	readonly 10046: ConfigEnemyData;
	/**风魔妖虎 */
	readonly 10047: ConfigEnemyData;
	/**影月魔狼 */
	readonly 10048: ConfigEnemyData;
	/**青苍龙 */
	readonly 10049: ConfigEnemyData;
	/**蝶仙 */
	readonly 10050: ConfigEnemyData;
	/**赤豹 */
	readonly 10051: ConfigEnemyData;
	/**开明兽 */
	readonly 10052: ConfigEnemyData;
	/**恐怖骑士 */
	readonly 10053: ConfigEnemyData;
	/**赤甲兽 */
	readonly 10054: ConfigEnemyData;
	/**泥翁龙 */
	readonly 10055: ConfigEnemyData;
	/**骚鸟 */
	readonly 10056: ConfigEnemyData;
	/**幻影骷髅 */
	readonly 10057: ConfigEnemyData;
	/**幻影秦兵 */
	readonly 10058: ConfigEnemyData;
	/**石像怪 */
	readonly 10059: ConfigEnemyData;
	/**牛头怪 */
	readonly 10060: ConfigEnemyData;
	/**碧睛狂狮 */
	readonly 10061: ConfigEnemyData;
	/**疾风螳螂 */
	readonly 10062: ConfigEnemyData;
	/**熔火巨蛙 */
	readonly 10063: ConfigEnemyData;
	/**机关阴火魔 */
	readonly 10064: ConfigEnemyData;
	/**食人魔 */
	readonly 10065: ConfigEnemyData;
	/**艾露猫 */
	readonly 10066: ConfigEnemyData;
	/**怨魂 */
	readonly 10067: ConfigEnemyData;
	/**巨蜥 */
	readonly 10068: ConfigEnemyData;
	/**锈钢傀儡 */
	readonly 10069: ConfigEnemyData;
	/**幽冥豹 */
	readonly 10070: ConfigEnemyData;
	/**麒麟 */
	readonly 10071: ConfigEnemyData;
	/**霞龙 */
	readonly 10072: ConfigEnemyData;
	/**泥鱼龙 */
	readonly 10073: ConfigEnemyData;
	/**强盗 */
	readonly 10074: ConfigEnemyData;
	/**九尾 */
	readonly 10075: ConfigEnemyData;
	/**骑兵 */
	readonly 10076: ConfigEnemyData;
	/**盗贼 */
	readonly 10077: ConfigEnemyData;
	/**青龙 */
	readonly 10078: ConfigEnemyData;
	/**奇美拉 */
	readonly 10079: ConfigEnemyData;
	/**幻影秦始皇 */
	readonly 10080: ConfigEnemyData;
	/**粘怪 */
	readonly 10081: ConfigEnemyData;
	/**骸龙 */
	readonly 10082: ConfigEnemyData;
	/**狮鹫 */
	readonly 10083: ConfigEnemyData;
	/**毒蝇 */
	readonly 10084: ConfigEnemyData;
	/**恶狼骑士 */
	readonly 10085: ConfigEnemyData;
	/**恶狼斗士 */
	readonly 10086: ConfigEnemyData;
	/**踏云魔豹 */
	readonly 10087: ConfigEnemyData;
	/**疾风魔狼 */
	readonly 10088: ConfigEnemyData;
	/**长颈鬼 */
	readonly 10089: ConfigEnemyData;
	/**幻影护卫长 */
	readonly 10090: ConfigEnemyData;
	/**飞龙 */
	readonly 10091: ConfigEnemyData;
	/**大地冰熊 */
	readonly 10092: ConfigEnemyData;
	/**黑冥血炼豹 */
	readonly 10093: ConfigEnemyData;
	/**机关魔火妖 */
	readonly 10094: ConfigEnemyData;
	/**皇家狮鹫 */
	readonly 10095: ConfigEnemyData;
	/**角龙 */
	readonly 10096: ConfigEnemyData;
	/**刑天 */
	readonly 10097: ConfigEnemyData;
	/**火鸟 */
	readonly 10098: ConfigEnemyData;
	/**吸血巨人 */
	readonly 10099: ConfigEnemyData;
	/**青甲蝎 */
	readonly 10100: ConfigEnemyData;
	/**猿猴 */
	readonly 10101: ConfigEnemyData;
	/**幽冥暗狼 */
	readonly 10102: ConfigEnemyData;
	/**蛇女 */
	readonly 10103: ConfigEnemyData;
	/**剑魔亡灵 */
	readonly 10104: ConfigEnemyData;
	/**银环血鳞熊 */
	readonly 10105: ConfigEnemyData;
	/**鹰身女巫 */
	readonly 10106: ConfigEnemyData;
	/**水生兽 */
	readonly 10107: ConfigEnemyData;
	/**伞鸟 */
	readonly 10108: ConfigEnemyData;
	/**剑齿虎 */
	readonly 10109: ConfigEnemyData;
	/**天使 */
	readonly 10110: ConfigEnemyData;
	/**法师 */
	readonly 10111: ConfigEnemyData;
	/**丸鸟 */
	readonly 10112: ConfigEnemyData;
	/**碧眼火狮 */
	readonly 10113: ConfigEnemyData;
	/**飞头蛮 */
	readonly 10114: ConfigEnemyData;
	/**秦兵护卫长 */
	readonly 10115: ConfigEnemyData;
	/**巨石妖 */
	readonly 10116: ConfigEnemyData;
	/**美杜莎女王 */
	readonly 10117: ConfigEnemyData;
	/**神射手 */
	readonly 10118: ConfigEnemyData;
	/**电角狼 */
	readonly 10119: ConfigEnemyData;
	/**八银地熊 */
	readonly 10120: ConfigEnemyData;
	/**恶鬼 */
	readonly 10121: ConfigEnemyData;
	/**双翼银狮 */
	readonly 10122: ConfigEnemyData;
	/**云生兽 */
	readonly 10123: ConfigEnemyData;
	/**冰雪白狮 */
	readonly 10124: ConfigEnemyData;
	/**苍龙 */
	readonly 10125: ConfigEnemyData;
	/**魔幻法师 */
	readonly 10126: ConfigEnemyData;
	/**鬼王 */
	readonly 10127: ConfigEnemyData;
	/**烈火精灵 */
	readonly 10128: ConfigEnemyData;
	/**金焱圣狮 */
	readonly 10129: ConfigEnemyData;
	/**噬毒巨猿 */
	readonly 10130: ConfigEnemyData;
	/**幽冥白虎 */
	readonly 10131: ConfigEnemyData;
	/**圣光虎 */
	readonly 10132: ConfigEnemyData;
	/**轰龙 */
	readonly 10133: ConfigEnemyData;
	/**赤炎虎 */
	readonly 10134: ConfigEnemyData;
	/**巨铁兵 */
	readonly 10135: ConfigEnemyData;
	/**骑士 */
	readonly 10136: ConfigEnemyData;
	/**赤金熊 */
	readonly 10137: ConfigEnemyData;
	/**冰霜石像 */
	readonly 10138: ConfigEnemyData;
	/**砂鱼 */
	readonly 10139: ConfigEnemyData;
	/**青蛇 */
	readonly 10140: ConfigEnemyData;
	/**炎晶龙 */
	readonly 10141: ConfigEnemyData;
	/**圣龙 */
	readonly 10142: ConfigEnemyData;
	/**比蒙巨兽 */
	readonly 10143: ConfigEnemyData;
	/**熔岩兽 */
	readonly 10144: ConfigEnemyData;
	/**天狗兽 */
	readonly 10145: ConfigEnemyData;
	/**怨虎龙 */
	readonly 10146: ConfigEnemyData;
	/**夜刃豹 */
	readonly 10147: ConfigEnemyData;
	/**火域狂狼 */
	readonly 10148: ConfigEnemyData;
	/**绿龙 */
	readonly 10149: ConfigEnemyData;
	/**金人 */
	readonly 10150: ConfigEnemyData;
	/**烈焰焱虎 */
	readonly 10151: ConfigEnemyData;
	/**半兽人首领 */
	readonly 10152: ConfigEnemyData;
	/**大地之熊 */
	readonly 10153: ConfigEnemyData;
	/**骷髅兵 */
	readonly 10154: ConfigEnemyData;
	/**河童蛙 */
	readonly 10155: ConfigEnemyData;
	/**嗜血狂狮 */
	readonly 10156: ConfigEnemyData;
	/**邪神 */
	readonly 10157: ConfigEnemyData;
	/**奇怪龙 */
	readonly 10158: ConfigEnemyData;
	/**烈火元素 */
	readonly 10159: ConfigEnemyData;
	/**蝎狮 */
	readonly 10160: ConfigEnemyData;
	/**人鱼龙 */
	readonly 10161: ConfigEnemyData;
	/**变形幼冰鲨 */
	readonly 10162: ConfigEnemyData;
	/**钻石人 */
	readonly 10163: ConfigEnemyData;
	/**雷帝鸟 */
	readonly 10164: ConfigEnemyData;
	/**妃蜘蛛 */
	readonly 10165: ConfigEnemyData;
	/**飞雷龙 */
	readonly 10166: ConfigEnemyData;
	/**荒漠猛犸 */
	readonly 10167: ConfigEnemyData;
	/**风神龙 */
	readonly 10168: ConfigEnemyData;
	/**波波 */
	readonly 10169: ConfigEnemyData;
	/**咬鱼 */
	readonly 10170: ConfigEnemyData;
	/**毒狗龙 */
	readonly 10171: ConfigEnemyData;
	/**水兽 */
	readonly 10172: ConfigEnemyData;
	/**羽龙 */
	readonly 10173: ConfigEnemyData;
	/**化蛇 */
	readonly 10174: ConfigEnemyData;
	/**机关鱼将军 */
	readonly 10175: ConfigEnemyData;
	/**雷霆石像 */
	readonly 10176: ConfigEnemyData;
	/**雷狼龙 */
	readonly 10177: ConfigEnemyData;
	/**雌狗龙 */
	readonly 10178: ConfigEnemyData;
	/**小精灵 */
	readonly 10179: ConfigEnemyData;
	/**大蝙蝠 */
	readonly 10180: ConfigEnemyData;
	/**啸月天狼 */
	readonly 10181: ConfigEnemyData;
	/**梅拉露 */
	readonly 10182: ConfigEnemyData;
	/**机关小拐子 */
	readonly 10183: ConfigEnemyData;
	/**赤血雷豹 */
	readonly 10184: ConfigEnemyData;
	/**机关龟 */
	readonly 10185: ConfigEnemyData;
	/**蜥蜴勇士 */
	readonly 10186: ConfigEnemyData;
	/**花仙子 */
	readonly 10187: ConfigEnemyData;
	/**蜥蜴人 */
	readonly 10188: ConfigEnemyData;
	/**黑暗翼虎 */
	readonly 10189: ConfigEnemyData;
	/**毒眼 */
	readonly 10190: ConfigEnemyData;
	/**铁人 */
	readonly 10191: ConfigEnemyData;
	/**赤刃螳螂 */
	readonly 10192: ConfigEnemyData;
	/**美杜莎 */
	readonly 10193: ConfigEnemyData;
	/**泡狐龙 */
	readonly 10194: ConfigEnemyData;
	/**毒蝎狮 */
	readonly 10195: ConfigEnemyData;
	/**沙漠土狼 */
	readonly 10196: ConfigEnemyData;
	/**九头怪 */
	readonly 10197: ConfigEnemyData;
	/**狼人 */
	readonly 10198: ConfigEnemyData;
	/**人虎 */
	readonly 10199: ConfigEnemyData;
	/**长角恶鬼 */
	readonly 10200: ConfigEnemyData;
	/**蝙蝠 */
	readonly 10201: ConfigEnemyData;
	/**暗月白虎 */
	readonly 10202: ConfigEnemyData;
	/**弓箭兵 */
	readonly 10203: ConfigEnemyData;
	/**独目鬼 */
	readonly 10204: ConfigEnemyData;
	/**金刚巨猿 */
	readonly 10205: ConfigEnemyData;
	/**金狮子 */
	readonly 10206: ConfigEnemyData;
	/**雷晶龙 */
	readonly 10207: ConfigEnemyData;
	/**荒漠盗匪 */
	readonly 10208: ConfigEnemyData;
	/**雷神龙 */
	readonly 10209: ConfigEnemyData;
	/**雪鬼兽 */
	readonly 10210: ConfigEnemyData;
	/**大天使 */
	readonly 10211: ConfigEnemyData;
	/**枪兵 */
	readonly 10212: ConfigEnemyData;
	/**行尸 */
	readonly 10213: ConfigEnemyData;
	/**冰牙龙 */
	readonly 10214: ConfigEnemyData;
	/**狂暴火狮 */
	readonly 10215: ConfigEnemyData;
	/**双头猎豹 */
	readonly 10216: ConfigEnemyData;
	/**飞龙王 */
	readonly 10217: ConfigEnemyData;
	/**青熊兽 */
	readonly 10218: ConfigEnemyData;
	/**泰坦巨人 */
	readonly 10219: ConfigEnemyData;
	/**恶魔 */
	readonly 10220: ConfigEnemyData;
	/**牛头王 */
	readonly 10221: ConfigEnemyData;
	/**垂皮龙 */
	readonly 10222: ConfigEnemyData;
	/**终极九头怪 */
	readonly 10223: ConfigEnemyData;
	/**投石矮人 */
	readonly 10224: ConfigEnemyData;
	/**大精灵 */
	readonly 10225: ConfigEnemyData;
	/**狗龙 */
	readonly 10226: ConfigEnemyData;
	/**木甲兽 */
	readonly 10227: ConfigEnemyData;
	/**冰雪暴熊 */
	readonly 10228: ConfigEnemyData;
	/**大狼人 */
	readonly 10229: ConfigEnemyData;
	/**牛头妖王 */
	readonly 10230: ConfigEnemyData;
	/**幻影射手 */
	readonly 10231: ConfigEnemyData;
	/**秦军士兵 */
	readonly 10232: ConfigEnemyData;
	/**炽焰奇美拉 */
	readonly 10233: ConfigEnemyData;
	/**独眼巨人 */
	readonly 10234: ConfigEnemyData;
	/**暗影豹 */
	readonly 10235: ConfigEnemyData;
	/**蜥蜴 */
	readonly 10236: ConfigEnemyData;
	/**黑曜龙 */
	readonly 10237: ConfigEnemyData;
	/**潜土巨蛙 */
	readonly 10238: ConfigEnemyData;
	/**镰鼬龙 */
	readonly 10239: ConfigEnemyData;
	/**机关神兵 */
	readonly 10240: ConfigEnemyData;
	/**炎帝鸟 */
	readonly 10241: ConfigEnemyData;
	/**石狮精 */
	readonly 10242: ConfigEnemyData;
	/**吸血鬼王 */
	readonly 10243: ConfigEnemyData;
	/**地狱洞穴人 */
	readonly 10244: ConfigEnemyData;
	/**魔剑客 */
	readonly 10245: ConfigEnemyData;
	/**暗黑骑士 */
	readonly 10246: ConfigEnemyData;
	/**冻尾蝎 */
	readonly 10247: ConfigEnemyData;
	/**蛮角兽 */
	readonly 10248: ConfigEnemyData;
	/**机关黑火魔 */
	readonly 10249: ConfigEnemyData;
	/**牛头妖 */
	readonly 10250: ConfigEnemyData;
	/**灰铠骨魔 */
	readonly 10251: ConfigEnemyData;
	/**火山云豹 */
	readonly 10252: ConfigEnemyData;
	/**碎颅人马 */
	readonly 10253: ConfigEnemyData;
	/**蛮牛 */
	readonly 10254: ConfigEnemyData;
	/**独角神兽 */
	readonly 10255: ConfigEnemyData;
	/**剑士 */
	readonly 10256: ConfigEnemyData;
	/**冰原猛犸 */
	readonly 10257: ConfigEnemyData;
	/**吸血蝙蝠 */
	readonly 10258: ConfigEnemyData;
	/**骨龙 */
	readonly 10259: ConfigEnemyData;
	/**雪斑黑豹 */
	readonly 10260: ConfigEnemyData;
	/**僵尸 */
	readonly 10261: ConfigEnemyData;
	/**雷火狼尸 */
	readonly 10262: ConfigEnemyData;
	/**三首猎犬 */
	readonly 10263: ConfigEnemyData;
	/**铠角兽 */
	readonly 10264: ConfigEnemyData;
	/**僧侣 */
	readonly 10265: ConfigEnemyData;
	/**树精 */
	readonly 10266: ConfigEnemyData;
	/**黑龙 */
	readonly 10267: ConfigEnemyData;
	/**小怪物 */
	readonly 10268: ConfigEnemyData;
	/**幽灵 */
	readonly 10269: ConfigEnemyData;
	/**白兔兽 */
	readonly 10270: ConfigEnemyData;
	/**毒龙 */
	readonly 10271: ConfigEnemyData;
	/**狐熊 */
	readonly 10272: ConfigEnemyData;
	/**石像鬼 */
	readonly 10273: ConfigEnemyData;
	/**大耳怪王 */
	readonly 10274: ConfigEnemyData;
	/**阴魂 */
	readonly 10275: ConfigEnemyData;
	/**甲虫 */
	readonly 10276: ConfigEnemyData;
	/**大妖精 */
	readonly 10277: ConfigEnemyData;
	/**独眼王 */
	readonly 10278: ConfigEnemyData;
	/**火龙 */
	readonly 10279: ConfigEnemyData;
	/**木精灵 */
	readonly 10280: ConfigEnemyData;
	/**尸巫 */
	readonly 10281: ConfigEnemyData;
	/**水晶龙 */
	readonly 10282: ConfigEnemyData;
	/**蛮鄂龙 */
	readonly 10283: ConfigEnemyData;
	/**木乃伊 */
	readonly 10284: ConfigEnemyData;
	/**半兽人 */
	readonly 10285: ConfigEnemyData;
	/**紫火魔狮 */
	readonly 10286: ConfigEnemyData;
	/**神怪主 */
	readonly 10287: ConfigEnemyData;
	/**冰霜巨狼 */
	readonly 10288: ConfigEnemyData;
	/**尸巫王 */
	readonly 10289: ConfigEnemyData;
	/**金龙 */
	readonly 10290: ConfigEnemyData;
	/**银神兵 */
	readonly 10291: ConfigEnemyData;
	/**小妖精 */
	readonly 10292: ConfigEnemyData;
	/**岩龙 */
	readonly 10293: ConfigEnemyData;
	/**贼寇 */
	readonly 10294: ConfigEnemyData;
	/**鬼龙 */
	readonly 10295: ConfigEnemyData;
	/**大法师 */
	readonly 10296: ConfigEnemyData;
	/**铁甲爆炎虎 */
	readonly 10297: ConfigEnemyData;
	/**龙王 */
	readonly 10298: ConfigEnemyData;
	/**凤凰 */
	readonly 10299: ConfigEnemyData;
	/**晶曜龙 */
	readonly 10300: ConfigEnemyData;
	/**半人马首领 */
	readonly 10301: ConfigEnemyData;
	/**冰角狼 */
	readonly 10302: ConfigEnemyData;
	/**大骷髅 */
	readonly 10303: ConfigEnemyData;
	/**冰焰魔狮 */
	readonly 10304: ConfigEnemyData;
	/**血翎天狼 */
	readonly 10305: ConfigEnemyData;
	/**精灵 */
	readonly 10306: ConfigEnemyData;
	/**地狱猎犬 */
	readonly 10307: ConfigEnemyData;
	/**祭司 */
	readonly 10308: ConfigEnemyData;
	/**冠突龙 */
	readonly 10309: ConfigEnemyData;
	/**精灵鹿 */
	readonly 10310: ConfigEnemyData;
	/**紫晶翼狮 */
	readonly 10311: ConfigEnemyData;
	/**蛇羽龙 */
	readonly 10312: ConfigEnemyData;
	/**狸兽 */
	readonly 10313: ConfigEnemyData;
	/**眠狗龙 */
	readonly 10314: ConfigEnemyData;
	/**有头机关鸟 */
	readonly 10315: ConfigEnemyData;
	/**崩山人马 */
	readonly 10316: ConfigEnemyData;
	/**秦军伍长 */
	readonly 10317: ConfigEnemyData;
	/**暴风虎 */
	readonly 10318: ConfigEnemyData;
	/**硬甲龙 */
	readonly 10319: ConfigEnemyData;
	/**枯木战士 */
	readonly 10320: ConfigEnemyData;
	/**魔法元素 */
	readonly 10321: ConfigEnemyData;
	/**石人 */
	readonly 10322: ConfigEnemyData;
	/**枯木卫士 */
	readonly 10323: ConfigEnemyData;
	/**金人兵 */
	readonly 10324: ConfigEnemyData;
	/**鹰身女妖 */
	readonly 10325: ConfigEnemyData;
	/**机关狮将军 */
	readonly 10326: ConfigEnemyData;
	/**雌火龙 */
	readonly 10327: ConfigEnemyData;
	/**紫龙 */
	readonly 10328: ConfigEnemyData;
	/**赤龙 */
	readonly 10329: ConfigEnemyData;
	/**大耳怪 */
	readonly 10330: ConfigEnemyData;
	/**战斗矮人 */
	readonly 10331: ConfigEnemyData;
	/**银飞马 */
	readonly 10332: ConfigEnemyData;
	/**大地双头狮虎兽 */
	readonly 10333: ConfigEnemyData;
	/**大恶魔 */
	readonly 10334: ConfigEnemyData;
	/**霜骸龙 */
	readonly 10335: ConfigEnemyData;
	/**木甲刀兵 */
	readonly 10336: ConfigEnemyData;
	/**暗黑魔狼 */
	readonly 10337: ConfigEnemyData;
	/**炎魔熊 */
	readonly 10338: ConfigEnemyData;
	/**十字军 */
	readonly 10339: ConfigEnemyData;
}