/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigCaiJiData {
	readonly ID: number;
	/**名字 */
	readonly Name: string;
}

declare interface ConfigCaiJi extends ReadOnlyObject<ConfigCaiJiData> {
	/**云罗山脉 */
	readonly 10001: ConfigCaiJiData;
	/**玄灵峡谷 */
	readonly 10002: ConfigCaiJiData;
	/**月牙湖 */
	readonly 10003: ConfigCaiJiData;
}