/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigEquipmentData {
	/**id */
	readonly ID: number;
	/**名字 */
	readonly Name: string;
	/**装备部位 */
	readonly Part: number;
}

declare interface ConfigEquipment extends ReadOnlyObject<ConfigEquipmentData> {
	/**新手武器 */
	readonly 40000: ConfigEquipmentData;
	/**新手头盔 */
	readonly 40001: ConfigEquipmentData;
	/**新手项链 */
	readonly 40002: ConfigEquipmentData;
	/**新手衣服 */
	readonly 40003: ConfigEquipmentData;
	/**新手戒指 */
	readonly 40004: ConfigEquipmentData;
	/**新手裤子 */
	readonly 40005: ConfigEquipmentData;
	/**新手护符 */
	readonly 40006: ConfigEquipmentData;
	/**新手鞋子 */
	readonly 40007: ConfigEquipmentData;
	/**苍竹长剑 */
	readonly 40008: ConfigEquipmentData;
	/**苍竹项链 */
	readonly 40009: ConfigEquipmentData;
	/**苍竹戒指 */
	readonly 40010: ConfigEquipmentData;
	/**苍竹护符 */
	readonly 40011: ConfigEquipmentData;
	/**苍竹帽 */
	readonly 40012: ConfigEquipmentData;
	/**苍竹衣 */
	readonly 40013: ConfigEquipmentData;
	/**苍竹裤 */
	readonly 40014: ConfigEquipmentData;
	/**苍竹鞋 */
	readonly 40015: ConfigEquipmentData;
	/**平凡长剑 */
	readonly 40016: ConfigEquipmentData;
	/**平凡项链 */
	readonly 40017: ConfigEquipmentData;
	/**平凡戒指 */
	readonly 40018: ConfigEquipmentData;
	/**平凡护符 */
	readonly 40019: ConfigEquipmentData;
	/**平凡帽 */
	readonly 40020: ConfigEquipmentData;
	/**平凡衣 */
	readonly 40021: ConfigEquipmentData;
	/**平凡裤 */
	readonly 40022: ConfigEquipmentData;
	/**平凡鞋 */
	readonly 40023: ConfigEquipmentData;
	/**清风长剑 */
	readonly 40024: ConfigEquipmentData;
	/**清风项链 */
	readonly 40025: ConfigEquipmentData;
	/**清风戒指 */
	readonly 40026: ConfigEquipmentData;
	/**清风护符 */
	readonly 40027: ConfigEquipmentData;
	/**清风帽 */
	readonly 40028: ConfigEquipmentData;
	/**清风衣 */
	readonly 40029: ConfigEquipmentData;
	/**清风裤 */
	readonly 40030: ConfigEquipmentData;
	/**清风鞋 */
	readonly 40031: ConfigEquipmentData;
	/**星海长剑 */
	readonly 40032: ConfigEquipmentData;
	/**星海项链 */
	readonly 40033: ConfigEquipmentData;
	/**星海戒指 */
	readonly 40034: ConfigEquipmentData;
	/**星海护符 */
	readonly 40035: ConfigEquipmentData;
	/**星海帽 */
	readonly 40036: ConfigEquipmentData;
	/**星海衣 */
	readonly 40037: ConfigEquipmentData;
	/**星海裤 */
	readonly 40038: ConfigEquipmentData;
	/**星海鞋 */
	readonly 40039: ConfigEquipmentData;
	/**寂灭长剑 */
	readonly 40040: ConfigEquipmentData;
	/**寂灭项链 */
	readonly 40041: ConfigEquipmentData;
	/**寂灭戒指 */
	readonly 40042: ConfigEquipmentData;
	/**寂灭护符 */
	readonly 40043: ConfigEquipmentData;
	/**寂灭帽 */
	readonly 40044: ConfigEquipmentData;
	/**寂灭衣 */
	readonly 40045: ConfigEquipmentData;
	/**寂灭裤 */
	readonly 40046: ConfigEquipmentData;
	/**寂灭鞋 */
	readonly 40047: ConfigEquipmentData;
	/**烈焰长剑 */
	readonly 40048: ConfigEquipmentData;
	/**烈焰项链 */
	readonly 40049: ConfigEquipmentData;
	/**烈焰戒指 */
	readonly 40050: ConfigEquipmentData;
	/**烈焰护符 */
	readonly 40051: ConfigEquipmentData;
	/**烈焰帽 */
	readonly 40052: ConfigEquipmentData;
	/**烈焰衣 */
	readonly 40053: ConfigEquipmentData;
	/**烈焰裤 */
	readonly 40054: ConfigEquipmentData;
	/**烈焰鞋 */
	readonly 40055: ConfigEquipmentData;
	/**紫月长剑 */
	readonly 40056: ConfigEquipmentData;
	/**紫月项链 */
	readonly 40057: ConfigEquipmentData;
	/**紫月戒指 */
	readonly 40058: ConfigEquipmentData;
	/**紫月护符 */
	readonly 40059: ConfigEquipmentData;
	/**紫月帽 */
	readonly 40060: ConfigEquipmentData;
	/**紫月衣 */
	readonly 40061: ConfigEquipmentData;
	/**紫月裤 */
	readonly 40062: ConfigEquipmentData;
	/**紫月鞋 */
	readonly 40063: ConfigEquipmentData;
	/**踏雪长剑 */
	readonly 40064: ConfigEquipmentData;
	/**踏雪项链 */
	readonly 40065: ConfigEquipmentData;
	/**踏雪戒指 */
	readonly 40066: ConfigEquipmentData;
	/**踏雪护符 */
	readonly 40067: ConfigEquipmentData;
	/**踏雪帽 */
	readonly 40068: ConfigEquipmentData;
	/**踏雪衣 */
	readonly 40069: ConfigEquipmentData;
	/**踏雪裤 */
	readonly 40070: ConfigEquipmentData;
	/**踏雪鞋 */
	readonly 40071: ConfigEquipmentData;
	/**秋水长剑 */
	readonly 40072: ConfigEquipmentData;
	/**秋水项链 */
	readonly 40073: ConfigEquipmentData;
	/**秋水戒指 */
	readonly 40074: ConfigEquipmentData;
	/**秋水护符 */
	readonly 40075: ConfigEquipmentData;
	/**秋水帽 */
	readonly 40076: ConfigEquipmentData;
	/**秋水衣 */
	readonly 40077: ConfigEquipmentData;
	/**秋水裤 */
	readonly 40078: ConfigEquipmentData;
	/**秋水鞋 */
	readonly 40079: ConfigEquipmentData;
	/**破凡长剑 */
	readonly 40080: ConfigEquipmentData;
	/**破凡项链 */
	readonly 40081: ConfigEquipmentData;
	/**破凡戒指 */
	readonly 40082: ConfigEquipmentData;
	/**破凡护符 */
	readonly 40083: ConfigEquipmentData;
	/**破凡帽 */
	readonly 40084: ConfigEquipmentData;
	/**破凡衣 */
	readonly 40085: ConfigEquipmentData;
	/**破凡裤 */
	readonly 40086: ConfigEquipmentData;
	/**破凡鞋 */
	readonly 40087: ConfigEquipmentData;
	/**神木长剑 */
	readonly 40088: ConfigEquipmentData;
	/**神木项链 */
	readonly 40089: ConfigEquipmentData;
	/**神木戒指 */
	readonly 40090: ConfigEquipmentData;
	/**神木护符 */
	readonly 40091: ConfigEquipmentData;
	/**神木帽 */
	readonly 40092: ConfigEquipmentData;
	/**神木衣 */
	readonly 40093: ConfigEquipmentData;
	/**神木裤 */
	readonly 40094: ConfigEquipmentData;
	/**神木鞋 */
	readonly 40095: ConfigEquipmentData;
	/**九州神龙 */
	readonly 49996: ConfigEquipmentData;
	/**骷髅战甲 */
	readonly 49997: ConfigEquipmentData;
	/**观音泪 */
	readonly 49998: ConfigEquipmentData;
	/**仙器 */
	readonly 49999: ConfigEquipmentData;
}