/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigPropsData {
	/**id */
	readonly ID: number;
	readonly Rewards: BaseDropOutType[];
}

declare interface ConfigProps extends ReadOnlyObject<ConfigPropsData> {
	/**1百万金币 */
	readonly 2000: ConfigPropsData;
	/**1亿金币 */
	readonly 2001: ConfigPropsData;
	/**50元宝 */
	readonly 2002: ConfigPropsData;
	/**100元宝 */
	readonly 2003: ConfigPropsData;
	/**500元宝 */
	readonly 2004: ConfigPropsData;
	/**1000元宝 */
	readonly 2005: ConfigPropsData;
	/**10000元宝 */
	readonly 2006: ConfigPropsData;
	/**副本重置卡 */
	readonly 2007: ConfigPropsData;
	/**秘境重置卡 */
	readonly 2008: ConfigPropsData;
	/**BOSS重置卡 */
	readonly 2009: ConfigPropsData;
	/**门派邀请函 */
	readonly 2010: ConfigPropsData;
	/**首充礼包 */
	readonly 2011: ConfigPropsData;
}