/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigGemData {
	/**id */
	readonly ID: number;
	/**加成 */
	readonly Addition: AdditionType;
	/**等级 */
	readonly Level: number;
}

declare interface ConfigGem extends ReadOnlyObject<ConfigGemData> {
	/**一级攻击宝石 */
	readonly 7000: ConfigGemData;
	/**二级攻击宝石 */
	readonly 7001: ConfigGemData;
	/**三级攻击宝石 */
	readonly 7002: ConfigGemData;
	/**四级攻击宝石 */
	readonly 7003: ConfigGemData;
	/**五级攻击宝石 */
	readonly 7004: ConfigGemData;
	/**六级攻击宝石 */
	readonly 7005: ConfigGemData;
	/**七级攻击宝石 */
	readonly 7006: ConfigGemData;
	/**八级攻击宝石 */
	readonly 7007: ConfigGemData;
	/**九级攻击宝石 */
	readonly 7008: ConfigGemData;
	/**十级攻击宝石 */
	readonly 7009: ConfigGemData;
	/**一级防御宝石 */
	readonly 7010: ConfigGemData;
	/**二级防御宝石 */
	readonly 7011: ConfigGemData;
	/**三级防御宝石 */
	readonly 7012: ConfigGemData;
	/**四级防御宝石 */
	readonly 7013: ConfigGemData;
	/**五级防御宝石 */
	readonly 7014: ConfigGemData;
	/**六级防御宝石 */
	readonly 7015: ConfigGemData;
	/**七级防御宝石 */
	readonly 7016: ConfigGemData;
	/**八级防御宝石 */
	readonly 7017: ConfigGemData;
	/**九级防御宝石 */
	readonly 7018: ConfigGemData;
	/**十级防御宝石 */
	readonly 7019: ConfigGemData;
	/**一级生命宝石 */
	readonly 7020: ConfigGemData;
	/**二级生命宝石 */
	readonly 7021: ConfigGemData;
	/**三级生命宝石 */
	readonly 7022: ConfigGemData;
	/**四级生命宝石 */
	readonly 7023: ConfigGemData;
	/**五级生命宝石 */
	readonly 7024: ConfigGemData;
	/**六级生命宝石 */
	readonly 7025: ConfigGemData;
	/**七级生命宝石 */
	readonly 7026: ConfigGemData;
	/**八级生命宝石 */
	readonly 7027: ConfigGemData;
	/**九级生命宝石 */
	readonly 7028: ConfigGemData;
	/**十级生命宝石 */
	readonly 7029: ConfigGemData;
	/**一级力量宝石 */
	readonly 7030: ConfigGemData;
	/**二级力量宝石 */
	readonly 7031: ConfigGemData;
	/**三级力量宝石 */
	readonly 7032: ConfigGemData;
	/**四级力量宝石 */
	readonly 7033: ConfigGemData;
	/**五级力量宝石 */
	readonly 7034: ConfigGemData;
	/**六级力量宝石 */
	readonly 7035: ConfigGemData;
	/**七级力量宝石 */
	readonly 7036: ConfigGemData;
	/**八级力量宝石 */
	readonly 7037: ConfigGemData;
	/**九级力量宝石 */
	readonly 7038: ConfigGemData;
	/**十级力量宝石 */
	readonly 7039: ConfigGemData;
	/**一级体力宝石 */
	readonly 7040: ConfigGemData;
	/**二级体力宝石 */
	readonly 7041: ConfigGemData;
	/**三级体力宝石 */
	readonly 7042: ConfigGemData;
	/**四级体力宝石 */
	readonly 7043: ConfigGemData;
	/**五级体力宝石 */
	readonly 7044: ConfigGemData;
	/**六级体力宝石 */
	readonly 7045: ConfigGemData;
	/**七级体力宝石 */
	readonly 7046: ConfigGemData;
	/**八级体力宝石 */
	readonly 7047: ConfigGemData;
	/**九级体力宝石 */
	readonly 7048: ConfigGemData;
	/**十级体力宝石 */
	readonly 7049: ConfigGemData;
	/**一级金攻宝石 */
	readonly 7050: ConfigGemData;
	/**二级金攻宝石 */
	readonly 7051: ConfigGemData;
	/**三级金攻宝石 */
	readonly 7052: ConfigGemData;
	/**四级金攻宝石 */
	readonly 7053: ConfigGemData;
	/**五级金攻宝石 */
	readonly 7054: ConfigGemData;
	/**六级金攻宝石 */
	readonly 7055: ConfigGemData;
	/**七级金攻宝石 */
	readonly 7056: ConfigGemData;
	/**八级金攻宝石 */
	readonly 7057: ConfigGemData;
	/**九级金攻宝石 */
	readonly 7058: ConfigGemData;
	/**十级金攻宝石 */
	readonly 7059: ConfigGemData;
	/**一级木攻宝石 */
	readonly 7060: ConfigGemData;
	/**二级木攻宝石 */
	readonly 7061: ConfigGemData;
	/**三级木攻宝石 */
	readonly 7062: ConfigGemData;
	/**四级木攻宝石 */
	readonly 7063: ConfigGemData;
	/**五级木攻宝石 */
	readonly 7064: ConfigGemData;
	/**六级木攻宝石 */
	readonly 7065: ConfigGemData;
	/**七级木攻宝石 */
	readonly 7066: ConfigGemData;
	/**八级木攻宝石 */
	readonly 7067: ConfigGemData;
	/**九级木攻宝石 */
	readonly 7068: ConfigGemData;
	/**十级木攻宝石 */
	readonly 7069: ConfigGemData;
	/**一级水攻宝石 */
	readonly 7070: ConfigGemData;
	/**二级水攻宝石 */
	readonly 7071: ConfigGemData;
	/**三级水攻宝石 */
	readonly 7072: ConfigGemData;
	/**四级水攻宝石 */
	readonly 7073: ConfigGemData;
	/**五级水攻宝石 */
	readonly 7074: ConfigGemData;
	/**六级水攻宝石 */
	readonly 7075: ConfigGemData;
	/**七级水攻宝石 */
	readonly 7076: ConfigGemData;
	/**八级水攻宝石 */
	readonly 7077: ConfigGemData;
	/**九级水攻宝石 */
	readonly 7078: ConfigGemData;
	/**十级水攻宝石 */
	readonly 7079: ConfigGemData;
	/**一级火攻宝石 */
	readonly 7080: ConfigGemData;
	/**二级火攻宝石 */
	readonly 7081: ConfigGemData;
	/**三级火攻宝石 */
	readonly 7082: ConfigGemData;
	/**四级火攻宝石 */
	readonly 7083: ConfigGemData;
	/**五级火攻宝石 */
	readonly 7084: ConfigGemData;
	/**六级火攻宝石 */
	readonly 7085: ConfigGemData;
	/**七级火攻宝石 */
	readonly 7086: ConfigGemData;
	/**八级火攻宝石 */
	readonly 7087: ConfigGemData;
	/**九级火攻宝石 */
	readonly 7088: ConfigGemData;
	/**十级火攻宝石 */
	readonly 7089: ConfigGemData;
	/**一级土攻宝石 */
	readonly 7090: ConfigGemData;
	/**二级土攻宝石 */
	readonly 7091: ConfigGemData;
	/**三级土攻宝石 */
	readonly 7092: ConfigGemData;
	/**四级土攻宝石 */
	readonly 7093: ConfigGemData;
	/**五级土攻宝石 */
	readonly 7094: ConfigGemData;
	/**六级土攻宝石 */
	readonly 7095: ConfigGemData;
	/**七级土攻宝石 */
	readonly 7096: ConfigGemData;
	/**八级土攻宝石 */
	readonly 7097: ConfigGemData;
	/**九级土攻宝石 */
	readonly 7098: ConfigGemData;
	/**十级土攻宝石 */
	readonly 7099: ConfigGemData;
	/**一级命中宝石 */
	readonly 7100: ConfigGemData;
	/**二级命中宝石 */
	readonly 7101: ConfigGemData;
	/**三级命中宝石 */
	readonly 7102: ConfigGemData;
	/**四级命中宝石 */
	readonly 7103: ConfigGemData;
	/**五级命中宝石 */
	readonly 7104: ConfigGemData;
	/**六级命中宝石 */
	readonly 7105: ConfigGemData;
	/**七级命中宝石 */
	readonly 7106: ConfigGemData;
	/**八级命中宝石 */
	readonly 7107: ConfigGemData;
	/**九级命中宝石 */
	readonly 7108: ConfigGemData;
	/**十级命中宝石 */
	readonly 7109: ConfigGemData;
	/**一级闪避宝石 */
	readonly 7110: ConfigGemData;
	/**二级闪避宝石 */
	readonly 7111: ConfigGemData;
	/**三级闪避宝石 */
	readonly 7112: ConfigGemData;
	/**四级闪避宝石 */
	readonly 7113: ConfigGemData;
	/**五级闪避宝石 */
	readonly 7114: ConfigGemData;
	/**六级闪避宝石 */
	readonly 7115: ConfigGemData;
	/**七级闪避宝石 */
	readonly 7116: ConfigGemData;
	/**八级闪避宝石 */
	readonly 7117: ConfigGemData;
	/**九级闪避宝石 */
	readonly 7118: ConfigGemData;
	/**十级闪避宝石 */
	readonly 7119: ConfigGemData;
	/**一级暴击宝石 */
	readonly 7120: ConfigGemData;
	/**二级暴击宝石 */
	readonly 7121: ConfigGemData;
	/**三级暴击宝石 */
	readonly 7122: ConfigGemData;
	/**四级暴击宝石 */
	readonly 7123: ConfigGemData;
	/**五级暴击宝石 */
	readonly 7124: ConfigGemData;
	/**六级暴击宝石 */
	readonly 7125: ConfigGemData;
	/**七级暴击宝石 */
	readonly 7126: ConfigGemData;
	/**八级暴击宝石 */
	readonly 7127: ConfigGemData;
	/**九级暴击宝石 */
	readonly 7128: ConfigGemData;
	/**十级暴击宝石 */
	readonly 7129: ConfigGemData;
	/**一级身法宝石 */
	readonly 7130: ConfigGemData;
	/**二级身法宝石 */
	readonly 7131: ConfigGemData;
	/**三级身法宝石 */
	readonly 7132: ConfigGemData;
	/**四级身法宝石 */
	readonly 7133: ConfigGemData;
	/**五级身法宝石 */
	readonly 7134: ConfigGemData;
	/**六级身法宝石 */
	readonly 7135: ConfigGemData;
	/**七级身法宝石 */
	readonly 7136: ConfigGemData;
	/**八级身法宝石 */
	readonly 7137: ConfigGemData;
	/**九级身法宝石 */
	readonly 7138: ConfigGemData;
	/**十级身法宝石 */
	readonly 7139: ConfigGemData;
	/**一级耐力宝石 */
	readonly 7140: ConfigGemData;
	/**二级耐力宝石 */
	readonly 7141: ConfigGemData;
	/**三级耐力宝石 */
	readonly 7142: ConfigGemData;
	/**四级耐力宝石 */
	readonly 7143: ConfigGemData;
	/**五级耐力宝石 */
	readonly 7144: ConfigGemData;
	/**六级耐力宝石 */
	readonly 7145: ConfigGemData;
	/**七级耐力宝石 */
	readonly 7146: ConfigGemData;
	/**八级耐力宝石 */
	readonly 7147: ConfigGemData;
	/**九级耐力宝石 */
	readonly 7148: ConfigGemData;
	/**十级耐力宝石 */
	readonly 7149: ConfigGemData;
	/**一级金防宝石 */
	readonly 7150: ConfigGemData;
	/**二级金防宝石 */
	readonly 7151: ConfigGemData;
	/**三级金防宝石 */
	readonly 7152: ConfigGemData;
	/**四级金防宝石 */
	readonly 7153: ConfigGemData;
	/**五级金防宝石 */
	readonly 7154: ConfigGemData;
	/**六级金防宝石 */
	readonly 7155: ConfigGemData;
	/**七级金防宝石 */
	readonly 7156: ConfigGemData;
	/**八级金防宝石 */
	readonly 7157: ConfigGemData;
	/**九级金防宝石 */
	readonly 7158: ConfigGemData;
	/**十级金防宝石 */
	readonly 7159: ConfigGemData;
	/**一级木防宝石 */
	readonly 7160: ConfigGemData;
	/**二级木防宝石 */
	readonly 7161: ConfigGemData;
	/**三级木防宝石 */
	readonly 7162: ConfigGemData;
	/**四级木防宝石 */
	readonly 7163: ConfigGemData;
	/**五级木防宝石 */
	readonly 7164: ConfigGemData;
	/**六级木防宝石 */
	readonly 7165: ConfigGemData;
	/**七级木防宝石 */
	readonly 7166: ConfigGemData;
	/**八级木防宝石 */
	readonly 7167: ConfigGemData;
	/**九级木防宝石 */
	readonly 7168: ConfigGemData;
	/**十级木防宝石 */
	readonly 7169: ConfigGemData;
	/**一级水防宝石 */
	readonly 7170: ConfigGemData;
	/**二级水防宝石 */
	readonly 7171: ConfigGemData;
	/**三级水防宝石 */
	readonly 7172: ConfigGemData;
	/**四级水防宝石 */
	readonly 7173: ConfigGemData;
	/**五级水防宝石 */
	readonly 7174: ConfigGemData;
	/**六级水防宝石 */
	readonly 7175: ConfigGemData;
	/**七级水防宝石 */
	readonly 7176: ConfigGemData;
	/**八级水防宝石 */
	readonly 7177: ConfigGemData;
	/**九级水防宝石 */
	readonly 7178: ConfigGemData;
	/**十级水防宝石 */
	readonly 7179: ConfigGemData;
	/**一级火防宝石 */
	readonly 7180: ConfigGemData;
	/**二级火防宝石 */
	readonly 7181: ConfigGemData;
	/**三级火防宝石 */
	readonly 7182: ConfigGemData;
	/**四级火防宝石 */
	readonly 7183: ConfigGemData;
	/**五级火防宝石 */
	readonly 7184: ConfigGemData;
	/**六级火防宝石 */
	readonly 7185: ConfigGemData;
	/**七级火防宝石 */
	readonly 7186: ConfigGemData;
	/**八级火防宝石 */
	readonly 7187: ConfigGemData;
	/**九级火防宝石 */
	readonly 7188: ConfigGemData;
	/**十级火防宝石 */
	readonly 7189: ConfigGemData;
	/**一级土防宝石 */
	readonly 7190: ConfigGemData;
	/**二级土防宝石 */
	readonly 7191: ConfigGemData;
	/**三级土防宝石 */
	readonly 7192: ConfigGemData;
	/**四级土防宝石 */
	readonly 7193: ConfigGemData;
	/**五级土防宝石 */
	readonly 7194: ConfigGemData;
	/**六级土防宝石 */
	readonly 7195: ConfigGemData;
	/**七级土防宝石 */
	readonly 7196: ConfigGemData;
	/**八级土防宝石 */
	readonly 7197: ConfigGemData;
	/**九级土防宝石 */
	readonly 7198: ConfigGemData;
	/**十级土防宝石 */
	readonly 7199: ConfigGemData;
}