/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigFoodData {
	readonly ID: number;
	/**恢复类型 */
	readonly RecoverType: number;
	/**恢复值 */
	readonly RecoverValue: number;
}

declare interface ConfigFood extends ReadOnlyObject<ConfigFoodData> {
	/**面包 */
	readonly 4000: ConfigFoodData;
	/**汉堡 */
	readonly 4001: ConfigFoodData;
	/**炒面 */
	readonly 4002: ConfigFoodData;
	/**煎饼 */
	readonly 4003: ConfigFoodData;
	/**烧鸡 */
	readonly 4004: ConfigFoodData;
	/**牛排 */
	readonly 4005: ConfigFoodData;
	/**蛋炒饭 */
	readonly 4006: ConfigFoodData;
	/**咖喱饭 */
	readonly 4007: ConfigFoodData;
	/**青椒肉丝 */
	readonly 4008: ConfigFoodData;
	/**鱼香肉丝 */
	readonly 4009: ConfigFoodData;
}