/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigColorData {
	readonly ID: number;
	/**颜色值 */
	readonly Color: string;
}

declare interface ConfigColor extends ReadOnlyObject<ConfigColorData> {
	readonly 1: ConfigColorData;
	readonly 2: ConfigColorData;
	readonly 3: ConfigColorData;
	readonly 4: ConfigColorData;
	readonly 5: ConfigColorData;
	readonly 6: ConfigColorData;
	readonly 7: ConfigColorData;
	readonly 8: ConfigColorData;
	readonly 9: ConfigColorData;
	readonly 10: ConfigColorData;
	readonly 11: ConfigColorData;
	readonly 12: ConfigColorData;
}