/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigEquipmentAdditionData {
	/**id */
	readonly ID: number;
	/**主属性可使用加成 */
	readonly Main: number[];
	/**五行属性可使用加成 */
	readonly WuXing: number[];
	/**副属性可使用加成 */
	readonly Second: number[];
	/**体质属性可使用加成 */
	readonly Body: number[];
}

declare interface ConfigEquipmentAddition extends ReadOnlyObject<ConfigEquipmentAdditionData> {
	/**武器 */
	readonly 1: ConfigEquipmentAdditionData;
	/**头盔 */
	readonly 2: ConfigEquipmentAdditionData;
	/**项链 */
	readonly 3: ConfigEquipmentAdditionData;
	/**衣服 */
	readonly 4: ConfigEquipmentAdditionData;
	/**戒指 */
	readonly 5: ConfigEquipmentAdditionData;
	/**裤子 */
	readonly 6: ConfigEquipmentAdditionData;
	/**护符 */
	readonly 7: ConfigEquipmentAdditionData;
	/**鞋子 */
	readonly 8: ConfigEquipmentAdditionData;
	/**坐骑 */
	readonly 9: ConfigEquipmentAdditionData;
	/**时装 */
	readonly 10: ConfigEquipmentAdditionData;
	/**暗器 */
	readonly 11: ConfigEquipmentAdditionData;
	/**法宝 */
	readonly 12: ConfigEquipmentAdditionData;
}