/**This is automatically generated by BatMain.bat , please do not modify */
declare interface BaseDropOutType {
	id: number;
	count: number;
}
declare interface RandomDropOutType {
	id: number;
	count: number;
	probability: number;
	probBase: number;
}
declare interface AdditionType {
	type: number;
	value: number;
}
declare interface UseRequireType {
	jingJie: number;
	cengJi: number;
}