/**The class is automatically generated by BatMain.bat , please do not modify */
export const enum NetNotify {
	/** @param data {@link INotifyOnlineNextDay} */
	NotifyOnlineNextDay = "NetNotify_NotifyOnlineNextDay",
	/** @param data {@link INotifyVigorRecover} */
	NotifyVigorRecover = "NetNotify_NotifyVigorRecover",
	/** @param data {@link INotifyBattleProgress} */
	NotifyBattleProgress = "NetNotify_NotifyBattleProgress",
	/** @param data {@link INotifyHeart} */
	NotifyHeart = "NetNotify_NotifyHeart",
}