/** This script is generated automatically, Please do not any modify! */declare interface CfgEquipment {
	readonly [key: string]: CfgEquipmentData;
	/** 新手武器 */
	readonly 40000: CfgEquipmentData;
	/** 新手头盔 */
	readonly 40001: CfgEquipmentData;
	/** 新手项链 */
	readonly 40002: CfgEquipmentData;
	/** 新手衣服 */
	readonly 40003: CfgEquipmentData;
	/** 新手戒指 */
	readonly 40004: CfgEquipmentData;
	/** 新手裤子 */
	readonly 40005: CfgEquipmentData;
	/** 新手护符 */
	readonly 40006: CfgEquipmentData;
	/** 新手鞋子 */
	readonly 40007: CfgEquipmentData;
	/** 苍竹长剑 */
	readonly 40008: CfgEquipmentData;
	/** 苍竹项链 */
	readonly 40009: CfgEquipmentData;
	/** 苍竹戒指 */
	readonly 40010: CfgEquipmentData;
	/** 苍竹护符 */
	readonly 40011: CfgEquipmentData;
	/** 苍竹帽 */
	readonly 40012: CfgEquipmentData;
	/** 苍竹衣 */
	readonly 40013: CfgEquipmentData;
	/** 苍竹裤 */
	readonly 40014: CfgEquipmentData;
	/** 苍竹鞋 */
	readonly 40015: CfgEquipmentData;
	/** 平凡长剑 */
	readonly 40016: CfgEquipmentData;
	/** 平凡项链 */
	readonly 40017: CfgEquipmentData;
	/** 平凡戒指 */
	readonly 40018: CfgEquipmentData;
	/** 平凡护符 */
	readonly 40019: CfgEquipmentData;
	/** 平凡帽 */
	readonly 40020: CfgEquipmentData;
	/** 平凡衣 */
	readonly 40021: CfgEquipmentData;
	/** 平凡裤 */
	readonly 40022: CfgEquipmentData;
	/** 平凡鞋 */
	readonly 40023: CfgEquipmentData;
	/** 清风长剑 */
	readonly 40024: CfgEquipmentData;
	/** 清风项链 */
	readonly 40025: CfgEquipmentData;
	/** 清风戒指 */
	readonly 40026: CfgEquipmentData;
	/** 清风护符 */
	readonly 40027: CfgEquipmentData;
	/** 清风帽 */
	readonly 40028: CfgEquipmentData;
	/** 清风衣 */
	readonly 40029: CfgEquipmentData;
	/** 清风裤 */
	readonly 40030: CfgEquipmentData;
	/** 清风鞋 */
	readonly 40031: CfgEquipmentData;
	/** 星海长剑 */
	readonly 40032: CfgEquipmentData;
	/** 星海项链 */
	readonly 40033: CfgEquipmentData;
	/** 星海戒指 */
	readonly 40034: CfgEquipmentData;
	/** 星海护符 */
	readonly 40035: CfgEquipmentData;
	/** 星海帽 */
	readonly 40036: CfgEquipmentData;
	/** 星海衣 */
	readonly 40037: CfgEquipmentData;
	/** 星海裤 */
	readonly 40038: CfgEquipmentData;
	/** 星海鞋 */
	readonly 40039: CfgEquipmentData;
	/** 寂灭长剑 */
	readonly 40040: CfgEquipmentData;
	/** 寂灭项链 */
	readonly 40041: CfgEquipmentData;
	/** 寂灭戒指 */
	readonly 40042: CfgEquipmentData;
	/** 寂灭护符 */
	readonly 40043: CfgEquipmentData;
	/** 寂灭帽 */
	readonly 40044: CfgEquipmentData;
	/** 寂灭衣 */
	readonly 40045: CfgEquipmentData;
	/** 寂灭裤 */
	readonly 40046: CfgEquipmentData;
	/** 寂灭鞋 */
	readonly 40047: CfgEquipmentData;
	/** 烈焰长剑 */
	readonly 40048: CfgEquipmentData;
	/** 烈焰项链 */
	readonly 40049: CfgEquipmentData;
	/** 烈焰戒指 */
	readonly 40050: CfgEquipmentData;
	/** 烈焰护符 */
	readonly 40051: CfgEquipmentData;
	/** 烈焰帽 */
	readonly 40052: CfgEquipmentData;
	/** 烈焰衣 */
	readonly 40053: CfgEquipmentData;
	/** 烈焰裤 */
	readonly 40054: CfgEquipmentData;
	/** 烈焰鞋 */
	readonly 40055: CfgEquipmentData;
	/** 紫月长剑 */
	readonly 40056: CfgEquipmentData;
	/** 紫月项链 */
	readonly 40057: CfgEquipmentData;
	/** 紫月戒指 */
	readonly 40058: CfgEquipmentData;
	/** 紫月护符 */
	readonly 40059: CfgEquipmentData;
	/** 紫月帽 */
	readonly 40060: CfgEquipmentData;
	/** 紫月衣 */
	readonly 40061: CfgEquipmentData;
	/** 紫月裤 */
	readonly 40062: CfgEquipmentData;
	/** 紫月鞋 */
	readonly 40063: CfgEquipmentData;
	/** 踏雪长剑 */
	readonly 40064: CfgEquipmentData;
	/** 踏雪项链 */
	readonly 40065: CfgEquipmentData;
	/** 踏雪戒指 */
	readonly 40066: CfgEquipmentData;
	/** 踏雪护符 */
	readonly 40067: CfgEquipmentData;
	/** 踏雪帽 */
	readonly 40068: CfgEquipmentData;
	/** 踏雪衣 */
	readonly 40069: CfgEquipmentData;
	/** 踏雪裤 */
	readonly 40070: CfgEquipmentData;
	/** 踏雪鞋 */
	readonly 40071: CfgEquipmentData;
	/** 秋水长剑 */
	readonly 40072: CfgEquipmentData;
	/** 秋水项链 */
	readonly 40073: CfgEquipmentData;
	/** 秋水戒指 */
	readonly 40074: CfgEquipmentData;
	/** 秋水护符 */
	readonly 40075: CfgEquipmentData;
	/** 秋水帽 */
	readonly 40076: CfgEquipmentData;
	/** 秋水衣 */
	readonly 40077: CfgEquipmentData;
	/** 秋水裤 */
	readonly 40078: CfgEquipmentData;
	/** 秋水鞋 */
	readonly 40079: CfgEquipmentData;
	/** 破凡长剑 */
	readonly 40080: CfgEquipmentData;
	/** 破凡项链 */
	readonly 40081: CfgEquipmentData;
	/** 破凡戒指 */
	readonly 40082: CfgEquipmentData;
	/** 破凡护符 */
	readonly 40083: CfgEquipmentData;
	/** 破凡帽 */
	readonly 40084: CfgEquipmentData;
	/** 破凡衣 */
	readonly 40085: CfgEquipmentData;
	/** 破凡裤 */
	readonly 40086: CfgEquipmentData;
	/** 破凡鞋 */
	readonly 40087: CfgEquipmentData;
	/** 神木长剑 */
	readonly 40088: CfgEquipmentData;
	/** 神木项链 */
	readonly 40089: CfgEquipmentData;
	/** 神木戒指 */
	readonly 40090: CfgEquipmentData;
	/** 神木护符 */
	readonly 40091: CfgEquipmentData;
	/** 神木帽 */
	readonly 40092: CfgEquipmentData;
	/** 神木衣 */
	readonly 40093: CfgEquipmentData;
	/** 神木裤 */
	readonly 40094: CfgEquipmentData;
	/** 神木鞋 */
	readonly 40095: CfgEquipmentData;
	/** 九州神龙 */
	readonly 49996: CfgEquipmentData;
	/** 骷髅战甲 */
	readonly 49997: CfgEquipmentData;
	/** 观音泪 */
	readonly 49998: CfgEquipmentData;
	/** 仙器 */
	readonly 49999: CfgEquipmentData;
}

declare interface CfgEquipmentData {
	readonly [key: string]: any;
	/** id */
	readonly id: number;
	/** 名字 */
	readonly name: string;
	/** 装备部位 */
	readonly part: number;
}

