/** This script is generated automatically, Please do not any modify! */declare interface CfgGem {
	readonly [key: string]: CfgGemData;
	/** 一级攻击宝石 */
	readonly 7000: CfgGemData;
	/** 二级攻击宝石 */
	readonly 7001: CfgGemData;
	/** 三级攻击宝石 */
	readonly 7002: CfgGemData;
	/** 四级攻击宝石 */
	readonly 7003: CfgGemData;
	/** 五级攻击宝石 */
	readonly 7004: CfgGemData;
	/** 六级攻击宝石 */
	readonly 7005: CfgGemData;
	/** 七级攻击宝石 */
	readonly 7006: CfgGemData;
	/** 八级攻击宝石 */
	readonly 7007: CfgGemData;
	/** 九级攻击宝石 */
	readonly 7008: CfgGemData;
	/** 十级攻击宝石 */
	readonly 7009: CfgGemData;
	/** 一级防御宝石 */
	readonly 7010: CfgGemData;
	/** 二级防御宝石 */
	readonly 7011: CfgGemData;
	/** 三级防御宝石 */
	readonly 7012: CfgGemData;
	/** 四级防御宝石 */
	readonly 7013: CfgGemData;
	/** 五级防御宝石 */
	readonly 7014: CfgGemData;
	/** 六级防御宝石 */
	readonly 7015: CfgGemData;
	/** 七级防御宝石 */
	readonly 7016: CfgGemData;
	/** 八级防御宝石 */
	readonly 7017: CfgGemData;
	/** 九级防御宝石 */
	readonly 7018: CfgGemData;
	/** 十级防御宝石 */
	readonly 7019: CfgGemData;
	/** 一级生命宝石 */
	readonly 7020: CfgGemData;
	/** 二级生命宝石 */
	readonly 7021: CfgGemData;
	/** 三级生命宝石 */
	readonly 7022: CfgGemData;
	/** 四级生命宝石 */
	readonly 7023: CfgGemData;
	/** 五级生命宝石 */
	readonly 7024: CfgGemData;
	/** 六级生命宝石 */
	readonly 7025: CfgGemData;
	/** 七级生命宝石 */
	readonly 7026: CfgGemData;
	/** 八级生命宝石 */
	readonly 7027: CfgGemData;
	/** 九级生命宝石 */
	readonly 7028: CfgGemData;
	/** 十级生命宝石 */
	readonly 7029: CfgGemData;
	/** 一级力量宝石 */
	readonly 7030: CfgGemData;
	/** 二级力量宝石 */
	readonly 7031: CfgGemData;
	/** 三级力量宝石 */
	readonly 7032: CfgGemData;
	/** 四级力量宝石 */
	readonly 7033: CfgGemData;
	/** 五级力量宝石 */
	readonly 7034: CfgGemData;
	/** 六级力量宝石 */
	readonly 7035: CfgGemData;
	/** 七级力量宝石 */
	readonly 7036: CfgGemData;
	/** 八级力量宝石 */
	readonly 7037: CfgGemData;
	/** 九级力量宝石 */
	readonly 7038: CfgGemData;
	/** 十级力量宝石 */
	readonly 7039: CfgGemData;
	/** 一级体力宝石 */
	readonly 7040: CfgGemData;
	/** 二级体力宝石 */
	readonly 7041: CfgGemData;
	/** 三级体力宝石 */
	readonly 7042: CfgGemData;
	/** 四级体力宝石 */
	readonly 7043: CfgGemData;
	/** 五级体力宝石 */
	readonly 7044: CfgGemData;
	/** 六级体力宝石 */
	readonly 7045: CfgGemData;
	/** 七级体力宝石 */
	readonly 7046: CfgGemData;
	/** 八级体力宝石 */
	readonly 7047: CfgGemData;
	/** 九级体力宝石 */
	readonly 7048: CfgGemData;
	/** 十级体力宝石 */
	readonly 7049: CfgGemData;
	/** 一级金攻宝石 */
	readonly 7050: CfgGemData;
	/** 二级金攻宝石 */
	readonly 7051: CfgGemData;
	/** 三级金攻宝石 */
	readonly 7052: CfgGemData;
	/** 四级金攻宝石 */
	readonly 7053: CfgGemData;
	/** 五级金攻宝石 */
	readonly 7054: CfgGemData;
	/** 六级金攻宝石 */
	readonly 7055: CfgGemData;
	/** 七级金攻宝石 */
	readonly 7056: CfgGemData;
	/** 八级金攻宝石 */
	readonly 7057: CfgGemData;
	/** 九级金攻宝石 */
	readonly 7058: CfgGemData;
	/** 十级金攻宝石 */
	readonly 7059: CfgGemData;
	/** 一级木攻宝石 */
	readonly 7060: CfgGemData;
	/** 二级木攻宝石 */
	readonly 7061: CfgGemData;
	/** 三级木攻宝石 */
	readonly 7062: CfgGemData;
	/** 四级木攻宝石 */
	readonly 7063: CfgGemData;
	/** 五级木攻宝石 */
	readonly 7064: CfgGemData;
	/** 六级木攻宝石 */
	readonly 7065: CfgGemData;
	/** 七级木攻宝石 */
	readonly 7066: CfgGemData;
	/** 八级木攻宝石 */
	readonly 7067: CfgGemData;
	/** 九级木攻宝石 */
	readonly 7068: CfgGemData;
	/** 十级木攻宝石 */
	readonly 7069: CfgGemData;
	/** 一级水攻宝石 */
	readonly 7070: CfgGemData;
	/** 二级水攻宝石 */
	readonly 7071: CfgGemData;
	/** 三级水攻宝石 */
	readonly 7072: CfgGemData;
	/** 四级水攻宝石 */
	readonly 7073: CfgGemData;
	/** 五级水攻宝石 */
	readonly 7074: CfgGemData;
	/** 六级水攻宝石 */
	readonly 7075: CfgGemData;
	/** 七级水攻宝石 */
	readonly 7076: CfgGemData;
	/** 八级水攻宝石 */
	readonly 7077: CfgGemData;
	/** 九级水攻宝石 */
	readonly 7078: CfgGemData;
	/** 十级水攻宝石 */
	readonly 7079: CfgGemData;
	/** 一级火攻宝石 */
	readonly 7080: CfgGemData;
	/** 二级火攻宝石 */
	readonly 7081: CfgGemData;
	/** 三级火攻宝石 */
	readonly 7082: CfgGemData;
	/** 四级火攻宝石 */
	readonly 7083: CfgGemData;
	/** 五级火攻宝石 */
	readonly 7084: CfgGemData;
	/** 六级火攻宝石 */
	readonly 7085: CfgGemData;
	/** 七级火攻宝石 */
	readonly 7086: CfgGemData;
	/** 八级火攻宝石 */
	readonly 7087: CfgGemData;
	/** 九级火攻宝石 */
	readonly 7088: CfgGemData;
	/** 十级火攻宝石 */
	readonly 7089: CfgGemData;
	/** 一级土攻宝石 */
	readonly 7090: CfgGemData;
	/** 二级土攻宝石 */
	readonly 7091: CfgGemData;
	/** 三级土攻宝石 */
	readonly 7092: CfgGemData;
	/** 四级土攻宝石 */
	readonly 7093: CfgGemData;
	/** 五级土攻宝石 */
	readonly 7094: CfgGemData;
	/** 六级土攻宝石 */
	readonly 7095: CfgGemData;
	/** 七级土攻宝石 */
	readonly 7096: CfgGemData;
	/** 八级土攻宝石 */
	readonly 7097: CfgGemData;
	/** 九级土攻宝石 */
	readonly 7098: CfgGemData;
	/** 十级土攻宝石 */
	readonly 7099: CfgGemData;
	/** 一级命中宝石 */
	readonly 7100: CfgGemData;
	/** 二级命中宝石 */
	readonly 7101: CfgGemData;
	/** 三级命中宝石 */
	readonly 7102: CfgGemData;
	/** 四级命中宝石 */
	readonly 7103: CfgGemData;
	/** 五级命中宝石 */
	readonly 7104: CfgGemData;
	/** 六级命中宝石 */
	readonly 7105: CfgGemData;
	/** 七级命中宝石 */
	readonly 7106: CfgGemData;
	/** 八级命中宝石 */
	readonly 7107: CfgGemData;
	/** 九级命中宝石 */
	readonly 7108: CfgGemData;
	/** 十级命中宝石 */
	readonly 7109: CfgGemData;
	/** 一级闪避宝石 */
	readonly 7110: CfgGemData;
	/** 二级闪避宝石 */
	readonly 7111: CfgGemData;
	/** 三级闪避宝石 */
	readonly 7112: CfgGemData;
	/** 四级闪避宝石 */
	readonly 7113: CfgGemData;
	/** 五级闪避宝石 */
	readonly 7114: CfgGemData;
	/** 六级闪避宝石 */
	readonly 7115: CfgGemData;
	/** 七级闪避宝石 */
	readonly 7116: CfgGemData;
	/** 八级闪避宝石 */
	readonly 7117: CfgGemData;
	/** 九级闪避宝石 */
	readonly 7118: CfgGemData;
	/** 十级闪避宝石 */
	readonly 7119: CfgGemData;
	/** 一级暴击宝石 */
	readonly 7120: CfgGemData;
	/** 二级暴击宝石 */
	readonly 7121: CfgGemData;
	/** 三级暴击宝石 */
	readonly 7122: CfgGemData;
	/** 四级暴击宝石 */
	readonly 7123: CfgGemData;
	/** 五级暴击宝石 */
	readonly 7124: CfgGemData;
	/** 六级暴击宝石 */
	readonly 7125: CfgGemData;
	/** 七级暴击宝石 */
	readonly 7126: CfgGemData;
	/** 八级暴击宝石 */
	readonly 7127: CfgGemData;
	/** 九级暴击宝石 */
	readonly 7128: CfgGemData;
	/** 十级暴击宝石 */
	readonly 7129: CfgGemData;
	/** 一级身法宝石 */
	readonly 7130: CfgGemData;
	/** 二级身法宝石 */
	readonly 7131: CfgGemData;
	/** 三级身法宝石 */
	readonly 7132: CfgGemData;
	/** 四级身法宝石 */
	readonly 7133: CfgGemData;
	/** 五级身法宝石 */
	readonly 7134: CfgGemData;
	/** 六级身法宝石 */
	readonly 7135: CfgGemData;
	/** 七级身法宝石 */
	readonly 7136: CfgGemData;
	/** 八级身法宝石 */
	readonly 7137: CfgGemData;
	/** 九级身法宝石 */
	readonly 7138: CfgGemData;
	/** 十级身法宝石 */
	readonly 7139: CfgGemData;
	/** 一级耐力宝石 */
	readonly 7140: CfgGemData;
	/** 二级耐力宝石 */
	readonly 7141: CfgGemData;
	/** 三级耐力宝石 */
	readonly 7142: CfgGemData;
	/** 四级耐力宝石 */
	readonly 7143: CfgGemData;
	/** 五级耐力宝石 */
	readonly 7144: CfgGemData;
	/** 六级耐力宝石 */
	readonly 7145: CfgGemData;
	/** 七级耐力宝石 */
	readonly 7146: CfgGemData;
	/** 八级耐力宝石 */
	readonly 7147: CfgGemData;
	/** 九级耐力宝石 */
	readonly 7148: CfgGemData;
	/** 十级耐力宝石 */
	readonly 7149: CfgGemData;
	/** 一级金防宝石 */
	readonly 7150: CfgGemData;
	/** 二级金防宝石 */
	readonly 7151: CfgGemData;
	/** 三级金防宝石 */
	readonly 7152: CfgGemData;
	/** 四级金防宝石 */
	readonly 7153: CfgGemData;
	/** 五级金防宝石 */
	readonly 7154: CfgGemData;
	/** 六级金防宝石 */
	readonly 7155: CfgGemData;
	/** 七级金防宝石 */
	readonly 7156: CfgGemData;
	/** 八级金防宝石 */
	readonly 7157: CfgGemData;
	/** 九级金防宝石 */
	readonly 7158: CfgGemData;
	/** 十级金防宝石 */
	readonly 7159: CfgGemData;
	/** 一级木防宝石 */
	readonly 7160: CfgGemData;
	/** 二级木防宝石 */
	readonly 7161: CfgGemData;
	/** 三级木防宝石 */
	readonly 7162: CfgGemData;
	/** 四级木防宝石 */
	readonly 7163: CfgGemData;
	/** 五级木防宝石 */
	readonly 7164: CfgGemData;
	/** 六级木防宝石 */
	readonly 7165: CfgGemData;
	/** 七级木防宝石 */
	readonly 7166: CfgGemData;
	/** 八级木防宝石 */
	readonly 7167: CfgGemData;
	/** 九级木防宝石 */
	readonly 7168: CfgGemData;
	/** 十级木防宝石 */
	readonly 7169: CfgGemData;
	/** 一级水防宝石 */
	readonly 7170: CfgGemData;
	/** 二级水防宝石 */
	readonly 7171: CfgGemData;
	/** 三级水防宝石 */
	readonly 7172: CfgGemData;
	/** 四级水防宝石 */
	readonly 7173: CfgGemData;
	/** 五级水防宝石 */
	readonly 7174: CfgGemData;
	/** 六级水防宝石 */
	readonly 7175: CfgGemData;
	/** 七级水防宝石 */
	readonly 7176: CfgGemData;
	/** 八级水防宝石 */
	readonly 7177: CfgGemData;
	/** 九级水防宝石 */
	readonly 7178: CfgGemData;
	/** 十级水防宝石 */
	readonly 7179: CfgGemData;
	/** 一级火防宝石 */
	readonly 7180: CfgGemData;
	/** 二级火防宝石 */
	readonly 7181: CfgGemData;
	/** 三级火防宝石 */
	readonly 7182: CfgGemData;
	/** 四级火防宝石 */
	readonly 7183: CfgGemData;
	/** 五级火防宝石 */
	readonly 7184: CfgGemData;
	/** 六级火防宝石 */
	readonly 7185: CfgGemData;
	/** 七级火防宝石 */
	readonly 7186: CfgGemData;
	/** 八级火防宝石 */
	readonly 7187: CfgGemData;
	/** 九级火防宝石 */
	readonly 7188: CfgGemData;
	/** 十级火防宝石 */
	readonly 7189: CfgGemData;
	/** 一级土防宝石 */
	readonly 7190: CfgGemData;
	/** 二级土防宝石 */
	readonly 7191: CfgGemData;
	/** 三级土防宝石 */
	readonly 7192: CfgGemData;
	/** 四级土防宝石 */
	readonly 7193: CfgGemData;
	/** 五级土防宝石 */
	readonly 7194: CfgGemData;
	/** 六级土防宝石 */
	readonly 7195: CfgGemData;
	/** 七级土防宝石 */
	readonly 7196: CfgGemData;
	/** 八级土防宝石 */
	readonly 7197: CfgGemData;
	/** 九级土防宝石 */
	readonly 7198: CfgGemData;
	/** 十级土防宝石 */
	readonly 7199: CfgGemData;
}

declare interface CfgGemData {
	readonly [key: string]: any;
	/** id */
	readonly id: number;
	/**  */
	readonly name: string;
	/** 加成 */
	readonly addition: CfgGemData1;
	/** 等级 */
	readonly level: number;
}

declare interface CfgGemData1 {
	readonly [key: string]: any;
	readonly type: number;
	readonly value: number;
}

