/** This script is generated automatically, Please do not any modify! */export namespace ResPath {
	export const enum UnclassifiedPath {}

	// res/config/
	export const enum ConfigPath {
		Config = "res/config/Config.json",
	}

	// res/font/
	export const enum FontName {
		Font01 = "Font01",
		Font02 = "Font02",
		Font03 = "Font03",
		Font04 = "Font04",
		Font05 = "Font05",
		Font06 = "Font06",
		Font07 = "Font07",
		Font08 = "Font08",
		Font09 = "Font09",
		Font10 = "Font10",
		Font11 = "Font11",
		Font12 = "Font12",
		Font13 = "Font13",
		Font14 = "Font14",
		Font15 = "Font15",
	}

	export const enum FontPath {
		Font01 = "res/font/Font01.ttf",
		Font02 = "res/font/Font02.ttf",
		Font03 = "res/font/Font03.ttf",
		Font04 = "res/font/Font04.ttf",
		Font05 = "res/font/Font05.ttf",
		Font06 = "res/font/Font06.ttf",
		Font07 = "res/font/Font07.ttf",
		Font08 = "res/font/Font08.ttf",
		Font09 = "res/font/Font09.ttf",
		Font10 = "res/font/Font10.ttf",
		Font11 = "res/font/Font11.ttf",
		Font12 = "res/font/Font12.ttf",
		Font13 = "res/font/Font13.ttf",
		Font14 = "res/font/Font14.ttf",
		Font15 = "res/font/Font15.ttf",
	}

	// res/prescreen/
	export const enum PrescreenPath {
		Prescreen = "res/prescreen/prescreen.png",
	}

	// res/skeleton/
	export const enum SkeletonPath {
		Bianhua = "res/skeleton/bianhua.sk",
		Biaoqing = "res/skeleton/biaoqing.sk",
		Biaoti = "res/skeleton/biaoti.sk",
		Cailiaohechen_1 = "res/skeleton/cailiaohechen_1.sk",
		Cailiaohechen_2 = "res/skeleton/cailiaohechen_2.sk",
		Chanzi = "res/skeleton/chanzi.sk",
		Chuxian = "res/skeleton/chuxian.sk",
		Click = "res/skeleton/click.sk",
		Dengjitisheng = "res/skeleton/dengjitisheng.sk",
		Dengjitisheng1 = "res/skeleton/dengjitisheng1.sk",
		Dianji = "res/skeleton/dianji.sk",
		Dianji2 = "res/skeleton/dianji2.sk",
		Dianji3 = "res/skeleton/dianji3.sk",
		Fangjianqiehuan = "res/skeleton/fangjianqiehuan.sk",
		Fengnudemao = "res/skeleton/fengnudemao.sk",
		Guanghuan = "res/skeleton/guanghuan.sk",
		Guangka = "res/skeleton/guangka.sk",
		Guanjiahuode = "res/skeleton/guanjiahuode.sk",
		Gx = "res/skeleton/gx.sk",
		Haidao = "res/skeleton/haidao.sk",
		Huodejiangli = "res/skeleton/huodejiangli.sk",
		Jiajuhuanren = "res/skeleton/jiajuhuanren.sk",
		Jiajuhuode = "res/skeleton/jiajuhuode.sk",
		Jianzao = "res/skeleton/jianzao.sk",
		Jiazai = "res/skeleton/jiazai.sk",
		Jihuo = "res/skeleton/jihuo.sk",
		Jinbi = "res/skeleton/jinbi.sk",
		Jinbi1 = "res/skeleton/jinbi1.sk",
		Jinbi2 = "res/skeleton/jinbi2.sk",
		Jinbixiaoguo = "res/skeleton/jinbixiaoguo.sk",
		Jindutiao = "res/skeleton/jindutiao.sk",
		Jindutiaoguang = "res/skeleton/jindutiaoguang.sk",
		Jinengjiesuo = "res/skeleton/jinengjiesuo.sk",
		Jinyan1 = "res/skeleton/jinyan1.sk",
		Jinyan2 = "res/skeleton/jinyan2.sk",
		Jusangdemao = "res/skeleton/jusangdemao.sk",
		Kaixindemao = "res/skeleton/kaixindemao.sk",
		Kz = "res/skeleton/kz.sk",
		Nengliangman = "res/skeleton/nengliangman.sk",
		New = "res/skeleton/new.sk",
		Round_1 = "res/skeleton/round_1.sk",
		Shanguang = "res/skeleton/shanguang.sk",
		Shengji = "res/skeleton/shengji.sk",
		Shubendakai = "res/skeleton/shubendakai.sk",
		Shubendakai2 = "res/skeleton/shubendakai2.sk",
		Shuidi = "res/skeleton/shuidi.sk",
		Suo = "res/skeleton/suo.sk",
		Suo2 = "res/skeleton/suo2.sk",
		Xg = "res/skeleton/xg.sk",
		Xingxing = "res/skeleton/xingxing.sk",
		Xuanzhongkuang = "res/skeleton/xuanzhongkuang.sk",
		Yan = "res/skeleton/yan.sk",
		Yuchaolailin = "res/skeleton/yuchaolailin.sk",
		Zhaohuanguanjia = "res/skeleton/zhaohuanguanjia.sk",
		Zhuancheng = "res/skeleton/zhuancheng.sk",
	}

	// res/sound/
	export const enum SoundPath {
		Button1 = "res/sound/Button1.wav",
		Button10 = "res/sound/Button10.wav",
		Button11 = "res/sound/Button11.wav",
		Button12 = "res/sound/Button12.wav",
		Button13 = "res/sound/Button13.wav",
		Button14 = "res/sound/Button14.wav",
		Button15 = "res/sound/Button15.wav",
		Button16 = "res/sound/Button16.wav",
		Button17 = "res/sound/Button17.wav",
		Button18 = "res/sound/Button18.wav",
		Button19 = "res/sound/Button19.wav",
		Button2 = "res/sound/Button2.wav",
		Button20 = "res/sound/Button20.wav",
		Button21 = "res/sound/Button21.wav",
		Button22 = "res/sound/Button22.wav",
		Button23 = "res/sound/Button23.wav",
		Button24 = "res/sound/Button24.wav",
		Button25 = "res/sound/Button25.wav",
		Button26 = "res/sound/Button26.wav",
		Button27 = "res/sound/Button27.wav",
		Button28 = "res/sound/Button28.wav",
		Button29 = "res/sound/Button29.wav",
		Button3 = "res/sound/Button3.wav",
		Button30 = "res/sound/Button30.wav",
		Button31 = "res/sound/Button31.wav",
		Button32 = "res/sound/Button32.wav",
		Button33 = "res/sound/Button33.wav",
		Button34 = "res/sound/Button34.wav",
		Button35 = "res/sound/Button35.wav",
		Button36 = "res/sound/Button36.wav",
		Button37 = "res/sound/Button37.wav",
		Button38 = "res/sound/Button38.wav",
		Button39 = "res/sound/Button39.wav",
		Button4 = "res/sound/Button4.wav",
		Button40 = "res/sound/Button40.wav",
		Button41 = "res/sound/Button41.wav",
		Button42 = "res/sound/Button42.wav",
		Button43 = "res/sound/Button43.wav",
		Button44 = "res/sound/Button44.wav",
		Button45 = "res/sound/Button45.wav",
		Button46 = "res/sound/Button46.wav",
		Button47 = "res/sound/Button47.wav",
		Button48 = "res/sound/Button48.wav",
		Button49 = "res/sound/Button49.wav",
		Button5 = "res/sound/Button5.wav",
		Button6 = "res/sound/Button6.wav",
		Button7 = "res/sound/Button7.wav",
		Button8 = "res/sound/Button8.wav",
		Button9 = "res/sound/Button9.wav",
	}

	// res/ui/
	export const enum PkgName {
		PkgBattle = "PkgBattle",
		PkgCommon = "PkgCommon",
		PkgDesign = "PkgDesign",
		PkgLogin = "PkgLogin",
		PkgMain = "PkgMain",
	}

	export const enum PkgPath {
		PkgBattle = "res/ui/PkgBattle",
		PkgCommon = "res/ui/PkgCommon",
		PkgDesign = "res/ui/PkgDesign",
		PkgLogin = "res/ui/PkgLogin",
		PkgMain = "res/ui/PkgMain",
	}

}