/**The script is automatically generated by BatMain.bat , please do not modify */
export const enum ViewID {
	/**Btns */
	BtnCornerTxtView = "BtnCornerTxtView",
	BtnCheckView = "BtnCheckView",

	/**Renders */
	RenderChooseBattleView = "RenderChooseBattleView",
	RenderChatMsgView = "RenderChatMsgView",
	RenderFriendView = "RenderFriendView",
	RenderGoodsView = "RenderGoodsView",
	RenderTextView = "RenderTextView",

	/**Coms */
	ComBattleConfirmView = "ComBattleConfirmView",
	ComConfirmView = "ComConfirmView",
	ComTipInfoView = "ComTipInfoView",
	ComWaitingView = "ComWaitingView",
	ComAbodeView = "ComAbodeView",
	ComCharView = "ComCharView",
	ComGoodsInfoView = "ComGoodsInfoView",
	ComGoodsView = "ComGoodsView",
	ComRenWuView = "ComRenWuView",
	ComSettingView = "ComSettingView",
	ComShopView = "ComShopView",
	ComSkillView = "ComSkillView",
	ComTrainView = "ComTrainView",
	ComXinFaView = "ComXinFaView",
	ComZhiZuoView = "ComZhiZuoView",

	/**UIs */
	UIBattleConfirmView = "UIBattleConfirmView",
	UIBattleView = "UIBattleView",
	UIChooseBattleView = "UIChooseBattleView",
	UIConfirmView = "UIConfirmView",
	UILoading1View = "UILoading1View",
	UILoading2View = "UILoading2View",
	UIWaitingView = "UIWaitingView",
	UILoginView = "UILoginView",
	UIChatView = "UIChatView",
	UIEquipmentInfoView = "UIEquipmentInfoView",
	UIGoodsInfoView = "UIGoodsInfoView",
	UIMainView = "UIMainView",
	UIPlayerInfoView = "UIPlayerInfoView",
	UISectView = "UISectView",
	UISettingView = "UISettingView",
	UISphereToolView = "UISphereToolView",
}