/**The script is automatically generated by BatMain.bat , please do not modify */
import { Logger } from "../../libs/utils/Logger";
import PkgBattleBinder from "../ui/PkgBattle/PkgBattleBinder";
import RenderChooseBattle from "../ui/PkgBattle/RenderChooseBattle";
import UIBattle from "../ui/PkgBattle/UIBattle";
import UIChooseBattle from "../ui/PkgBattle/UIChooseBattle";
import ComNumInput from "../ui/PkgCommon/ComNumInput";
import ComTipInfo from "../ui/PkgCommon/ComTipInfo";
import PkgCommonBinder from "../ui/PkgCommon/PkgCommonBinder";
import UILoading1 from "../ui/PkgCommon/UILoading1";
import UILoading2 from "../ui/PkgCommon/UILoading2";
import UITipConfirm from "../ui/PkgCommon/UITipConfirm";
import UIWaiting from "../ui/PkgCommon/UIWaiting";
import PkgLoginBinder from "../ui/PkgLogin/PkgLoginBinder";
import UILoginMain from "../ui/PkgLogin/UILoginMain";
import ComDongFu from "../ui/PkgMain/ComDongFu";
import ComItemInfo from "../ui/PkgMain/ComItemInfo";
import ComJueSe from "../ui/PkgMain/ComJueSe";
import ComLiLian from "../ui/PkgMain/ComLiLian";
import ComRenWu from "../ui/PkgMain/ComRenWu";
import ComShangCheng from "../ui/PkgMain/ComShangCheng";
import ComSkill from "../ui/PkgMain/ComSkill";
import ComWuPin from "../ui/PkgMain/ComWuPin";
import ComXinFa from "../ui/PkgMain/ComXinFa";
import ComZhiZuo from "../ui/PkgMain/ComZhiZuo";
import PkgMainBinder from "../ui/PkgMain/PkgMainBinder";
import RenderBag from "../ui/PkgMain/RenderBag";
import RenderChatMsg from "../ui/PkgMain/RenderChatMsg";
import RenderFriend from "../ui/PkgMain/RenderFriend";
import RenderText from "../ui/PkgMain/RenderText";
import UIChat from "../ui/PkgMain/UIChat";
import UIEquipmentInfo from "../ui/PkgMain/UIEquipmentInfo";
import UIMain from "../ui/PkgMain/UIMain";
import UIPlayerInfo from "../ui/PkgMain/UIPlayerInfo";
import UISect from "../ui/PkgMain/UISect";
import UISetting from "../ui/PkgMain/UISetting";
import UISphereTool from "../ui/PkgMain/UISphereTool";
import { RenderChooseBattleView } from "../view/PkgBattle/Renders/RenderChooseBattleView";
import { UIBattleView } from "../view/PkgBattle/UIBattleView";
import { UIChooseBattleView } from "../view/PkgBattle/UIChooseBattleView";
import { ComNumInputView } from "../view/PkgCommon/Coms/ComNumInputView";
import { ComTipInfoView } from "../view/PkgCommon/Coms/ComTipInfoView";
import { UILoading1View } from "../view/PkgCommon/UILoading1View";
import { UILoading2View } from "../view/PkgCommon/UILoading2View";
import { UITipConfirmView } from "../view/PkgCommon/UITipConfirmView";
import { UIWaitingView } from "../view/PkgCommon/UIWaitingView";
import { UILoginMainView } from "../view/PkgLogin/UILoginMainView";
import { ComDongFuView } from "../view/PkgMain/Coms/ComDongFuView";
import { ComItemInfoView } from "../view/PkgMain/Coms/ComItemInfoView";
import { ComJueSeView } from "../view/PkgMain/Coms/ComJueSeView";
import { ComLiLianView } from "../view/PkgMain/Coms/ComLiLianView";
import { ComRenWuView } from "../view/PkgMain/Coms/ComRenWuView";
import { ComShangChengView } from "../view/PkgMain/Coms/ComShangChengView";
import { ComSkillView } from "../view/PkgMain/Coms/ComSkillView";
import { ComWuPinView } from "../view/PkgMain/Coms/ComWuPinView";
import { ComXinFaView } from "../view/PkgMain/Coms/ComXinFaView";
import { ComZhiZuoView } from "../view/PkgMain/Coms/ComZhiZuoView";
import { RenderBagView } from "../view/PkgMain/Renders/RenderBagView";
import { RenderChatMsgView } from "../view/PkgMain/Renders/RenderChatMsgView";
import { RenderFriendView } from "../view/PkgMain/Renders/RenderFriendView";
import { RenderTextView } from "../view/PkgMain/Renders/RenderTextView";
import { UIChatView } from "../view/PkgMain/UIChatView";
import { UIEquipmentInfoView } from "../view/PkgMain/UIEquipmentInfoView";
import { UIMainView } from "../view/PkgMain/UIMainView";
import { UIPlayerInfoView } from "../view/PkgMain/UIPlayerInfoView";
import { UISectView } from "../view/PkgMain/UISectView";
import { UISettingView } from "../view/PkgMain/UISettingView";
import { UISphereToolView } from "../view/PkgMain/UISphereToolView";
import { UIBattleCtrl } from "../viewCtrl/PkgBattle/UIBattleCtrl";
import { UIChooseBattleCtrl } from "../viewCtrl/PkgBattle/UIChooseBattleCtrl";
import { ComNumInputCtrl } from "../viewCtrl/PkgCommon/Coms/ComNumInputCtrl";
import { ComTipInfoCtrl } from "../viewCtrl/PkgCommon/Coms/ComTipInfoCtrl";
import { UILoading1Ctrl } from "../viewCtrl/PkgCommon/UILoading1Ctrl";
import { UILoading2Ctrl } from "../viewCtrl/PkgCommon/UILoading2Ctrl";
import { UITipConfirmCtrl } from "../viewCtrl/PkgCommon/UITipConfirmCtrl";
import { UIWaitingCtrl } from "../viewCtrl/PkgCommon/UIWaitingCtrl";
import { UILoginMainCtrl } from "../viewCtrl/PkgLogin/UILoginMainCtrl";
import { ComDongFuCtrl } from "../viewCtrl/PkgMain/Coms/ComDongFuCtrl";
import { ComItemInfoCtrl } from "../viewCtrl/PkgMain/Coms/ComItemInfoCtrl";
import { ComJueSeCtrl } from "../viewCtrl/PkgMain/Coms/ComJueSeCtrl";
import { ComLiLianCtrl } from "../viewCtrl/PkgMain/Coms/ComLiLianCtrl";
import { ComRenWuCtrl } from "../viewCtrl/PkgMain/Coms/ComRenWuCtrl";
import { ComShangChengCtrl } from "../viewCtrl/PkgMain/Coms/ComShangChengCtrl";
import { ComSkillCtrl } from "../viewCtrl/PkgMain/Coms/ComSkillCtrl";
import { ComWuPinCtrl } from "../viewCtrl/PkgMain/Coms/ComWuPinCtrl";
import { ComXinFaCtrl } from "../viewCtrl/PkgMain/Coms/ComXinFaCtrl";
import { ComZhiZuoCtrl } from "../viewCtrl/PkgMain/Coms/ComZhiZuoCtrl";
import { UIChatCtrl } from "../viewCtrl/PkgMain/UIChatCtrl";
import { UIEquipmentInfoCtrl } from "../viewCtrl/PkgMain/UIEquipmentInfoCtrl";
import { UIMainCtrl } from "../viewCtrl/PkgMain/UIMainCtrl";
import { UIPlayerInfoCtrl } from "../viewCtrl/PkgMain/UIPlayerInfoCtrl";
import { UISectCtrl } from "../viewCtrl/PkgMain/UISectCtrl";
import { UISettingCtrl } from "../viewCtrl/PkgMain/UISettingCtrl";
import { UISphereToolCtrl } from "../viewCtrl/PkgMain/UISphereToolCtrl";
import { UIBattleProxy } from "../viewProxy/PkgBattle/UIBattleProxy";
import { UIChooseBattleProxy } from "../viewProxy/PkgBattle/UIChooseBattleProxy";
import { ComNumInputProxy } from "../viewProxy/PkgCommon/Coms/ComNumInputProxy";
import { ComTipInfoProxy } from "../viewProxy/PkgCommon/Coms/ComTipInfoProxy";
import { UILoading1Proxy } from "../viewProxy/PkgCommon/UILoading1Proxy";
import { UILoading2Proxy } from "../viewProxy/PkgCommon/UILoading2Proxy";
import { UITipConfirmProxy } from "../viewProxy/PkgCommon/UITipConfirmProxy";
import { UIWaitingProxy } from "../viewProxy/PkgCommon/UIWaitingProxy";
import { UILoginMainProxy } from "../viewProxy/PkgLogin/UILoginMainProxy";
import { ComDongFuProxy } from "../viewProxy/PkgMain/Coms/ComDongFuProxy";
import { ComItemInfoProxy } from "../viewProxy/PkgMain/Coms/ComItemInfoProxy";
import { ComJueSeProxy } from "../viewProxy/PkgMain/Coms/ComJueSeProxy";
import { ComLiLianProxy } from "../viewProxy/PkgMain/Coms/ComLiLianProxy";
import { ComRenWuProxy } from "../viewProxy/PkgMain/Coms/ComRenWuProxy";
import { ComShangChengProxy } from "../viewProxy/PkgMain/Coms/ComShangChengProxy";
import { ComSkillProxy } from "../viewProxy/PkgMain/Coms/ComSkillProxy";
import { ComWuPinProxy } from "../viewProxy/PkgMain/Coms/ComWuPinProxy";
import { ComXinFaProxy } from "../viewProxy/PkgMain/Coms/ComXinFaProxy";
import { ComZhiZuoProxy } from "../viewProxy/PkgMain/Coms/ComZhiZuoProxy";
import { UIChatProxy } from "../viewProxy/PkgMain/UIChatProxy";
import { UIEquipmentInfoProxy } from "../viewProxy/PkgMain/UIEquipmentInfoProxy";
import { UIMainProxy } from "../viewProxy/PkgMain/UIMainProxy";
import { UIPlayerInfoProxy } from "../viewProxy/PkgMain/UIPlayerInfoProxy";
import { UISectProxy } from "../viewProxy/PkgMain/UISectProxy";
import { UISettingProxy } from "../viewProxy/PkgMain/UISettingProxy";
import { UISphereToolProxy } from "../viewProxy/PkgMain/UISphereToolProxy";
import { uiMgr } from "./UIManager";
import { ViewID } from "./ViewID";

const logger = Logger.Create("ViewRegister", true);

class ViewRegister {

	Init() {
		this.pkgBind();
		this.viewBind();
		this.registerView();
	}

	/**包bind */
	private pkgBind() {
		PkgBattleBinder.bindAll();
		PkgCommonBinder.bindAll();
		PkgLoginBinder.bindAll();
		PkgMainBinder.bindAll();
	}

	/**页面替换bind */
	private viewBind() {
		//Coms
		fgui.UIObjectFactory.setExtension(ComNumInput.URL, ComNumInputView);
		fgui.UIObjectFactory.setExtension(ComTipInfo.URL, ComTipInfoView);
		fgui.UIObjectFactory.setExtension(ComDongFu.URL, ComDongFuView);
		fgui.UIObjectFactory.setExtension(ComItemInfo.URL, ComItemInfoView);
		fgui.UIObjectFactory.setExtension(ComJueSe.URL, ComJueSeView);
		fgui.UIObjectFactory.setExtension(ComLiLian.URL, ComLiLianView);
		fgui.UIObjectFactory.setExtension(ComRenWu.URL, ComRenWuView);
		fgui.UIObjectFactory.setExtension(ComShangCheng.URL, ComShangChengView);
		fgui.UIObjectFactory.setExtension(ComSkill.URL, ComSkillView);
		fgui.UIObjectFactory.setExtension(ComWuPin.URL, ComWuPinView);
		fgui.UIObjectFactory.setExtension(ComXinFa.URL, ComXinFaView);
		fgui.UIObjectFactory.setExtension(ComZhiZuo.URL, ComZhiZuoView);

		//Renders
		fgui.UIObjectFactory.setExtension(RenderChooseBattle.URL, RenderChooseBattleView);
		fgui.UIObjectFactory.setExtension(RenderBag.URL, RenderBagView);
		fgui.UIObjectFactory.setExtension(RenderChatMsg.URL, RenderChatMsgView);
		fgui.UIObjectFactory.setExtension(RenderFriend.URL, RenderFriendView);
		fgui.UIObjectFactory.setExtension(RenderText.URL, RenderTextView);

		//Views
		fgui.UIObjectFactory.setExtension(UIBattle.URL, UIBattleView);
		fgui.UIObjectFactory.setExtension(UIChooseBattle.URL, UIChooseBattleView);
		fgui.UIObjectFactory.setExtension(UILoading1.URL, UILoading1View);
		fgui.UIObjectFactory.setExtension(UILoading2.URL, UILoading2View);
		fgui.UIObjectFactory.setExtension(UITipConfirm.URL, UITipConfirmView);
		fgui.UIObjectFactory.setExtension(UIWaiting.URL, UIWaitingView);
		fgui.UIObjectFactory.setExtension(UILoginMain.URL, UILoginMainView);
		fgui.UIObjectFactory.setExtension(UIChat.URL, UIChatView);
		fgui.UIObjectFactory.setExtension(UIEquipmentInfo.URL, UIEquipmentInfoView);
		fgui.UIObjectFactory.setExtension(UIMain.URL, UIMainView);
		fgui.UIObjectFactory.setExtension(UIPlayerInfo.URL, UIPlayerInfoView);
		fgui.UIObjectFactory.setExtension(UISect.URL, UISectView);
		fgui.UIObjectFactory.setExtension(UISetting.URL, UISettingView);
		fgui.UIObjectFactory.setExtension(UISphereTool.URL, UISphereToolView);
	}

	/**页面注册 */
	private registerView() {
		const register = uiMgr.registView.bind(uiMgr);
		//Coms
		register(ViewID.ComNumInputView, ComNumInputView, ComNumInputCtrl, ComNumInputProxy);
		register(ViewID.ComTipInfoView, ComTipInfoView, ComTipInfoCtrl, ComTipInfoProxy);
		register(ViewID.ComDongFuView, ComDongFuView, ComDongFuCtrl, ComDongFuProxy);
		register(ViewID.ComItemInfoView, ComItemInfoView, ComItemInfoCtrl, ComItemInfoProxy);
		register(ViewID.ComJueSeView, ComJueSeView, ComJueSeCtrl, ComJueSeProxy);
		register(ViewID.ComLiLianView, ComLiLianView, ComLiLianCtrl, ComLiLianProxy);
		register(ViewID.ComRenWuView, ComRenWuView, ComRenWuCtrl, ComRenWuProxy);
		register(ViewID.ComShangChengView, ComShangChengView, ComShangChengCtrl, ComShangChengProxy);
		register(ViewID.ComSkillView, ComSkillView, ComSkillCtrl, ComSkillProxy);
		register(ViewID.ComWuPinView, ComWuPinView, ComWuPinCtrl, ComWuPinProxy);
		register(ViewID.ComXinFaView, ComXinFaView, ComXinFaCtrl, ComXinFaProxy);
		register(ViewID.ComZhiZuoView, ComZhiZuoView, ComZhiZuoCtrl, ComZhiZuoProxy);

		//Views
		register(ViewID.UIBattleView, UIBattleView, UIBattleCtrl, UIBattleProxy);
		register(ViewID.UIChooseBattleView, UIChooseBattleView, UIChooseBattleCtrl, UIChooseBattleProxy);
		register(ViewID.UILoading1View, UILoading1View, UILoading1Ctrl, UILoading1Proxy);
		register(ViewID.UILoading2View, UILoading2View, UILoading2Ctrl, UILoading2Proxy);
		register(ViewID.UITipConfirmView, UITipConfirmView, UITipConfirmCtrl, UITipConfirmProxy);
		register(ViewID.UIWaitingView, UIWaitingView, UIWaitingCtrl, UIWaitingProxy);
		register(ViewID.UILoginMainView, UILoginMainView, UILoginMainCtrl, UILoginMainProxy);
		register(ViewID.UIChatView, UIChatView, UIChatCtrl, UIChatProxy);
		register(ViewID.UIEquipmentInfoView, UIEquipmentInfoView, UIEquipmentInfoCtrl, UIEquipmentInfoProxy);
		register(ViewID.UIMainView, UIMainView, UIMainCtrl, UIMainProxy);
		register(ViewID.UIPlayerInfoView, UIPlayerInfoView, UIPlayerInfoCtrl, UIPlayerInfoProxy);
		register(ViewID.UISectView, UISectView, UISectCtrl, UISectProxy);
		register(ViewID.UISettingView, UISettingView, UISettingCtrl, UISettingProxy);
		register(ViewID.UISphereToolView, UISphereToolView, UISphereToolCtrl, UISphereToolProxy);
	}
}
export const uiRegister = new ViewRegister();