/**The script is automatically generated by BatMain.bat , please do not modify */
import PkgBattleBinder from "../ui/PkgBattle/PkgBattleBinder";
import PkgCommonBinder from "../ui/PkgCommon/PkgCommonBinder";
import PkgLittleGameBinder from "../ui/PkgLittleGame/PkgLittleGameBinder";
import PkgLoginBinder from "../ui/PkgLogin/PkgLoginBinder";
import PkgMainBinder from "../ui/PkgMain/PkgMainBinder";
import { BtnCheckCtrl } from "../view/PkgMain/controller/btns/BtnCheckCtrl";
import { BtnCheckView } from "../view/PkgMain/view/btns/BtnCheckView";
import { BtnMainKindCtrl } from "../view/PkgMain/controller/btns/BtnMainKindCtrl";
import { BtnMainKindView } from "../view/PkgMain/view/btns/BtnMainKindView";
import { BtnTxtCtrl } from "../view/PkgCommon/controller/btns/BtnTxtCtrl";
import { BtnTxtView } from "../view/PkgCommon/view/btns/BtnTxtView";
import { ComAbodeCtrl } from "../view/PkgMain/controller/coms/ComAbodeCtrl";
import { ComAbodeView } from "../view/PkgMain/view/coms/ComAbodeView";
import { ComBattleConfirmCtrl } from "../view/PkgBattle/controller/coms/ComBattleConfirmCtrl";
import { ComBattleConfirmView } from "../view/PkgBattle/view/coms/ComBattleConfirmView";
import { ComCharCtrl } from "../view/PkgMain/controller/coms/ComCharCtrl";
import { ComCharView } from "../view/PkgMain/view/coms/ComCharView";
import { ComConfirmCtrl } from "../view/PkgCommon/controller/coms/ComConfirmCtrl";
import { ComConfirmView } from "../view/PkgCommon/view/coms/ComConfirmView";
import { ComGoodsCtrl } from "../view/PkgMain/controller/coms/ComGoodsCtrl";
import { ComGoodsInfoCtrl } from "../view/PkgMain/controller/coms/ComGoodsInfoCtrl";
import { ComGoodsInfoView } from "../view/PkgMain/view/coms/ComGoodsInfoView";
import { ComGoodsView } from "../view/PkgMain/view/coms/ComGoodsView";
import { ComItem2048Ctrl } from "../view/PkgLittleGame/controller/coms/ComItem2048Ctrl";
import { ComItem2048View } from "../view/PkgLittleGame/view/coms/ComItem2048View";
import { ComRedDotCtrl } from "../view/PkgCommon/controller/coms/ComRedDotCtrl";
import { ComRedDotView } from "../view/PkgCommon/view/coms/ComRedDotView";
import { ComRenWuCtrl } from "../view/PkgMain/controller/coms/ComRenWuCtrl";
import { ComRenWuView } from "../view/PkgMain/view/coms/ComRenWuView";
import { ComSettingCtrl } from "../view/PkgMain/controller/coms/ComSettingCtrl";
import { ComSettingView } from "../view/PkgMain/view/coms/ComSettingView";
import { ComShopCtrl } from "../view/PkgMain/controller/coms/ComShopCtrl";
import { ComShopView } from "../view/PkgMain/view/coms/ComShopView";
import { ComSkillCtrl } from "../view/PkgMain/controller/coms/ComSkillCtrl";
import { ComSkillView } from "../view/PkgMain/view/coms/ComSkillView";
import { ComTenWaterCtrl } from "../view/PkgLittleGame/controller/coms/ComTenWaterCtrl";
import { ComTenWaterView } from "../view/PkgLittleGame/view/coms/ComTenWaterView";
import { ComTipInfoCtrl } from "../view/PkgCommon/controller/coms/ComTipInfoCtrl";
import { ComTipInfoView } from "../view/PkgCommon/view/coms/ComTipInfoView";
import { ComTrainCtrl } from "../view/PkgMain/controller/coms/ComTrainCtrl";
import { ComTrainView } from "../view/PkgMain/view/coms/ComTrainView";
import { ComWaitingCtrl } from "../view/PkgCommon/controller/coms/ComWaitingCtrl";
import { ComWaitingView } from "../view/PkgCommon/view/coms/ComWaitingView";
import { ComXinFaCtrl } from "../view/PkgMain/controller/coms/ComXinFaCtrl";
import { ComXinFaView } from "../view/PkgMain/view/coms/ComXinFaView";
import { ComZhiZuoCtrl } from "../view/PkgMain/controller/coms/ComZhiZuoCtrl";
import { ComZhiZuoView } from "../view/PkgMain/view/coms/ComZhiZuoView";
import { RenderChatMsgCtrl } from "../view/PkgMain/controller/renders/RenderChatMsgCtrl";
import { RenderChatMsgView } from "../view/PkgMain/view/renders/RenderChatMsgView";
import { RenderChooseBattleCtrl } from "../view/PkgBattle/controller/renders/RenderChooseBattleCtrl";
import { RenderChooseBattleView } from "../view/PkgBattle/view/renders/RenderChooseBattleView";
import { RenderFriendCtrl } from "../view/PkgMain/controller/renders/RenderFriendCtrl";
import { RenderFriendView } from "../view/PkgMain/view/renders/RenderFriendView";
import { RenderGoodsCtrl } from "../view/PkgMain/controller/renders/RenderGoodsCtrl";
import { RenderGoodsView } from "../view/PkgMain/view/renders/RenderGoodsView";
import { RenderTextCtrl } from "../view/PkgMain/controller/renders/RenderTextCtrl";
import { RenderTextView } from "../view/PkgMain/view/renders/RenderTextView";
import { UI2048Ctrl } from "../view/PkgLittleGame/controller/UI2048Ctrl";
import { UI2048Proxy } from "../view/PkgLittleGame/proxy/UI2048Proxy";
import { UI2048View } from "../view/PkgLittleGame/view/UI2048View";
import { UIBattleConfirmCtrl } from "../view/PkgBattle/controller/UIBattleConfirmCtrl";
import { UIBattleConfirmProxy } from "../view/PkgBattle/proxy/UIBattleConfirmProxy";
import { UIBattleConfirmView } from "../view/PkgBattle/view/UIBattleConfirmView";
import { UIBattleCtrl } from "../view/PkgBattle/controller/UIBattleCtrl";
import { UIBattleProxy } from "../view/PkgBattle/proxy/UIBattleProxy";
import { UIBattleView } from "../view/PkgBattle/view/UIBattleView";
import { UIChatCtrl } from "../view/PkgMain/controller/UIChatCtrl";
import { UIChatProxy } from "../view/PkgMain/proxy/UIChatProxy";
import { UIChatView } from "../view/PkgMain/view/UIChatView";
import { UIChooseBattleCtrl } from "../view/PkgBattle/controller/UIChooseBattleCtrl";
import { UIChooseBattleProxy } from "../view/PkgBattle/proxy/UIChooseBattleProxy";
import { UIChooseBattleView } from "../view/PkgBattle/view/UIChooseBattleView";
import { UIConfirmCtrl } from "../view/PkgCommon/controller/UIConfirmCtrl";
import { UIConfirmProxy } from "../view/PkgCommon/proxy/UIConfirmProxy";
import { UIConfirmView } from "../view/PkgCommon/view/UIConfirmView";
import { UIEquipmentInfoCtrl } from "../view/PkgMain/controller/UIEquipmentInfoCtrl";
import { UIEquipmentInfoProxy } from "../view/PkgMain/proxy/UIEquipmentInfoProxy";
import { UIEquipmentInfoView } from "../view/PkgMain/view/UIEquipmentInfoView";
import { UIGoodsInfoCtrl } from "../view/PkgMain/controller/UIGoodsInfoCtrl";
import { UIGoodsInfoEvent } from "../view/PkgMain/event/UIGoodsInfoEvent";
import { UIGoodsInfoProxy } from "../view/PkgMain/proxy/UIGoodsInfoProxy";
import { UIGoodsInfoView } from "../view/PkgMain/view/UIGoodsInfoView";
import { UILittleGameCtrl } from "../view/PkgLittleGame/controller/UILittleGameCtrl";
import { UILittleGameProxy } from "../view/PkgLittleGame/proxy/UILittleGameProxy";
import { UILittleGameView } from "../view/PkgLittleGame/view/UILittleGameView";
import { UILoading1Ctrl } from "../view/PkgCommon/controller/UILoading1Ctrl";
import { UILoading1Proxy } from "../view/PkgCommon/proxy/UILoading1Proxy";
import { UILoading1View } from "../view/PkgCommon/view/UILoading1View";
import { UILoading2Ctrl } from "../view/PkgCommon/controller/UILoading2Ctrl";
import { UILoading2Proxy } from "../view/PkgCommon/proxy/UILoading2Proxy";
import { UILoading2View } from "../view/PkgCommon/view/UILoading2View";
import { UILoginCtrl } from "../view/PkgLogin/controller/UILoginCtrl";
import { UILoginEvent } from "../view/PkgLogin/event/UILoginEvent";
import { UILoginProxy } from "../view/PkgLogin/proxy/UILoginProxy";
import { UILoginView } from "../view/PkgLogin/view/UILoginView";
import { UIMainCtrl } from "../view/PkgMain/controller/UIMainCtrl";
import { UIMainProxy } from "../view/PkgMain/proxy/UIMainProxy";
import { UIMainView } from "../view/PkgMain/view/UIMainView";
import { UIPlayerInfoCtrl } from "../view/PkgMain/controller/UIPlayerInfoCtrl";
import { UIPlayerInfoProxy } from "../view/PkgMain/proxy/UIPlayerInfoProxy";
import { UIPlayerInfoView } from "../view/PkgMain/view/UIPlayerInfoView";
import { UISectCtrl } from "../view/PkgMain/controller/UISectCtrl";
import { UISectProxy } from "../view/PkgMain/proxy/UISectProxy";
import { UISectView } from "../view/PkgMain/view/UISectView";
import { UISettingCtrl } from "../view/PkgMain/controller/UISettingCtrl";
import { UISettingProxy } from "../view/PkgMain/proxy/UISettingProxy";
import { UISettingView } from "../view/PkgMain/view/UISettingView";
import { UISnakeCtrl } from "../view/PkgLittleGame/controller/UISnakeCtrl";
import { UISnakeProxy } from "../view/PkgLittleGame/proxy/UISnakeProxy";
import { UISnakeView } from "../view/PkgLittleGame/view/UISnakeView";
import { UISphereToolCtrl } from "../view/PkgMain/controller/UISphereToolCtrl";
import { UISphereToolProxy } from "../view/PkgMain/proxy/UISphereToolProxy";
import { UISphereToolView } from "../view/PkgMain/view/UISphereToolView";
import { UITenWaterCtrl } from "../view/PkgLittleGame/controller/UITenWaterCtrl";
import { UITenWaterProxy } from "../view/PkgLittleGame/proxy/UITenWaterProxy";
import { UITenWaterView } from "../view/PkgLittleGame/view/UITenWaterView";
import { UITest3DCtrl } from "../view/PkgLittleGame/controller/UITest3DCtrl";
import { UITest3DProxy } from "../view/PkgLittleGame/proxy/UITest3DProxy";
import { UITest3DView } from "../view/PkgLittleGame/view/UITest3DView";
import { UIWaitingCtrl } from "../view/PkgCommon/controller/UIWaitingCtrl";
import { UIWaitingProxy } from "../view/PkgCommon/proxy/UIWaitingProxy";
import { UIWaitingView } from "../view/PkgCommon/view/UIWaitingView";
import { uiMgr } from "./UIManager";


class ViewRegister {

    init() {
        this.pkgBind();
        this.registerView();
    }

    /**包bind */
    private pkgBind() {
		PkgBattleBinder.bindAll();
		PkgCommonBinder.bindAll();
		PkgLittleGameBinder.bindAll();
		PkgLoginBinder.bindAll();
		PkgMainBinder.bindAll();
	}

    /**页面注册 */
    private registerView() {
		const register = uiMgr.registView.bind(uiMgr);
		//Btns
		register(ViewID.BtnTxtView, BtnTxtView, BtnTxtCtrl);
		register(ViewID.BtnCheckView, BtnCheckView, BtnCheckCtrl);
		register(ViewID.BtnMainKindView, BtnMainKindView, BtnMainKindCtrl);

		//Renders
		register(ViewID.RenderChooseBattleView, RenderChooseBattleView, RenderChooseBattleCtrl);
		register(ViewID.RenderChatMsgView, RenderChatMsgView, RenderChatMsgCtrl);
		register(ViewID.RenderFriendView, RenderFriendView, RenderFriendCtrl);
		register(ViewID.RenderGoodsView, RenderGoodsView, RenderGoodsCtrl);
		register(ViewID.RenderTextView, RenderTextView, RenderTextCtrl);

		//Coms
		register(ViewID.ComBattleConfirmView, ComBattleConfirmView, ComBattleConfirmCtrl);
		register(ViewID.ComConfirmView, ComConfirmView, ComConfirmCtrl);
		register(ViewID.ComRedDotView, ComRedDotView, ComRedDotCtrl);
		register(ViewID.ComTipInfoView, ComTipInfoView, ComTipInfoCtrl);
		register(ViewID.ComWaitingView, ComWaitingView, ComWaitingCtrl);
		register(ViewID.ComItem2048View, ComItem2048View, ComItem2048Ctrl);
		register(ViewID.ComTenWaterView, ComTenWaterView, ComTenWaterCtrl);
		register(ViewID.ComAbodeView, ComAbodeView, ComAbodeCtrl);
		register(ViewID.ComCharView, ComCharView, ComCharCtrl);
		register(ViewID.ComGoodsView, ComGoodsView, ComGoodsCtrl);
		register(ViewID.ComGoodsInfoView, ComGoodsInfoView, ComGoodsInfoCtrl);
		register(ViewID.ComRenWuView, ComRenWuView, ComRenWuCtrl);
		register(ViewID.ComSettingView, ComSettingView, ComSettingCtrl);
		register(ViewID.ComShopView, ComShopView, ComShopCtrl);
		register(ViewID.ComSkillView, ComSkillView, ComSkillCtrl);
		register(ViewID.ComTrainView, ComTrainView, ComTrainCtrl);
		register(ViewID.ComXinFaView, ComXinFaView, ComXinFaCtrl);
		register(ViewID.ComZhiZuoView, ComZhiZuoView, ComZhiZuoCtrl);

		//UIs
		register(ViewID.UIBattleView, UIBattleView, UIBattleCtrl, UIBattleProxy);
		register(ViewID.UIBattleConfirmView, UIBattleConfirmView, UIBattleConfirmCtrl, UIBattleConfirmProxy);
		register(ViewID.UIChooseBattleView, UIChooseBattleView, UIChooseBattleCtrl, UIChooseBattleProxy);
		register(ViewID.UIConfirmView, UIConfirmView, UIConfirmCtrl, UIConfirmProxy);
		register(ViewID.UILoading1View, UILoading1View, UILoading1Ctrl, UILoading1Proxy);
		register(ViewID.UILoading2View, UILoading2View, UILoading2Ctrl, UILoading2Proxy);
		register(ViewID.UIWaitingView, UIWaitingView, UIWaitingCtrl, UIWaitingProxy);
		register(ViewID.UI2048View, UI2048View, UI2048Ctrl, UI2048Proxy);
		register(ViewID.UILittleGameView, UILittleGameView, UILittleGameCtrl, UILittleGameProxy);
		register(ViewID.UISnakeView, UISnakeView, UISnakeCtrl, UISnakeProxy);
		register(ViewID.UITenWaterView, UITenWaterView, UITenWaterCtrl, UITenWaterProxy);
		register(ViewID.UITest3DView, UITest3DView, UITest3DCtrl, UITest3DProxy);
		register(ViewID.UILoginView, UILoginView, UILoginCtrl, UILoginProxy);
		register(ViewID.UIChatView, UIChatView, UIChatCtrl, UIChatProxy);
		register(ViewID.UIEquipmentInfoView, UIEquipmentInfoView, UIEquipmentInfoCtrl, UIEquipmentInfoProxy);
		register(ViewID.UIGoodsInfoView, UIGoodsInfoView, UIGoodsInfoCtrl, UIGoodsInfoProxy);
		register(ViewID.UIMainView, UIMainView, UIMainCtrl, UIMainProxy);
		register(ViewID.UIPlayerInfoView, UIPlayerInfoView, UIPlayerInfoCtrl, UIPlayerInfoProxy);
		register(ViewID.UISectView, UISectView, UISectCtrl, UISectProxy);
		register(ViewID.UISettingView, UISettingView, UISettingCtrl, UISettingProxy);
		register(ViewID.UISphereToolView, UISphereToolView, UISphereToolCtrl, UISphereToolProxy);
	}
}
export const viewRegister = new ViewRegister();