/**The script is automatically generated by BatMain.bat , please do not modify */
export const enum ViewID {
	/**Coms */
	ComNumInputView = "ComNumInputView",
	ComTipInfoView = "ComTipInfoView",
	ComDongFuView = "ComDongFuView",
	ComItemInfoView = "ComItemInfoView",
	ComJueSeView = "ComJueSeView",
	ComLiLianView = "ComLiLianView",
	ComRenWuView = "ComRenWuView",
	ComShangChengView = "ComShangChengView",
	ComSkillView = "ComSkillView",
	ComWuPinView = "ComWuPinView",
	ComXinFaView = "ComXinFaView",
	ComZhiZuoView = "ComZhiZuoView",

	/**Views */
	UIBattleView = "BattleView",
	UIChooseBattleView = "ChooseBattleView",
	UILoading1View = "Loading1View",
	UILoading2View = "Loading2View",
	UITipConfirmView = "TipConfirmView",
	UIWaitingView = "WaitingView",
	UILoginMainView = "LoginMainView",
	UIChatView = "ChatView",
	UIEquipmentInfoView = "EquipmentInfoView",
	UIMainView = "MainView",
	UIPlayerInfoView = "PlayerInfoView",
	UISectView = "SectView",
	UISettingView = "SettingView",
	UISphereToolView = "SphereToolView",
}