/**The script is automatically generated by BatMain.bat , please do not modify */
export const enum ViewID {
	/**Btns */
	BtnUpgrade1View = "BtnUpgrade1View",
	BtnUpgrade2View = "BtnUpgrade2View",
	BtnMainSkillView = "BtnMainSkillView",
	BtnMainView = "BtnMainView",

	/**Renders */
	RenderClickFactionView = "RenderClickFactionView",
	RenderFactionView = "RenderFactionView",
	RenderPuppetView = "RenderPuppetView",

	/**Coms */
	ComConfirmView = "ComConfirmView",
	ComRedDotView = "ComRedDotView",
	ComTipInfoView = "ComTipInfoView",
	ComBattleContainerView = "ComBattleContainerView",
	ComBattleView = "ComBattleView",
	ComFactionInfoView = "ComFactionInfoView",
	ComFactionView = "ComFactionView",
	ComHurtFloatView = "ComHurtFloatView",
	ComOfflineView = "ComOfflineView",
	ComPuppetView = "ComPuppetView",
	ComRebirthItemView = "ComRebirthItemView",
	ComRebirthView = "ComRebirthView",
	ComShopItem1View = "ComShopItem1View",
	ComShopItem2View = "ComShopItem2View",
	ComShopItem3View = "ComShopItem3View",
	ComShopItem4View = "ComShopItem4View",
	ComShopView = "ComShopView",
	ComSoulFloatView = "ComSoulFloatView",
	ComTechnologyView = "ComTechnologyView",

	/**UIs */
	UIConfirmView = "UIConfirmView",
	UILoginView = "UILoginView",
	UIFactionInfoView = "UIFactionInfoView",
	UIGMView = "UIGMView",
	UIMainView = "UIMainView",
	UIOfflineView = "UIOfflineView",
	UIRecordView = "UIRecordView",
}