---The file is automatically generated by proto_declare.js , please do not modify

---网络通知
Notify = {
	--- poker.auth request, count:2
	NotifyAnotherLogin = "NotifyAnotherLogin",
	NotifyAccountBanned = "NotifyAccountBanned",

	--- poker.game request, count:25
	NotifyGameStart = "NotifyGameStart",
	NotifyGameEnd = "NotifyGameEnd",
	NotifyGameTerminated = "NotifyGameTerminated",
	NotifyFight = "NotifyFight",
	NotifyStageStart = "NotifyStageStart",
	NotifyStageEnd = "NotifyStageEnd",
	NotifyDealCard = "NotifyDealCard",
	NotifyWaitCallLord = "NotifyWaitCallLord",
	NotifyCallLord = "NotifyCallLord",
	NotifyWaitGrabLord = "NotifyWaitGrabLord",
	NotifyGrabLord = "NotifyGrabLord",
	NotifyConfirmLandlord = "NotifyConfirmLandlord",
	NotifyWaitOpenHand = "NotifyWaitOpenHand",
	NotifyOpenHand = "NotifyOpenHand",
	NotifyWaitDiscard = "NotifyWaitDiscard",
	NotifyDiscard = "NotifyDiscard",
	NotifyWaitNewStage = "NotifyWaitNewStage",
	NotifyDelegate = "NotifyDelegate",
	NotifyAFK = "NotifyAFK",
	NotifyConnect = "NotifyConnect",
	NotifyEmoji = "NotifyEmoji",
	NotifyGameAction = "NotifyGameAction",
	NotifyVote = "NotifyVote",
	NotifyVoteResult = "NotifyVoteResult",
	NotifyDiscardError = "NotifyDiscardError",

	--- poker.lobby request, count:9
	NotifyAccountGameEnd = "NotifyAccountGameEnd",
	NotifyAccountUpdate = "NotifyAccountUpdate",
	NotifyFriendModify = "NotifyFriendModify",
	NotifyFriendState = "NotifyFriendState",
	NotifyFriendInfoUpdate = "NotifyFriendInfoUpdate",
	NotifyUpvote = "NotifyUpvote",
	NotifyChangePassword = "NotifyChangePassword",
	NotifyTestBroadcast = "NotifyTestBroadcast",
	NotifyKickoutOffline = "NotifyKickoutOffline",

	--- poker.match request, count:4
	NotifyUnifiedMatchTimeout = "NotifyUnifiedMatchTimeout",
	NotifyMatchCanceled = "NotifyMatchCanceled",
	NotifyMatchReset = "NotifyMatchReset",
	NotifyMatchSuccess = "NotifyMatchSuccess",

	--- poker.payment request, count:1
	NotifyPayResult = "NotifyPayResult",

	--- poker.room request, count:4
	NotifyRoomInvite = "NotifyRoomInvite",
	NotifyRoomKicked = "NotifyRoomKicked",
	NotifyRoomUpdate = "NotifyRoomUpdate",
	NotifyRoomEmoji = "NotifyRoomEmoji",
}

---网络请求协议
Request = {
	--- client request, count:0

	--- poker.auth request, count:9
	ResetPasswordEmail = "ResetPasswordEmail",
	ResetPassword = "ResetPassword",
	CheckUsername = "CheckUsername",
	CheckMail = "CheckMail",
	Oauth2Auth = "Oauth2Auth",
	OauthBindAccount = "OauthBindAccount",
	StartCancellation = "StartCancellation",
	CancelCancellation = "CancelCancellation",
	FetchAccountLevelInfo = "FetchAccountLevelInfo",

	--- poker.event request, count:0

	--- poker.game request, count:14
	FetchGameInfo = "FetchGameInfo",
	ConnectController = "ConnectController",
	ReadyToPlay = "ReadyToPlay",
	SyncGame = "SyncGame",
	FinishSync = "FinishSync",
	PlayerCallLord = "PlayerCallLord",
	PlayerGrabLord = "PlayerGrabLord",
	MasterOpenHand = "MasterOpenHand",
	PlayerDiscard = "PlayerDiscard",
	PlayNextStage = "PlayNextStage",
	Delegate = "Delegate",
	Emoji = "Emoji",
	AFK = "AFK",
	Vote = "Vote",

	--- poker.lobby request, count:98
	CreateNickname = "CreateNickname",
	ModifyNickname = "ModifyNickname",
	ModifyAvatarId = "ModifyAvatarId",
	ModifyTitleId = "ModifyTitleId",
	ModifyFrameId = "ModifyFrameId",
	SaveSkinGroup = "SaveSkinGroup",
	ChangeUsedSkinGroup = "ChangeUsedSkinGroup",
	ChangeMainCharacter = "ChangeMainCharacter",
	MakeCraft = "MakeCraft",
	FetchItemIdMap = "FetchItemIdMap",
	DebugButton = "DebugButton",
	FetchAccountBrief = "FetchAccountBrief",
	AddFriendRequest = "AddFriendRequest",
	ApplyFriendRequest = "ApplyFriendRequest",
	RemoveFriend = "RemoveFriend",
	QueryGame = "QueryGame",
	AuthGame = "AuthGame",
	FetchMailList = "FetchMailList",
	FetchMailDetail = "FetchMailDetail",
	ReadMail = "ReadMail",
	RecvMailAttachment = "RecvMailAttachment",
	DeleteMail = "DeleteMail",
	FetchDailyTaskList = "FetchDailyTaskList",
	ReceiveDailyTaskReward = "ReceiveDailyTaskReward",
	ReceiveSosCoin = "ReceiveSosCoin",
	ReadAnnouncement = "ReadAnnouncement",
	FetchAnnouncementList = "FetchAnnouncementList",
	BuyFromShop = "BuyFromShop",
	ExchangeFromShop = "ExchangeFromShop",
	FetchLeaderboard = "FetchLeaderboard",
	FetchFriendState = "FetchFriendState",
	DeleteSkinGroup = "DeleteSkinGroup",
	ReceiveCharacterLevelRewards = "ReceiveCharacterLevelRewards",
	FetchGameDevShuffles = "FetchGameDevShuffles",
	FetchActiveChest = "FetchActiveChest",
	FetchChest = "FetchChest",
	OpenChest = "OpenChest",
	FetchGiftBoxRewards = "FetchGiftBoxRewards",
	OpenGiftBox = "OpenGiftBox",
	FetchMatchStat = "FetchMatchStat",
	ReceiveSuiteReward = "ReceiveSuiteReward",
	FetchSeasonInfo = "FetchSeasonInfo",
	ReceiveSeasonReward = "ReceiveSeasonReward",
	ConfirmSeason = "ConfirmSeason",
	FetchRecentGameRecordList = "FetchRecentGameRecordList",
	FetchFavoriteGameRecordList = "FetchFavoriteGameRecordList",
	FetchGameRecordDetail = "FetchGameRecordDetail",
	AddFavoriteGameRecord = "AddFavoriteGameRecord",
	RemoveFavoriteGameRecord = "RemoveFavoriteGameRecord",
	ShareGameRecord = "ShareGameRecord",
	FetchOBToken = "FetchOBToken",
	FetchGameLiveList = "FetchGameLiveList",
	Observe = "Observe",
	UserComplain = "UserComplain",
	FetchClientValue = "FetchClientValue",
	SetClientValue = "SetClientValue",
	DelClientValue = "DelClientValue",
	ReceiveAchievementReward = "ReceiveAchievementReward",
	ReceiveAchievementLevelReward = "ReceiveAchievementLevelReward",
	ReceiveGiftCodeReward = "ReceiveGiftCodeReward",
	PlayCharacterVoice = "PlayCharacterVoice",
	RecordFetchHeadImage = "RecordFetchHeadImage",
	RecordFetchBustImage = "RecordFetchBustImage",
	ModifyProfileBackground = "ModifyProfileBackground",
	ModifyAchievementPermission = "ModifyAchievementPermission",
	FetchAccountAllAchievement = "FetchAccountAllAchievement",
	Upvote = "Upvote",
	SaveDecoration = "SaveDecoration",
	UpdateSeason = "UpdateSeason",
	FetchServerTime = "FetchServerTime",
	ReceiveVipReward = "ReceiveVipReward",
	FetchAccountComment = "FetchAccountComment",
	ModifyCommentPermission = "ModifyCommentPermission",
	AddComment = "AddComment",
	DelComment = "DelComment",
	SaveQuickPhrase = "SaveQuickPhrase",
	DelQuickPhrase = "DelQuickPhrase",
	ReceiveMonthTicket = "ReceiveMonthTicket",
	ReceiveBattlePassReward = "ReceiveBattlePassReward",
	ReceiveBattlePassTaskReward = "ReceiveBattlePassTaskReward",
	ReceiveFreePackage = "ReceiveFreePackage",
	BindMailEmail = "BindMailEmail",
	BindMail = "BindMail",
	ReadGuide = "ReadGuide",
	ShieldEmoji = "ShieldEmoji",
	TryOn = "TryOn",
	FetchAccount = "FetchAccount",
	ActivityBianDangFetchCurrent = "ActivityBianDangFetchCurrent",
	ActivityBianDangSaveCurrent = "ActivityBianDangSaveCurrent",
	ActivityBianDangReceiveRewards = "ActivityBianDangReceiveRewards",
	ActivityBianDangOpenChest = "ActivityBianDangOpenChest",
	FetchActivityList = "FetchActivityList",
	FetchActivityTasks = "FetchActivityTasks",
	ReceiveActivityTaskReward = "ReceiveActivityTaskReward",
	ActivityQianDaoFetchCurrent = "ActivityQianDaoFetchCurrent",
	ActivityQianDaoReceiveRewards = "ActivityQianDaoReceiveRewards",
	ModifySeasonStatisticPermission = "ModifySeasonStatisticPermission",
	GetValidPaymentPlatform = "GetValidPaymentPlatform",

	--- poker.match request, count:2
	StartUnifiedMatch = "StartUnifiedMatch",
	CancelUnifiedMatch = "CancelUnifiedMatch",

	--- poker.payment request, count:13
	CreateSandboxOrder = "CreateSandboxOrder",
	ResolveSandboxOrder = "ResolveSandboxOrder",
	ResolveUnfilledOrder = "ResolveUnfilledOrder",
	CreateXsollaOrder = "CreateXsollaOrder",
	CreateMycardOrder = "CreateMycardOrder",
	QueryOrder = "QueryOrder",
	CreateAppleOrder = "CreateAppleOrder",
	CheckAppleOrder = "CheckAppleOrder",
	FetchSteamLocation = "FetchSteamLocation",
	CreateSteamOrder = "CreateSteamOrder",
	CheckSteamOrder = "CheckSteamOrder",
	CreateGoogleOrder = "CreateGoogleOrder",
	CheckGoogleOrder = "CheckGoogleOrder",

	--- poker.room request, count:16
	CreateRoom = "CreateRoom",
	LeaveRoom = "LeaveRoom",
	JoinRoom = "JoinRoom",
	AddRoomRobot = "AddRoomRobot",
	UpdateRoomRule = "UpdateRoomRule",
	UpdateRoomSeat = "UpdateRoomSeat",
	MemberLoadEnd = "MemberLoadEnd",
	PlayerReady = "PlayerReady",
	OpenHand = "OpenHand",
	StartGame = "StartGame",
	SetRoomOwner = "SetRoomOwner",
	KickRoomMember = "KickRoomMember",
	ChangeRoomOwner = "ChangeRoomOwner",
	InviteFriendToRoom = "InviteFriendToRoom",
	RoomEmoji = "RoomEmoji",
	FetchRoomInfo = "FetchRoomInfo",

	--- poker.share request, count:0

	--- poker.trigger request, count:0

	--- server request, count:0
}

---以下是  common 协议结构，一共 2 个
---@class IResponse
---@field error any

---@class ISkinItem
---@field type number
---@field res_id number

---以下是  client 协议结构，一共 0 个
---以下是  poker.auth 协议结构，一共 28 个
---@class IReqVerifyEmail
---@field email string

---@class IResVerifyEmail: IResponse
---@field token string

---@class IReqResetPasswordEmail
---@field email string
---@field validation string

---@class IResResetPasswordEmail: IResponse
---@field token string

---@class IReqResetPassword
---@field token string
---@field password string
---@field code string

---@class IReqAuthUsername
---@field username string
---@field email string
---@field password string
---@field type number

---@class IResAuthUsername: IResponse
---@field token string

---@class IReqAuthToken
---@field token string

---@class IResAuthToken: IResponse

---@class IReqLogin
---@field token string
---@field client_user_info IClientUserInfo
---@field login_type number

---@class IAccountOauth
---@field oauth_type number

---@class IDebtOrder
---@field goods_id number
---@field order_id string
---@field time number

---@class IReqSignup
---@field token string
---@field password string
---@field type number
---@field code string
---@field client_user_info IClientUserInfo
---@field username string
---@field oauth_type number
---@field oauth_code string

---@class IReqLogout

---@class IReqCheckUsername
---@field username string

---@class IResCheckUsername: IResponse
---@field available boolean

---@class IReqCheckMail
---@field email string

---@class IResCheckMail: IResponse
---@field available boolean

---@class INotifyAnotherLogin
---@field target_ip string

---@class INotifyAccountBanned
---@field ban_time number
---@field reason string

---@class IReqOauth2Auth
---@field oauth_type number
---@field code string

---@class IResOauth2Auth: IResponse
---@field token string
---@field has_account boolean

---@class IReqOauthBindAccount
---@field oauth_type number
---@field code string
---@field token string

---@class IResStartCancellation: IResponse
---@field cancel_time number

---@class IReqCancelCancellation
---@field token string

---@class IReqFetchAccountLevelInfo
---@field token string

---@class IResFetchAccountLevelInfo: IResponse
---@field account_id number
---@field nickname string
---@field levels IAccountLevel[]

---@class IResLogin: IResponse
---@field account_id number
---@field nickname string
---@field avatar_id number
---@field title_id number
---@field frame_id number
---@field avatar_png string
---@field username string
---@field binded_mail string
---@field mail_valid boolean
---@field need_bind_email number
---@field oauth IAccountOauth[]
---@field freeze_state number
---@field freeze_end_time number
---@field debt_orders IDebtOrder[]
---@field levels IAccountLevel[]
---@field character IAccountCharacter
---@field bag IAccountBag
---@field friend IAccountFriend
---@field mail IAccountMail
---@field daily_task IAccountDailyTask
---@field misc IAccountMisc
---@field achievement IAccountAchievement
---@field setting IAccountSetting
---@field mall IAccountMall
---@field decoration IAccountDecoration
---@field battle_pass IAccountBattlePass
---@field free_packages IAccountFreePackage[]
---@field season IAccountSeason
---@field last_modify_nickname_time number
---@field session_id number

---以下是  poker.event 协议结构，一共 25 个
---@class IGameRecord
---@field version number
---@field uuid string
---@field create_time number
---@field finish_time number
---@field finish_scene number
---@field category number
---@field meta IGameMeta
---@field rule IGameRule
---@field players IPlayerSnapshot[]
---@field events number[][]
---@field season_id number
---@field setting IPlayRuleSetting

---@class IEvent
---@field id number
---@field time number
---@field buffer number[]

---@class IEventBeginGame

---@class IEventEndGame

---@class IEventBeginStage
---@field stage number
---@field stage_start_players IPlayerStageStartSnap[]
---@field multiple IMultiple
---@field effects IGameEffect[]

---@class IEventEndStage
---@field result IStageResult
---@field effects IGameEffect[]

---@class IEventConnect
---@field seat number
---@field connect number
---@field ready number
---@field game_state number

---@class IEventDealCard
---@field deal_cards number[]
---@field river number[]
---@field call_seat number
---@field deal_card_players IPlayerStageStartSnap[]
---@field deal_setting IDealSetting
---@field tian_laizi number[]

---@class IEventWaitCall
---@field seat number

---@class IEventDoCall
---@field seat number
---@field call number
---@field duration number

---@class IEventWaitGrab
---@field seat number

---@class IEventDoGrab
---@field seat number
---@field grab number
---@field duration number
---@field multiple IMultiple
---@field effects IGameEffect[]

---@class IEventConfirm
---@field seat number
---@field river number[]
---@field di_laizi number[]

---@class IEventWaitDiscard
---@field seat number
---@field last_union ICardUnion
---@field thinking_time number

---@class IEventDoDiscard
---@field seat number
---@field discard number
---@field union ICardUnion
---@field multiple IMultiple
---@field remain number
---@field duration number
---@field effects IGameEffect[]
---@field time_out boolean

---@class IEventWaitOpenHand
---@field seat number

---@class IEventOpenHand
---@field seat number
---@field hand number[]
---@field multiple IMultiple
---@field effects IGameEffect[]

---@class IEventDelegate
---@field seat number
---@field delegate number

---@class IEventWaitStage

---@class IEventEmoji
---@field seat number
---@field type number
---@field emoji number
---@field phrase_id number

---@class IEventAFK
---@field seat number
---@field afk number

---@class IEventFight

---@class IEventVote
---@field seat number
---@field initiate boolean
---@field agree boolean

---@class IEventVoteResult
---@field result boolean

---@class IEventDiscardError
---@field error_seq number
---@field error_message string
---@field union ICardUnion

---以下是  poker.game 协议结构，一共 41 个
---@class IResFetchGameInfo: IResponse
---@field setting IPlayRuleSetting
---@field meta IGameMeta
---@field accounts IPlayerSnapshot[]
---@field game_state number
---@field uuid string
---@field create_time number

---@class IResReadyToPlay: IResponse
---@field game_state number

---@class IReqSyncGame
---@field step number

---@class IResSyncGame: IResponse
---@field is_end boolean
---@field game_restore IGameRestore

---@class IReqCallLord
---@field call boolean
---@field duration number

---@class IReqGrabLord
---@field grab boolean
---@field duration number

---@class IReqMasterOpenHand
---@field open boolean
---@field union ICardUnion
---@field duration number

---@class IReqDiscard
---@field discard boolean
---@field union ICardUnion
---@field duration number
---@field discard_event_id number

---@class IReqPlayNextStage
---@field open boolean
---@field duration number

---@class IReqDelegate
---@field delegate boolean

---@class IReqEmoji
---@field type number
---@field emoji number
---@field phrase_id number

---@class IReqAFK
---@field afk boolean

---@class IPlayerStageStart
---@field seat number
---@field open_hand boolean

---@class IDealCardSeat
---@field seat number
---@field count number
---@field cards number[]

---@class INotifyGameStart
---@field uuid string
---@field time number

---@class INotifyGameEnd

---@class INotifyGameTerminated

---@class INotifyFight

---@class INotifyStageStart
---@field current_stage number
---@field players IPlayerStageStart[]
---@field multiple IMultiple
---@field effects IGameEffect[]

---@class INotifyStageEnd
---@field winner number
---@field winner_camp number
---@field is_spring boolean
---@field stage_end_players IPlayerStageEndSnap[]
---@field multiple IMultiple
---@field effects IGameEffect[]

---@class INotifyDealCard
---@field seats IDealCardSeat[]
---@field call_seat number
---@field tian_laizi_point number

---@class INotifyWaitCallLord
---@field seat number
---@field timeout number

---@class INotifyCallLord
---@field seat number
---@field call boolean

---@class INotifyWaitGrabLord
---@field seat number
---@field timeout number

---@class INotifyGrabLord
---@field seat number
---@field grab boolean
---@field multiple IMultiple
---@field effects IGameEffect[]

---@class INotifyConfirmLandlord
---@field seat number
---@field river number[]
---@field di_laizi_point number

---@class INotifyWaitOpenHand
---@field seat number
---@field timeout number

---@class INotifyOpenHand
---@field seat number
---@field open boolean
---@field cards number[]
---@field multiple IMultiple
---@field effects IGameEffect[]

---@class INotifyWaitDiscard
---@field seat number
---@field timeout number
---@field last_union ICardUnion

---@class INotifyDiscard
---@field seat number
---@field discard boolean
---@field union ICardUnion
---@field multiple IMultiple
---@field remain_count number
---@field effects IGameEffect[]

---@class INotifyWaitNewStage

---@class INotifyDelegate
---@field seat number
---@field delegate boolean

---@class INotifyAFK
---@field seat number
---@field afk boolean

---@class INotifyConnect
---@field seat number
---@field connect boolean
---@field ready number
---@field game_state number

---@class INotifyEmoji
---@field seat number
---@field type number
---@field emoji number
---@field phrase_id number

---@class IGameRestore
---@field actions number[][]

---@class INotifyGameAction
---@field seq number
---@field time number
---@field name string
---@field data number[]
---@field bucket number
---@field uuid string

---@class IReqVote
---@field initiate boolean
---@field agree boolean

---@class INotifyVote
---@field seat number
---@field initiate boolean
---@field agree boolean

---@class INotifyVoteResult
---@field result boolean

---@class INotifyDiscardError
---@field error_seq number
---@field error_message string

---以下是  poker.lobby 协议结构，一共 188 个
---@class IReqReceiveAchievementReward
---@field achievement_id number

---@class IResReceiveAchievementReward: IResponse
---@field rewards IItem[]

---@class IReqReceiveAchievementLevelReward
---@field level number
---@field all number

---@class IResReceiveAchievementLevelReward: IResponse
---@field rewards IItem[]

---@class IAccountLevelCompute
---@field id number
---@field score number

---@class IAccountLevelChange
---@field type number
---@field origin IAccountLevelCompute
---@field final IAccountLevelCompute
---@field reason number

---@class IAccountLevelModify
---@field season_id number
---@field game_score_modify number
---@field extra_score_modify number
---@field origin IAccountLevel
---@field final IAccountLevel
---@field changes IAccountLevelChange[]

---@class INotifyAccountGameEnd
---@field level_modify IAccountLevelModify
---@field character_exp_modify number
---@field character_final_exp number
---@field chest_progress IGameChestProgressUpdate
---@field origin_gold number
---@field modify_gold number
---@field tips_gold number
---@field uuid string
---@field game_create_time number
---@field game_end_time number
---@field settlement_end_time number

---@class IReqMakeCraft
---@field id number

---@class IIdData
---@field number_id number
---@field string_id string

---@class IReqChangeMainCharacter
---@field character_id number

---@class IResChangeMainCharacter: IResponse
---@field head_image_state number
---@field avatar_png string
---@field bust_image_state number
---@field bust_png string

---@class IReqChangeUsedSkinGroup
---@field character_id number
---@field group_id number

---@class IResChangeUsedSkinGroup: IResponse
---@field head_image_state number
---@field avatar_png string
---@field bust_image_state number
---@field bust_png string

---@class IReqCreateNickname
---@field nickname string

---@class IReqModifyNickname
---@field nickname string
---@field use_item_id string

---@class IReqModifyAvatarId
---@field avatar_id number

---@class IReqModifyTitleId
---@field title_id number

---@class IReqModifyFrameId
---@field frame_id number

---@class INotifyAccountUpdate
---@field update IAccountUpdate

---@class IAccountLevelUpdate
---@field levels IAccountLevel[]

---@class IAccountResourceUpdate
---@field id number
---@field final number
---@field update_time number

---@class IAccountBasicUpdate
---@field nickname string
---@field avatar_id number
---@field title_id number
---@field frame_id number
---@field avatar_png string
---@field likes number
---@field ban_state number
---@field binded_mail string
---@field mail_valid boolean
---@field bust_png string

---@class IAccountFriendUpdate
---@field friend number[]
---@field apply_request IAccountFriendRequest[]

---@class IAccountMailUpdate
---@field mails IMail[]

---@class IAccountDailyTaskUpdate
---@field progresses IBaseTaskProgress[]

---@class IAccountAchievementUpdate
---@field achievement_progresses IAchievementProgress[]
---@field level_progresses IAchievementLevelProgress[]

---@class IAccountSettingUpdate
---@field achievement_permission number
---@field comment_permission number
---@field brief_season_permission number

---@class IAccountMiscUpdate
---@field sos_coin ISosCoinData[]
---@field shop_record IShopRecord[]
---@field pickup_record IPickupRecord[]

---@class IAccountCharacterUpdate
---@field character_id number
---@field exp number
---@field rewarded_levels number[]

---@class IAccountCharacterSkinUpdate
---@field character_id number
---@field current_skin_group number
---@field skin_groups ICharacterSkinGroup[]

---@class IAccountMainCharacterUpdate
---@field character_id number

---@class IAccountRewardedSuiteUpdate
---@field rewarded_suites number[]

---@class IAccountSeasonStatisticUpdate
---@field season_statistics IAccountSeasonStatistic[]

---@class IAccountMallUpdate
---@field accumulate_value number
---@field vip number
---@field received_vip_rewards number[]
---@field currency IGoodsRecord[]
---@field package IGoodsRecord[]
---@field month_ticket IGoodsRecord[]

---@class IAccountQuickPhraseUpdate
---@field character_id number
---@field quick_phrase IQuickPhrase

---@class IAccountDecorationUpdate
---@field lobby_background number
---@field game_background number
---@field effects IEffectGroup
---@field card_faces ICardFaceGroup

---@class IAccountBattlePassUpdate
---@field battle_pass_id number
---@field paid_version number
---@field level number
---@field exp number
---@field week_exp number
---@field rewards IAccountBattlePassRewards
---@field tasks IAccountBattlePassTask[]

---@class IAccountUpdate
---@field basic IAccountBasicUpdate
---@field level IAccountLevelUpdate
---@field resource_updates IAccountResourceUpdate[]
---@field friend IAccountFriendUpdate
---@field mail IAccountMailUpdate
---@field daily_task IAccountDailyTaskUpdate
---@field misc IAccountMiscUpdate
---@field character IAccountCharacterUpdate[]
---@field character_skin IAccountCharacterSkinUpdate[]
---@field main_character IAccountMainCharacterUpdate
---@field rewarded_suite IAccountRewardedSuiteUpdate
---@field achievement IAccountAchievementUpdate
---@field setting IAccountSettingUpdate
---@field season_statistic IAccountSeasonStatisticUpdate
---@field mall IAccountMallUpdate
---@field quick_phrase IAccountQuickPhraseUpdate[]
---@field decoration IAccountDecorationUpdate
---@field battle_pass IAccountBattlePassUpdate
---@field free_packages IAccountFreePackage[]
---@field activity_tasks IActivityTask[]
---@field season_rewards IAccountSeasonRewards[]

---@class IReqFetchAccountBrief
---@field accounts number[]
---@field level number

---@class IResFetchAccountBrief: IResponse
---@field briefs IBytesBrief[]

---@class IBytesBrief
---@field basic_brief number[]
---@field season_summaries number[]

---@class IReqAddFriendRequest
---@field account_id number

---@class IReqApplyFriendRequest
---@field account_id_list number[]
---@field result number
---@field type number

---@class IResApplyFriendRequest: IResponse
---@field success_list number[]
---@field state number

---@class IReqRemoveFriend
---@field account_id number

---@class INotifyFriendModify
---@field new_friend number
---@field removed_friend number

---@class IResQueryGame: IResponse
---@field in_gaming boolean

---@class IResAuthGame: IResponse

---@class IResFetchMailList: IResponse
---@field mails IAccountMail

---@class IReqFetchMailDetail
---@field mail_id_list number[]

---@class IResFetchMailDetail: IResponse
---@field detail IMailDetail[]

---@class IReqReadMail
---@field mail_id number

---@class IReqRecvMailAttachment
---@field mail_list number[]

---@class IResRecvMailAttachment: IResponse
---@field items IItem[]

---@class IReqDeleteMail
---@field mail_list number[]

---@class IResFetchDailyTaskList: IResponse
---@field progresses IAccountDailyTask

---@class IReqReceiveDailyTaskReward
---@field task_id number
---@field all number

---@class IResReceiveDailyTaskReward: IResponse
---@field rewards IItem[]

---@class IReqReceiveSosCoin
---@field id number

---@class IResReceiveSosCoin: IResponse
---@field rewards IItem[]

---@class IReqReadAnnouncement
---@field id number

---@class IResFetchAnnouncementList: IResponse
---@field ann IAnnouncement[]

---@class IReqBuyFromShop
---@field id number
---@field count number

---@class IResBuyFromShop: IResponse
---@field items IItem[]
---@field skin_groups ISkinGroup[]

---@class IReqExchangeFromShop
---@field rule_id number
---@field items IItem[]

---@class IResExchangeFromShop: IResponse
---@field items IItem[]

---@class IReqFetchLeaderboard
---@field offset number
---@field category number

---@class IResFetchLeaderboard: IResponse
---@field account_list number[]
---@field self_rank number

---@class INotifyFriendState
---@field friend IAccountOnlineState

---@class INotifyFriendInfoUpdate
---@field account_id number

---@class IReqFetchFriendState
---@field accounts number[]

---@class IResFetchFriendState: IResponse
---@field friends IAccountOnlineState[]

---@class IReqDeleteSkinGroup
---@field group_id number
---@field character_id number

---@class IResDeleteSkinGroup: IResponse
---@field current_use_group_id number

---@class IReqReceiveCharacterLevelRewards
---@field level_list number[]
---@field character_id number

---@class IResReceiveCharacterLevelRewards: IResponse
---@field rewards IItem[]

---@class IResFetchGameDevShuffles: IResponse
---@field shuffles IGameDevShuffle[]

---@class IReqFetchActiveChest
---@field version number

---@class IChestData
---@field chest_id number
---@field end_time number

---@class IReqFetchChest
---@field chest_id number

---@class IResFetchChest: IResponse
---@field use_new boolean
---@field pickup_items number[]
---@field next_double number

---@class IReqOpenChest
---@field chest_id number
---@field count number
---@field ticket_id number
---@field ticket_count number
---@field pickup_items_hash string

---@class ISkinGroup
---@field skins IItem[]

---@class IResOpenChest: IResponse
---@field rewards IItem[]
---@field skin_groups ISkinGroup[]
---@field shop_currency_id number
---@field shop_currency_num number

---@class IReqFetchGiftBoxRewards
---@field res_id number

---@class IResFetchGiftBoxRewards: IResponse
---@field rewards IItem[]

---@class IReqOpenGiftBox
---@field res_id number
---@field count number

---@class IResOpenGiftBox: IResponse
---@field rewards IItem[]

---@class IAccountSeasonResult
---@field season_id number
---@field start_time number
---@field end_time number
---@field level_id number
---@field season_type number
---@field season_state number
---@field confirm_state number
---@field receive_state number
---@field template_id number

---@class IReqFetchSeasonInfo

---@class IResFetchSeasonInfo: IResponse
---@field seasons IAccountSeasonResult[]

---@class IReqReceiveSeasonReward
---@field season_id number
---@field reward_id number

---@class IResReceiveSeasonReward: IResponse
---@field rewards IItem[]

---@class IReqConfirmSeason
---@field season_id number

---@class IResConfirmSeason: IResponse

---@class IReqFetchMatchStat
---@field match_id_list number[]

---@class IMatchData
---@field match_id number
---@field count number

---@class IAccountGameRecord
---@field uuid string
---@field number number
---@field camp number
---@field win boolean
---@field start_time number
---@field end_time number
---@field open_hand boolean
---@field play_mode number
---@field match_id number
---@field category number
---@field Multiple number
---@field currency number

---@class IReqRecentGameRecordList

---@class IResRecentGameRecordList: IResponse
---@field records IAccountGameRecord[]

---@class IReqFavoriteGameRecordList

---@class IResFavoriteGameRecordList: IResponse
---@field records IAccountGameRecord[]

---@class IReqGameRecordDetail
---@field uuid string
---@field number number
---@field account_id number

---@class IResGameRecordDetail: IResponse
---@field data number[]

---@class IReqAddFavoriteGameRecord
---@field uuid string
---@field number number

---@class IReqDeleteFavoriteGameRecord
---@field uuid string
---@field number number

---@class IReqShareGameRecord
---@field uuid string
---@field number number

---@class IReqFetchOBToken
---@field uuid string

---@class IResFetchOBToken: IResponse
---@field token string
---@field create_time number
---@field delay number
---@field start_time number

---@class IReqFetchGameLiveList
---@field filter_id number

---@class IReqObserve
---@field uuid string

---@class IGameConfig
---@field category number
---@field meta IGameMeta
---@field rule IGameRule

---@class IResFetchGameLiveList: IResponse
---@field game_list IGameLiveHead[]

---@class IReqUserComplain
---@field target_id number
---@field type number

---@class IReqFetchClientValue
---@field key string

---@class IClientValue
---@field key string
---@field value string

---@class IReqSetClientValue
---@field key string
---@field value string

---@class IReqDelClientValue
---@field keys string[]

---@class IReqReceiveSuiteReward
---@field suite_id number

---@class IResReceiveSuiteReward: IResponse
---@field rewards IItem[]

---@class IReqReceiveGiftCodeReward
---@field code string

---@class IResReceiveGiftCodeReward: IResponse
---@field rewards IItem[]

---@class IReqPlayCharacterVoice
---@field character_id number
---@field voice_id number

---@class IResSaveSkinGroup: IResponse
---@field head_image_state number
---@field avatar_png string
---@field bust_image_state number
---@field bust_png string

---@class IReqRecordFetchHeadImage
---@field target_id number
---@field target_png string

---@class IResRecordFetchHeadImage: IResponse
---@field newest_png string

---@class IReqRecordFetchBustImage
---@field target_id number
---@field target_png string

---@class IResRecordFetchBustImage: IResponse
---@field newest_png string

---@class IReqModifyAchievementPermission
---@field achievement_permission number

---@class IReqFetchAccountAllAchievement
---@field account_id number

---@class IResFetchAccountAllAchievement: IResponse
---@field account_achievement IAccountAchievement

---@class IReqUpvote
---@field target_id number
---@field uuid string

---@class INotifyUpvote
---@field target_id number
---@field uuid string
---@field source_id number

---@class INotifyChangePassword

---@class IReqUpdateSeason

---@class IReqFetchServerTime

---@class IResFetchServerTime: IResponse
---@field time number

---@class IReqReceiveVipReward
---@field vip number

---@class IResReceiveVipReward: IResponse
---@field rewards IItem[]

---@class IReqFetchAccountComment
---@field account_id number

---@class IResFetchAccountComment: IResponse
---@field permission number
---@field comments IComment[]

---@class IReqAddComment
---@field target_id number
---@field comment IWordStock
---@field emo_id number

---@class IReqDelComment
---@field auto_id number[]

---@class IReqModifyCommentPermission
---@field permission number

---@class IReqSaveQuickPhrase
---@field chara_id number
---@field phrase_id number
---@field quick_phrase IWordStock

---@class IReqDelQuickPhrase
---@field chara_id number
---@field phrase_id number

---@class IReqModifyProfileBackground
---@field res_id number

---@class IReqSaveDecoration
---@field save_type number
---@field lobby_background number
---@field game_background number
---@field effects IEffectGroup
---@field card_faces ICardFaceGroup

---@class IReqReceiveBattlePassReward
---@field levels number[]

---@class IResReceiveBattlePassReward: IResponse
---@field rewards IItem[]

---@class IReqReceiveBattlePassTaskReward
---@field task_id number
---@field all number

---@class IResReceiveBattlePassTaskReward: IResponse
---@field rewards IItem[]

---@class IReqReceiveFreePackage
---@field id number

---@class IResReceiveFreePackage: IResponse
---@field rewards IItem[]

---@class INotifyTestBroadcast
---@field Content string

---@class IReqBindMailEmail
---@field email string

---@class IResBindMailEmail: IResponse
---@field token string

---@class IReqBindMail
---@field token string
---@field code string
---@field password string

---@class INotifyKickoutOffline
---@field reason number
---@field force boolean

---@class IReqReadGuide

---@class IReqFetchAccount
---@field type number[]

---@class IResFetchAccount: IResponse
---@field bag IAccountBag
---@field mall IAccountMall

---@class IActivityBianDangFood
---@field id number
---@field location_x number
---@field location_y number

---@class IResActivityBianDangFetchCurrent: IResponse
---@field table_id number
---@field foods IActivityBianDangFood[]
---@field received number[]

---@class IResActivityBianDangReceiveRewards: IResponse
---@field rewards IItem[]

---@class IReqActivityBianDangSaveCurrent
---@field table_id number
---@field foods IActivityBianDangFood[]

---@class IResActivityBianDangOpenChest: IResponse
---@field rewards IItem[]

---@class IActivityTask
---@field id number
---@field activity_id number
---@field progress number
---@field achieved number
---@field rewarded number

---@class IResFetchActivityTasks: IResponse
---@field tasks IActivityTask[]

---@class IReqReceiveActivityTaskReward
---@field id number

---@class IResReceiveActivityTaskReward: IResponse
---@field rewards IItem[]

---@class IActivity
---@field id number
---@field start_time number
---@field end_time number

---@class IResFetchActivityList: IResponse
---@field activities IActivity[]

---@class IReqActivityBianDangReceiveRewards
---@field table_id number

---@class IReqActivityQianDaoFetchCurrent
---@field activity_id number

---@class IResActivityQianDaoFetchCurrent: IResponse
---@field day number
---@field last_receive_time number

---@class IReqActivityQianDaoReceiveRewards
---@field activity_id number

---@class IResActivityQianDaoReceiveRewards: IResponse
---@field rewards IItem[]

---@class IReqModifySeasonStatisticPermission
---@field permission number

---@class IResGetValidPaymentPlatform: IResponse
---@field platforms IPaymentPlatformConfig[]

---@class IResFetchItemIdMap: IResponse
---@field id_map IIdData[]

---@class IReqSaveSkinGroup
---@field character_id number
---@field group_id number
---@field items ISkinItem[]
---@field name string

---@class IResFetchActiveChest: IResponse
---@field chests IChestData[]

---@class IResFetchMatchStat: IResponse
---@field matches IMatchData[]

---@class IGameLiveHead
---@field uuid string
---@field start_time number
---@field players IPlayerSnapshot[]
---@field game_config IGameConfig

---@class IResFetchClientValue: IResponse
---@field values IClientValue[]

---@class IReqTryOn
---@field character_id number
---@field items ISkinItem[]

---以下是  poker.match 协议结构，一共 6 个
---@class INotifyUnifiedMatchTimeout
---@field sid string

---@class INotifyMatchCanceled
---@field sid string

---@class INotifyMatchReset
---@field sid string

---@class INotifyMatchSuccess
---@field sid string

---@class IReqStartUnifiedMatch
---@field sid string
---@field open_hands number

---@class IReqCancelUnifiedMatch
---@field sid string

---以下是  poker.payment 协议结构，一共 25 个
---@class IReqCreateSandboxOrder
---@field goods_id number
---@field debt_order_id string

---@class IResCreateSandboxOrder: IResponse
---@field order_id string

---@class IReqResolveSandboxOrder
---@field order_id string
---@field action string

---@class IResResolveSandboxOrder: IResponse

---@class IBattlePassLevel
---@field origin number
---@field final number

---@class IReqResolveUnfilledOrder
---@field action string

---@class IResResolveUnfilledOrder: IResponse

---@class IReqCreateXsollaOrder
---@field goods_id number
---@field debt_order_id string

---@class IResCreateXsollaOrder: IResponse
---@field order_id string
---@field url string

---@class IReqCreateMycardOrder
---@field goods_id number
---@field debt_order_id string

---@class IResCreateMycardOrder: IResponse
---@field order_id string
---@field url string
---@field auth_code string

---@class IReqQueryOrder
---@field order_id string

---@class IResQueryOrder: IResponse
---@field pay_result number
---@field rewards IItem[]

---@class IReqCreateAppleOrder
---@field goods_id number
---@field debt_order_id string

---@class IResCreateAppleOrder: IResponse
---@field order_id string

---@class IReqCheckAppleOrder
---@field order_id string
---@field transaction_id string
---@field receipt_data string

---@class IReqFetchSteamLocation
---@field steam_id number

---@class IResFetchSteamLocation: IResponse
---@field country string

---@class IReqCreateSteamOrder
---@field goods_id number
---@field language string
---@field steam_id number
---@field debt_order_id string

---@class IResCreateSteamOrder: IResponse
---@field order_id string

---@class IReqCheckSteamOrder
---@field order_id string

---@class IReqCreateGoogleOrder
---@field goods_id number
---@field debt_order_id string

---@class IResCreateGoogleOrder: IResponse
---@field order_id string

---@class IReqCheckGoogleOrder
---@field order_id string
---@field token string

---@class INotifyPayResult
---@field pay_status number
---@field order_id string
---@field goods_id number
---@field rewards IItem[]
---@field accumulate_value number
---@field level IBattlePassLevel
---@field debt_order_id string

---以下是  poker.room 协议结构，一共 25 个
---@class IRoomMemberState
---@field account_id number
---@field ready_state number
---@field open_hand number

---@class INotifyRoomInvite
---@field room_id number
---@field account_id number
---@field seat number

---@class INotifyRoomKicked

---@class INotifyRoomUpdate
---@field members IPlayerSnapshot[]
---@field setting IPlayRuleSetting
---@field owner_id number
---@field room_status IRoomStatus
---@field room_id number
---@field member_states IRoomMemberState[]

---@class IRoomStatus
---@field loaded_num number
---@field ready_num number

---@class IReqChangeRoomOwner
---@field account_id number

---@class IReqKickRoomMember
---@field seat number

---@class IReqSetRoomOwner
---@field seat number

---@class IReqPlayerReady
---@field ready_state number

---@class IReqOpenHand
---@field open_hand number

---@class IReqMemberLoadEnd
---@field account_id number

---@class IReqUpdateRoomRule
---@field setting IPlayRuleSetting

---@class IReqCreateRoom
---@field setting IPlayRuleSetting

---@class IResCreateRoom: IResponse
---@field room_id number
---@field owner IPlayerSnapshot

---@class IReqJoinRoom
---@field room_id number
---@field seat number

---@class IResJoinRoom: IResponse
---@field members IPlayerSnapshot[]
---@field setting IPlayRuleSetting
---@field owner_id number
---@field member_states IRoomMemberState[]
---@field room_status IRoomStatus
---@field room_id number

---@class IReqLeaveRoom

---@class IResLeaveRoom: IResponse

---@class IReqAddRoomRobot
---@field seat number

---@class IResAddRoomRobot: IResponse

---@class IReqInviteFriendToRoom
---@field account_id number
---@field seat number

---@class INotifyRoomEmoji
---@field account_id number
---@field type number
---@field emoji number
---@field phrase_id number

---@class IReqRoomEmoji
---@field type number
---@field emoji number
---@field phrase_id number

---@class IReqFetchRoomInfo

---@class IResFetchRoomInfo: IResponse
---@field room_id number
---@field members IPlayerSnapshot[]
---@field setting IPlayRuleSetting
---@field owner_id number
---@field room_status IRoomStatus
---@field member_states IRoomMemberState[]

---以下是  poker.share 协议结构，一共 79 个
---@class IClientUserInfo
---@field device_id string
---@field runtime_id string
---@field device string
---@field os string
---@field ip string
---@field channel string
---@field client_version string
---@field code string

---@class IAccountLevel
---@field type number
---@field id number
---@field score number
---@field season_id number
---@field extra number

---@class ISkinData
---@field type number
---@field res_id number

---@class ICharacterSkinGroup
---@field group_id number
---@field skin_items ISkinData[]
---@field name string
---@field create_time number

---@class ICharacterData
---@field character_id number
---@field current_skin_group number
---@field skin_groups ICharacterSkinGroup[]
---@field exp number
---@field rewarded_level number
---@field rewarded_levels number[]
---@field quick_phrase IQuickPhrase[]

---@class IAccountCharacter
---@field current_character_id number
---@field character ICharacterData[]
---@field rewarded_suites number[]

---@class IItemReplace
---@field replace_count number
---@field res_id number
---@field res_count number

---@class IItem
---@field res_id number
---@field res_count number
---@field replace IItemReplace[]
---@field update_time number

---@class IAccountBag
---@field items IItem[]

---@class IAccountFriend
---@field friend number[]
---@field apply_request IAccountFriendRequest[]

---@class IMail
---@field read_time number
---@field recv_attachment_time number
---@field mail_id number
---@field expire_time number
---@field create_time number

---@class IMailDetail
---@field title string
---@field content string
---@field attachments IItem[]
---@field mail_id number

---@class IAccountMail
---@field mails IMail[]

---@class IAccountDailyTask
---@field progresses IBaseTaskProgress[]

---@class IAccountAchievement
---@field achievement_progresses IAchievementProgress[]
---@field level_progresses IAchievementLevelProgress[]

---@class IAccountSetting
---@field achievement_permission number
---@field comment_permission number
---@field brief_season_permission number

---@class IEffectData
---@field type number
---@field res_id number

---@class ICardFaceData
---@field type number
---@field res_id number

---@class IEffectGroup
---@field group_id number
---@field effects IEffectData[]

---@class ICardFaceGroup
---@field group_id number
---@field card_faces ICardFaceData[]
---@field open_cutin boolean

---@class IAccountDecoration
---@field lobby_background number
---@field game_background number
---@field effect_main_group number
---@field effects IEffectGroup[]
---@field card_face_main_group number
---@field card_faces ICardFaceGroup[]

---@class ISosCoinData
---@field id number
---@field count number

---@class IShopRecord
---@field shop_id number
---@field count number

---@class IPickupRecord
---@field pickup_id number
---@field pickup_count number

---@class IAccountMisc
---@field sos_coin ISosCoinData[]
---@field read_ann_id number[]
---@field shop_record IShopRecord[]
---@field pickup_record IPickupRecord[]

---@class ICardSnapshot
---@field suit number
---@field points number

---@class IReqEmpty

---@class IResEmpty: IResponse

---@class IAccountBrief1
---@field account_id number
---@field nickname string
---@field avatar_id number
---@field title_id number
---@field levels IAccountLevel[]
---@field frame_id number
---@field avatar_png string
---@field likes number
---@field bust_png string

---@class ICharacterBrief
---@field id number
---@field skins ISkinData[]
---@field exp number

---@class IAccountBrief2
---@field brief1 IAccountBrief1
---@field character ICharacterBrief

---@class IGameSummary
---@field game_count number
---@field win_count number
---@field win_hand_count number
---@field recent_win number[]
---@field highest_mul number
---@field highest_win number
---@field discard_duration number
---@field positive_bean_sum number
---@field positive_bean_count number
---@field open_count number
---@field landlord_open_count number
---@field total_discard_count number
---@field landlord_count number
---@field landlord_win_count number
---@field farmer_count number
---@field farmer_win_count number
---@field teammate_complete_count number
---@field multiple_sum number
---@field shapes ICardShape[]
---@field spring_count number

---@class ICardShape
---@field type number
---@field count number

---@class IGameStatistic
---@field play_mode number
---@field summary IGameSummary
---@field recent_trend_list IRecentTrend[]

---@class ISeasonStatistic
---@field season_id number
---@field season_type number
---@field highest_level_id number
---@field highest_level_score number

---@class ICharacterGameCount
---@field character_id number
---@field count number

---@class ISeasonMatchSummary
---@field match_id number
---@field game_count number
---@field win_count number

---@class ISeasonSummaries
---@field season_summaries ISeasonSummary[]

---@class ISeasonSummary
---@field season_id number
---@field season_type number
---@field character_game_count ICharacterGameCount[]
---@field beat_count number
---@field total_time number
---@field tongbi_count number
---@field score_count number
---@field extra_score_count number
---@field highest_tongbi number
---@field cap_count number
---@field character_exp_count number
---@field tips_count number
---@field login_day_count number
---@field daily_task_count number
---@field sos_count number
---@field chest_count number
---@field match_summary ISeasonMatchSummary[]

---@class IRecentTrend
---@field lord boolean
---@field win boolean
---@field multiple number
---@field copper_top boolean

---@class IGoodsRecord
---@field goods_id number
---@field purchased_count number
---@field start_time number
---@field end_time number
---@field is_first_pay boolean
---@field wallet number
---@field last_receive_time number
---@field expire_time number

---@class IAccountMall
---@field accumulate_value number
---@field vip number
---@field received_vip_rewards number[]
---@field currency IGoodsRecord[]
---@field package IGoodsRecord[]
---@field month_ticket IGoodsRecord[]

---@class IAccountBrief3
---@field brief2 IAccountBrief2
---@field game_statistic IGameStatistic[]
---@field season_statistic ISeasonStatistic[]
---@field last_achieved_achievement_id number
---@field total_achieved_achievement_point number
---@field profile_background number
---@field season_permission number

---@class IAccountFriendRequest
---@field account_id number
---@field apply_time number

---@class IOptionalUint32
---@field ok boolean
---@field value number

---@class IOptionalString
---@field ok boolean
---@field value string

---@class IBaseTaskProgress
---@field task_id number
---@field counter number
---@field achieved number
---@field rewarded number

---@class IAchievementProgress
---@field achievement_id number
---@field counter number
---@field achieved number
---@field achieved_time number
---@field rewarded number

---@class IAchievementLevelProgress
---@field level number
---@field rewarded_time number

---@class IAnnouncement
---@field id number
---@field content string
---@field title string

---@class ILandlordPlaySetting
---@field stage_count number
---@field can_multiple number
---@field can_open_hands number
---@field max_point number
---@field game_mode number
---@field dev IDevPlaySetting

---@class IPlayRuleSetting
---@field rule number
---@field landlord ILandlordPlaySetting

---@class IPlayerSnapshot
---@field account_id number
---@field nickname string
---@field levels IAccountLevel[]
---@field open number
---@field character_id number
---@field skins ISkinData[]
---@field seat number
---@field currency number
---@field title_id number
---@field emoji number[]
---@field effects IEffectData[]
---@field quick_phrase IQuickPhrase[]
---@field card_faces ICardFaceData[]
---@field open_cutin boolean

---@class IPlayMeta
---@field room_id number
---@field match_id number

---@class IGameMeta
---@field room_id number
---@field match_id number

---@class IAccountPlayingGame
---@field uuid string
---@field category number
---@field meta IGameMeta

---@class IAccountRoomInfo
---@field room_id number

---@class IAccountOnlineState
---@field account_id number
---@field online boolean
---@field last_login_time number
---@field last_logout_time number
---@field playing IAccountPlayingGame
---@field room IAccountRoomInfo

---@class IGameDevShuffle
---@field shuffle_id number
---@field create_time number
---@field cards string
---@field title string
---@field description string

---@class IDevPlaySetting
---@field open_hand number
---@field open_river number
---@field shuffler_id number
---@field cheat_mode number

---@class IDealSetting
---@field open_hand number
---@field open_river number
---@field shuffler_id number

---@class IGameChestProgressUpdate
---@field chest_id number
---@field origin number
---@field final number
---@field is_graded boolean
---@field rewards IItem[]

---@class IMultiple
---@field initial number
---@field open_hand number[]
---@field grab_lord number[]
---@field boom number[]
---@field spring number

---@class ICardUnion
---@field type number
---@field primary number[]
---@field secondary number[]
---@field entity_primary number[]
---@field entity_secondary number[]

---@class IGameRule
---@field stage number
---@field player_count number
---@field multiple number
---@field open_hand number
---@field base_point number
---@field max_score number
---@field fight number
---@field shuffle_mode number
---@field ai_level number
---@field dev IDevPlaySetting
---@field tips number
---@field init_multi number
---@field features number[]

---@class IPlayerStageStartSnap
---@field seat number
---@field hand number[]
---@field open number
---@field open_start number
---@field camp number
---@field delegate number

---@class IPlayerStageEndSnap
---@field seat number
---@field camp number
---@field base_point number
---@field multiple number
---@field stage_score number
---@field fixed_score number
---@field total_score number
---@field hand number[]
---@field is_open number
---@field win number
---@field stage_currency number
---@field fixed_currency number
---@field win_stage number
---@field game_rule_fix_flag number
---@field player_debt_fix_flag number
---@field extra_score number

---@class IStageResult
---@field winner number
---@field winner_camp number
---@field is_spring number
---@field stage_end_players IPlayerStageEndSnap[]
---@field multiple IMultiple
---@field stage number

---@class IAccountSeasonStatistic
---@field type number
---@field id number
---@field score number
---@field season_id number

---@class IWordStock
---@field sentence_id number
---@field words_id number[]

---@class IComment
---@field auto_id number
---@field account_id number
---@field commentor number
---@field comment IWordStock
---@field emo_id number
---@field comment_time number

---@class IQuickPhrase
---@field phrase_id number
---@field quick_phrase IWordStock

---@class IAccountBattlePassRewards
---@field free_rewards number[]
---@field rewards number[]

---@class IAccountBattlePassTask
---@field task_id number
---@field progress number
---@field achieved boolean
---@field rewarded boolean

---@class IAccountBattlePass
---@field battle_pass_id number
---@field paid_version number
---@field level number
---@field exp number
---@field week_exp number
---@field rewards IAccountBattlePassRewards
---@field tasks IAccountBattlePassTask[]
---@field settle_time number

---@class IAccountFreePackage
---@field id number
---@field receive_count number
---@field last_receive_time number

---@class IAccountSeasonRewards
---@field season_id number
---@field received_rewards number[]

---@class IAccountSeason
---@field season_rewards IAccountSeasonRewards[]

---@class IPaymentPlatformConfig
---@field platform_id number
---@field open_payment number
---@field open_clear number

---以下是  poker.trigger 协议结构，一共 2 个
---@class IGameEffect
---@field id number
---@field buffer number[]

---@class IEffectExtraScoreChange
---@field origin number
---@field final number
---@field reason number

---以下是  server 协议结构，一共 0 个
