import { EquipmentPart } from "../enum/ItemEnum";

export const EquipmentsSign = "$equipments";

export const UserKeyMap: { [ key in keyof IUserData ]: string } = {
    uid: "uid",
    nickname: "nickname",
    account: "account",
    password: "password",
    registerTime: "registerTime",
    lastLoginTime: "lastLoginTime",
    lastOnlineTime: "lastOnlineTime",
    offline:"offline",
    coin: "coin",
    vcoin: "vcoin",
    vigor: "vigor",
    jingJie: "jingJie",
    cengJi: "cengJi",
    exp: "exp",
    moHe: "moHe",
    moBi: "moBi",
    spiritStones: "spiritStones",
    title: "title",
    society: "society",
    sect: "sect",
    soul: "soul",
    gemScore: "gemScore",
    weapon: "weapon",
    helmet: "helmet",
    necklace: "necklace",
    clothes: "clothes",
    ring: "ring",
    trousers: "trousers",
    amulet: "amulet",
    shoes: "shoes",
    mount: "mount",
    hiddenWeeapon: "hiddenWeeapon",
    fashion: "fashion",
    magicWeapon: "magicWeapon",
    weaponGems: "weaponGems",
    helmetGems: "helmetGems",
    necklaceGems: "necklaceGems",
    clothesGems: "clothesGems",
    ringGems: "ringGems",
    trousersGems: "trousersGems",
    amuletGems: "amuletGems",
    shoesGems: "shoesGems",
    level: "level",
    copy: "copy",
    secret: "secret",
    boss: "boss",
    citta: "citta",
    skill: "skill",
    usingSkill: "usingSkill",
    collect: "collect",
    equipment: "equipment",
    gem: "gem",
    prop: "prop",
    material: "material",
    book: "book",
    other: "other",
};

export const DressedEquipMap: { readonly [ key in EquipmentPart ]: string } = {
    1: "weapon",
    2: "helmet",
    3: "necklace",
    4: "clothes",
    5: "ring",
    6: "trousers",
    7: "amulet",
    8: "shoes",
    9: "mount",
    10: "fashion",
    11: "hiddenWeeapon",
    12: "magicWeapon"
};

export const BaseDataKeyMap: { [ key: string ]: string } = {
    1001: "coin",
    1002: "vcoin",
    1003: "exp",
    1004: "moHe",
    1005: "moBi",
    1006: "spiritStones",
    1007: "soul",
    1008: "gemScore",
    1009: "vigor",
}