/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigPropsData {
	/**id */
	readonly ID: number;
	readonly Rewards: BaseDropOutType[];
}

declare interface ConfigProps extends KeyMap<ConfigPropsData> {
	/**1百万金币 */
	readonly 2000: ConfigPropsData;
	/**1亿金币 */
	readonly 2001: ConfigPropsData;
	/**50元宝 */
	readonly 2002: ConfigPropsData;
	/**100元宝 */
	readonly 2003: ConfigPropsData;
	/**500元宝 */
	readonly 2004: ConfigPropsData;
	/**1000元宝 */
	readonly 2005: ConfigPropsData;
	/**10000元宝 */
	readonly 2006: ConfigPropsData;
	/**副本重置卡 */
	readonly 2007: ConfigPropsData;
	/**秘境重置卡 */
	readonly 2008: ConfigPropsData;
	/**BOSS重置卡 */
	readonly 2009: ConfigPropsData;
	/**门派邀请函 */
	readonly 2010: ConfigPropsData;
	/**首充礼包 */
	readonly 2011: ConfigPropsData;
	/**首充礼包2 */
	readonly 2012: ConfigPropsData;
	/**微型经验胶囊 */
	readonly 2013: ConfigPropsData;
	/**小型经验胶囊 */
	readonly 2014: ConfigPropsData;
	/**中型经验胶囊 */
	readonly 2015: ConfigPropsData;
	/**大型经验胶囊 */
	readonly 2016: ConfigPropsData;
	/**巨型经验胶囊 */
	readonly 2017: ConfigPropsData;
}