/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigErrorData {
	readonly ID: number;
	/**错误文本 */
	readonly text: string;
}

declare interface ConfigError extends KeyMap<ConfigErrorData> {
	/**啥也没有 */
	readonly 0: ConfigErrorData;
	/**未知的命令 */
	readonly 1000: ConfigErrorData;
	/**未知的数据类型 */
	readonly 1001: ConfigErrorData;
	/**用户不存在 */
	readonly 1002: ConfigErrorData;
	/**用户已存在 */
	readonly 1003: ConfigErrorData;
	/**账号为空 */
	readonly 1004: ConfigErrorData;
	/**密码为空 */
	readonly 1005: ConfigErrorData;
	/**昵称为空 */
	readonly 1006: ConfigErrorData;
	/**异地登陆 */
	readonly 1007: ConfigErrorData;
}